// -------------------------------------------------------------
// 
// File Name: /Users/yoland/Documents/MATLAB/hdlsrc/codegen/fm32bit_57kHz_filter/hdlsrc/FilterTapSystolicPreAddWvlIn.v
// Created: 2025-12-08 16:50:07
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterTapSystolicPreAddWvlIn
// Source Path: fm32bit_57kHz_filter/dsphdl.FIRFilter/Filter/subFilter/FilterTapSystolicPreAddWvlIn
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterTapSystolicPreAddWvlIn
          (clk,
           enb,
           dinReg2_0_re,
           dinPreAdd,
           coefIn_0,
           addin,
           dinRegVld,
           syncReset,
           dinDly2,
           tapout);


  input   clk;
  input   enb;
  input   signed [31:0] dinReg2_0_re;  // sfix32_En30
  input   signed [31:0] dinPreAdd;  // sfix32_En30
  input   signed [31:0] coefIn_0;  // sfix32_En35
  input   signed [67:0] addin;  // sfix68_En65
  input   dinRegVld;
  input   syncReset;
  output  signed [31:0] dinDly2;  // sfix32_En30
  output  signed [67:0] tapout;  // sfix68_En65


  reg signed [64:0] fTap_mult_reg;  // sfix65
  reg signed [31:0] fTap_din1_reg1;  // sfix32
  reg signed [31:0] fTap_din1_reg2;  // sfix32
  reg signed [31:0] fTap_din2_reg1;  // sfix32
  reg signed [32:0] fTap_preAdd_reg;  // sfix33
  reg signed [67:0] fTap_addout_reg;  // sfix68
  reg signed [31:0] fTap_coef_reg1;  // sfix32
  reg signed [31:0] fTap_coef_reg2;  // sfix32
  reg signed [64:0] fTap_mult_reg_next;  // sfix65_En65
  reg signed [31:0] fTap_din1_reg1_next;  // sfix32_En30
  reg signed [31:0] fTap_din1_reg2_next;  // sfix32_En30
  reg signed [31:0] fTap_din2_reg1_next;  // sfix32_En30
  reg signed [32:0] fTap_preAdd_reg_next;  // sfix33_En30
  reg signed [67:0] fTap_addout_reg_next;  // sfix68_En65
  reg signed [31:0] fTap_coef_reg1_next;  // sfix32_En35
  reg signed [31:0] fTap_coef_reg2_next;  // sfix32_En35
  reg signed [31:0] dinDly2_1;  // sfix32_En30
  reg signed [67:0] tapout_1;  // sfix68_En65
  reg signed [67:0] fTap_add_cast;  // sfix68_En65
  reg signed [32:0] fTap_add_cast_0;  // sfix33_En30
  reg signed [32:0] fTap_add_cast_1;  // sfix33_En30


  // FilterTapSystolicPreAddWvldIn
  always @(posedge clk)
    begin : fTap_process
      if (enb) begin
        if (syncReset == 1'b1) begin
          fTap_din1_reg1 <= 32'sb00000000000000000000000000000000;
          fTap_din1_reg2 <= 32'sb00000000000000000000000000000000;
          fTap_din2_reg1 <= 32'sb00000000000000000000000000000000;
          fTap_preAdd_reg <= 33'sh000000000;
          fTap_coef_reg1 <= 32'sb00000000000000000000000000000000;
          fTap_coef_reg2 <= 32'sb00000000000000000000000000000000;
          fTap_mult_reg <= 65'sh00000000000000000;
          fTap_addout_reg <= 68'sh00000000000000000;
        end
        else begin
          fTap_mult_reg <= fTap_mult_reg_next;
          fTap_din1_reg1 <= fTap_din1_reg1_next;
          fTap_din1_reg2 <= fTap_din1_reg2_next;
          fTap_din2_reg1 <= fTap_din2_reg1_next;
          fTap_preAdd_reg <= fTap_preAdd_reg_next;
          fTap_addout_reg <= fTap_addout_reg_next;
          fTap_coef_reg1 <= fTap_coef_reg1_next;
          fTap_coef_reg2 <= fTap_coef_reg2_next;
        end
      end
    end

  always @(addin, coefIn_0, dinPreAdd, dinReg2_0_re, dinRegVld, fTap_addout_reg,
       fTap_coef_reg1, fTap_coef_reg2, fTap_din1_reg1, fTap_din1_reg2,
       fTap_din2_reg1, fTap_mult_reg, fTap_preAdd_reg) begin
    fTap_add_cast = 68'sh00000000000000000;
    fTap_add_cast_0 = 33'sh000000000;
    fTap_add_cast_1 = 33'sh000000000;
    fTap_mult_reg_next = fTap_mult_reg;
    fTap_din1_reg1_next = fTap_din1_reg1;
    fTap_din1_reg2_next = fTap_din1_reg2;
    fTap_din2_reg1_next = fTap_din2_reg1;
    fTap_preAdd_reg_next = fTap_preAdd_reg;
    fTap_addout_reg_next = fTap_addout_reg;
    fTap_coef_reg1_next = fTap_coef_reg1;
    fTap_coef_reg2_next = fTap_coef_reg2;
    if (dinRegVld) begin
      fTap_add_cast = {{3{fTap_mult_reg[64]}}, fTap_mult_reg};
      fTap_addout_reg_next = fTap_add_cast + addin;
      fTap_mult_reg_next = fTap_preAdd_reg * fTap_coef_reg2;
      fTap_add_cast_0 = {fTap_din1_reg2[31], fTap_din1_reg2};
      fTap_add_cast_1 = {fTap_din2_reg1[31], fTap_din2_reg1};
      fTap_preAdd_reg_next = fTap_add_cast_0 + fTap_add_cast_1;
      fTap_din1_reg2_next = fTap_din1_reg1;
      fTap_din1_reg1_next = dinReg2_0_re;
      fTap_din2_reg1_next = dinPreAdd;
      fTap_coef_reg2_next = fTap_coef_reg1;
      fTap_coef_reg1_next = coefIn_0;
    end
    dinDly2_1 = fTap_din1_reg2;
    tapout_1 = fTap_addout_reg;
  end

  assign dinDly2 = dinDly2_1;

  assign tapout = tapout_1;

endmodule  // FilterTapSystolicPreAddWvlIn

