// -------------------------------------------------------------
// 
// File Name: /Users/yoland/Documents/MATLAB/hdlsrc/codegen/fm32bit_57kHz_filter/hdlsrc/dsphdl_FIRFilter.v
// Created: 2025-12-08 16:50:07
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsphdl_FIRFilter
// Source Path: fm32bit_57kHz_filter/dsphdl.FIRFilter
// Hierarchy Level: 1
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsphdl_FIRFilter57
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] dataIn;  // sfix32_En30
  input   validIn;
  output  signed [67:0] dataOut;  // sfix68_En65
  output  validOut;


  wire syncReset;


  assign syncReset = reset;

  Filter57 u_FilterBank (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix32_En30
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix68_En65
                       .validOut(validOut)
                       );

endmodule  // dsphdl_FIRFilter

