// -------------------------------------------------------------
// 
// File Name: /Users/yoland/Documents/MATLAB/hdlsrc/codegen/fm32bit_19kHz_filter/hdlsrc/dsphdl_FIRFilter.v
// Created: 2025-12-08 16:51:37
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsphdl_FIRFilter
// Source Path: fm32bit_19kHz_filter/dsphdl.FIRFilter
// Hierarchy Level: 1
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsphdl_FIRFilter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] dataIn;  // sfix32_En30
  input   validIn;
  output  signed [68:0] dataOut;  // sfix69_En66
  output  validOut;


  wire syncReset;


  assign syncReset = reset;

  Filter u_FilterBank (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix32_En30
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix69_En66
                       .validOut(validOut)
                       );

endmodule  // dsphdl_FIRFilter

