// -------------------------------------------------------------
// 
// File Name: /MATLAB Drive/codegen/fm_filter/hdlsrc/dsphdl_FIRFilter.v
// Created: 2025-12-07 22:11:16
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dsphdl_FIRFilter
// Source Path: fm_filter/dsphdl.FIRFilter
// Hierarchy Level: 1
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsphdl_FIRFilter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  output  signed [46:0] dataOut;  // sfix47_En45
  output  validOut;


  wire syncReset;


  assign syncReset = 1'b0;

  Filter u_FilterBank (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn(dataIn),  // sfix16_En15
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut(dataOut),  // sfix47_En45
                       .validOut(validOut)
                       );

endmodule  // dsphdl_FIRFilter

