// -------------------------------------------------------------
// 
// File Name: /Users/yoland/Documents/MATLAB/hdlsrc/codegen/fm32bit_19kHz_filter/hdlsrc/FilterCoef.v
// Created: 2025-12-08 16:51:37
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FilterCoef
// Source Path: fm32bit_19kHz_filter/dsphdl.FIRFilter/Filter/FilterCoef
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FilterCoef
          (validIn,
           syncReset,
           CoefOut_0,
           CoefOut_1,
           CoefOut_2,
           CoefOut_3,
           CoefOut_4,
           CoefOut_5,
           CoefOut_6,
           CoefOut_7,
           CoefOut_8,
           CoefOut_9,
           CoefOut_10,
           CoefOut_11,
           CoefOut_12,
           CoefOut_13,
           CoefOut_14,
           CoefOut_15,
           CoefOut_16,
           CoefOut_17,
           CoefOut_18,
           CoefOut_19,
           CoefOut_20,
           CoefOut_21,
           CoefOut_22,
           CoefOut_23,
           CoefOut_24,
           CoefOut_25,
           CoefOut_26,
           CoefOut_27,
           CoefOut_28,
           CoefOut_29,
           CoefOut_30,
           CoefOut_31,
           CoefOut_32,
           CoefOut_33,
           CoefOut_34,
           CoefOut_35,
           CoefOut_36,
           CoefOut_37,
           CoefOut_38,
           CoefOut_39,
           CoefOut_40,
           CoefOut_41,
           CoefOut_42,
           CoefOut_43,
           CoefOut_44,
           CoefOut_45,
           CoefOut_46,
           CoefOut_47,
           CoefOut_48,
           CoefOut_49,
           CoefOut_50,
           CoefOut_51,
           CoefOut_52,
           CoefOut_53,
           CoefOut_54,
           CoefOut_55,
           CoefOut_56,
           CoefOut_57,
           CoefOut_58,
           CoefOut_59,
           CoefOut_60,
           CoefOut_61,
           CoefOut_62,
           CoefOut_63,
           CoefOut_64,
           CoefOut_65,
           CoefOut_66,
           CoefOut_67,
           CoefOut_68,
           CoefOut_69,
           CoefOut_70,
           CoefOut_71,
           CoefOut_72,
           CoefOut_73,
           CoefOut_74,
           CoefOut_75,
           CoefOut_76,
           CoefOut_77,
           CoefOut_78,
           CoefOut_79,
           CoefOut_80,
           CoefOut_81,
           CoefOut_82,
           CoefOut_83,
           CoefOut_84,
           CoefOut_85,
           CoefOut_86,
           CoefOut_87,
           CoefOut_88,
           CoefOut_89,
           CoefOut_90,
           CoefOut_91,
           CoefOut_92,
           CoefOut_93,
           CoefOut_94,
           CoefOut_95,
           CoefOut_96,
           CoefOut_97,
           CoefOut_98,
           CoefOut_99,
           CoefOut_100,
           CoefOut_101,
           CoefOut_102,
           CoefOut_103,
           CoefOut_104,
           CoefOut_105,
           CoefOut_106,
           CoefOut_107,
           CoefOut_108,
           CoefOut_109,
           CoefOut_110,
           CoefOut_111,
           CoefOut_112,
           CoefOut_113,
           CoefOut_114,
           CoefOut_115,
           CoefOut_116,
           CoefOut_117,
           CoefOut_118,
           CoefOut_119,
           CoefOut_120,
           CoefOut_121,
           CoefOut_122,
           CoefOut_123,
           CoefOut_124,
           CoefOut_125,
           CoefOut_126,
           CoefOut_127,
           CoefOut_128,
           CoefOut_129,
           CoefOut_130,
           CoefOut_131,
           CoefOut_132,
           CoefOut_133,
           CoefOut_134,
           CoefOut_135,
           CoefOut_136,
           CoefOut_137,
           CoefOut_138,
           CoefOut_139,
           CoefOut_140,
           CoefOut_141,
           CoefOut_142,
           CoefOut_143,
           CoefOut_144,
           CoefOut_145,
           CoefOut_146,
           CoefOut_147,
           CoefOut_148,
           CoefOut_149,
           CoefOut_150,
           CoefOut_151,
           CoefOut_152,
           CoefOut_153,
           CoefOut_154,
           CoefOut_155,
           CoefOut_156,
           CoefOut_157,
           CoefOut_158,
           CoefOut_159,
           CoefOut_160,
           CoefOut_161,
           CoefOut_162,
           CoefOut_163,
           CoefOut_164,
           CoefOut_165);


  input   validIn;
  input   syncReset;
  output  signed [31:0] CoefOut_0;  // sfix32_En36
  output  signed [31:0] CoefOut_1;  // sfix32_En36
  output  signed [31:0] CoefOut_2;  // sfix32_En36
  output  signed [31:0] CoefOut_3;  // sfix32_En36
  output  signed [31:0] CoefOut_4;  // sfix32_En36
  output  signed [31:0] CoefOut_5;  // sfix32_En36
  output  signed [31:0] CoefOut_6;  // sfix32_En36
  output  signed [31:0] CoefOut_7;  // sfix32_En36
  output  signed [31:0] CoefOut_8;  // sfix32_En36
  output  signed [31:0] CoefOut_9;  // sfix32_En36
  output  signed [31:0] CoefOut_10;  // sfix32_En36
  output  signed [31:0] CoefOut_11;  // sfix32_En36
  output  signed [31:0] CoefOut_12;  // sfix32_En36
  output  signed [31:0] CoefOut_13;  // sfix32_En36
  output  signed [31:0] CoefOut_14;  // sfix32_En36
  output  signed [31:0] CoefOut_15;  // sfix32_En36
  output  signed [31:0] CoefOut_16;  // sfix32_En36
  output  signed [31:0] CoefOut_17;  // sfix32_En36
  output  signed [31:0] CoefOut_18;  // sfix32_En36
  output  signed [31:0] CoefOut_19;  // sfix32_En36
  output  signed [31:0] CoefOut_20;  // sfix32_En36
  output  signed [31:0] CoefOut_21;  // sfix32_En36
  output  signed [31:0] CoefOut_22;  // sfix32_En36
  output  signed [31:0] CoefOut_23;  // sfix32_En36
  output  signed [31:0] CoefOut_24;  // sfix32_En36
  output  signed [31:0] CoefOut_25;  // sfix32_En36
  output  signed [31:0] CoefOut_26;  // sfix32_En36
  output  signed [31:0] CoefOut_27;  // sfix32_En36
  output  signed [31:0] CoefOut_28;  // sfix32_En36
  output  signed [31:0] CoefOut_29;  // sfix32_En36
  output  signed [31:0] CoefOut_30;  // sfix32_En36
  output  signed [31:0] CoefOut_31;  // sfix32_En36
  output  signed [31:0] CoefOut_32;  // sfix32_En36
  output  signed [31:0] CoefOut_33;  // sfix32_En36
  output  signed [31:0] CoefOut_34;  // sfix32_En36
  output  signed [31:0] CoefOut_35;  // sfix32_En36
  output  signed [31:0] CoefOut_36;  // sfix32_En36
  output  signed [31:0] CoefOut_37;  // sfix32_En36
  output  signed [31:0] CoefOut_38;  // sfix32_En36
  output  signed [31:0] CoefOut_39;  // sfix32_En36
  output  signed [31:0] CoefOut_40;  // sfix32_En36
  output  signed [31:0] CoefOut_41;  // sfix32_En36
  output  signed [31:0] CoefOut_42;  // sfix32_En36
  output  signed [31:0] CoefOut_43;  // sfix32_En36
  output  signed [31:0] CoefOut_44;  // sfix32_En36
  output  signed [31:0] CoefOut_45;  // sfix32_En36
  output  signed [31:0] CoefOut_46;  // sfix32_En36
  output  signed [31:0] CoefOut_47;  // sfix32_En36
  output  signed [31:0] CoefOut_48;  // sfix32_En36
  output  signed [31:0] CoefOut_49;  // sfix32_En36
  output  signed [31:0] CoefOut_50;  // sfix32_En36
  output  signed [31:0] CoefOut_51;  // sfix32_En36
  output  signed [31:0] CoefOut_52;  // sfix32_En36
  output  signed [31:0] CoefOut_53;  // sfix32_En36
  output  signed [31:0] CoefOut_54;  // sfix32_En36
  output  signed [31:0] CoefOut_55;  // sfix32_En36
  output  signed [31:0] CoefOut_56;  // sfix32_En36
  output  signed [31:0] CoefOut_57;  // sfix32_En36
  output  signed [31:0] CoefOut_58;  // sfix32_En36
  output  signed [31:0] CoefOut_59;  // sfix32_En36
  output  signed [31:0] CoefOut_60;  // sfix32_En36
  output  signed [31:0] CoefOut_61;  // sfix32_En36
  output  signed [31:0] CoefOut_62;  // sfix32_En36
  output  signed [31:0] CoefOut_63;  // sfix32_En36
  output  signed [31:0] CoefOut_64;  // sfix32_En36
  output  signed [31:0] CoefOut_65;  // sfix32_En36
  output  signed [31:0] CoefOut_66;  // sfix32_En36
  output  signed [31:0] CoefOut_67;  // sfix32_En36
  output  signed [31:0] CoefOut_68;  // sfix32_En36
  output  signed [31:0] CoefOut_69;  // sfix32_En36
  output  signed [31:0] CoefOut_70;  // sfix32_En36
  output  signed [31:0] CoefOut_71;  // sfix32_En36
  output  signed [31:0] CoefOut_72;  // sfix32_En36
  output  signed [31:0] CoefOut_73;  // sfix32_En36
  output  signed [31:0] CoefOut_74;  // sfix32_En36
  output  signed [31:0] CoefOut_75;  // sfix32_En36
  output  signed [31:0] CoefOut_76;  // sfix32_En36
  output  signed [31:0] CoefOut_77;  // sfix32_En36
  output  signed [31:0] CoefOut_78;  // sfix32_En36
  output  signed [31:0] CoefOut_79;  // sfix32_En36
  output  signed [31:0] CoefOut_80;  // sfix32_En36
  output  signed [31:0] CoefOut_81;  // sfix32_En36
  output  signed [31:0] CoefOut_82;  // sfix32_En36
  output  signed [31:0] CoefOut_83;  // sfix32_En36
  output  signed [31:0] CoefOut_84;  // sfix32_En36
  output  signed [31:0] CoefOut_85;  // sfix32_En36
  output  signed [31:0] CoefOut_86;  // sfix32_En36
  output  signed [31:0] CoefOut_87;  // sfix32_En36
  output  signed [31:0] CoefOut_88;  // sfix32_En36
  output  signed [31:0] CoefOut_89;  // sfix32_En36
  output  signed [31:0] CoefOut_90;  // sfix32_En36
  output  signed [31:0] CoefOut_91;  // sfix32_En36
  output  signed [31:0] CoefOut_92;  // sfix32_En36
  output  signed [31:0] CoefOut_93;  // sfix32_En36
  output  signed [31:0] CoefOut_94;  // sfix32_En36
  output  signed [31:0] CoefOut_95;  // sfix32_En36
  output  signed [31:0] CoefOut_96;  // sfix32_En36
  output  signed [31:0] CoefOut_97;  // sfix32_En36
  output  signed [31:0] CoefOut_98;  // sfix32_En36
  output  signed [31:0] CoefOut_99;  // sfix32_En36
  output  signed [31:0] CoefOut_100;  // sfix32_En36
  output  signed [31:0] CoefOut_101;  // sfix32_En36
  output  signed [31:0] CoefOut_102;  // sfix32_En36
  output  signed [31:0] CoefOut_103;  // sfix32_En36
  output  signed [31:0] CoefOut_104;  // sfix32_En36
  output  signed [31:0] CoefOut_105;  // sfix32_En36
  output  signed [31:0] CoefOut_106;  // sfix32_En36
  output  signed [31:0] CoefOut_107;  // sfix32_En36
  output  signed [31:0] CoefOut_108;  // sfix32_En36
  output  signed [31:0] CoefOut_109;  // sfix32_En36
  output  signed [31:0] CoefOut_110;  // sfix32_En36
  output  signed [31:0] CoefOut_111;  // sfix32_En36
  output  signed [31:0] CoefOut_112;  // sfix32_En36
  output  signed [31:0] CoefOut_113;  // sfix32_En36
  output  signed [31:0] CoefOut_114;  // sfix32_En36
  output  signed [31:0] CoefOut_115;  // sfix32_En36
  output  signed [31:0] CoefOut_116;  // sfix32_En36
  output  signed [31:0] CoefOut_117;  // sfix32_En36
  output  signed [31:0] CoefOut_118;  // sfix32_En36
  output  signed [31:0] CoefOut_119;  // sfix32_En36
  output  signed [31:0] CoefOut_120;  // sfix32_En36
  output  signed [31:0] CoefOut_121;  // sfix32_En36
  output  signed [31:0] CoefOut_122;  // sfix32_En36
  output  signed [31:0] CoefOut_123;  // sfix32_En36
  output  signed [31:0] CoefOut_124;  // sfix32_En36
  output  signed [31:0] CoefOut_125;  // sfix32_En36
  output  signed [31:0] CoefOut_126;  // sfix32_En36
  output  signed [31:0] CoefOut_127;  // sfix32_En36
  output  signed [31:0] CoefOut_128;  // sfix32_En36
  output  signed [31:0] CoefOut_129;  // sfix32_En36
  output  signed [31:0] CoefOut_130;  // sfix32_En36
  output  signed [31:0] CoefOut_131;  // sfix32_En36
  output  signed [31:0] CoefOut_132;  // sfix32_En36
  output  signed [31:0] CoefOut_133;  // sfix32_En36
  output  signed [31:0] CoefOut_134;  // sfix32_En36
  output  signed [31:0] CoefOut_135;  // sfix32_En36
  output  signed [31:0] CoefOut_136;  // sfix32_En36
  output  signed [31:0] CoefOut_137;  // sfix32_En36
  output  signed [31:0] CoefOut_138;  // sfix32_En36
  output  signed [31:0] CoefOut_139;  // sfix32_En36
  output  signed [31:0] CoefOut_140;  // sfix32_En36
  output  signed [31:0] CoefOut_141;  // sfix32_En36
  output  signed [31:0] CoefOut_142;  // sfix32_En36
  output  signed [31:0] CoefOut_143;  // sfix32_En36
  output  signed [31:0] CoefOut_144;  // sfix32_En36
  output  signed [31:0] CoefOut_145;  // sfix32_En36
  output  signed [31:0] CoefOut_146;  // sfix32_En36
  output  signed [31:0] CoefOut_147;  // sfix32_En36
  output  signed [31:0] CoefOut_148;  // sfix32_En36
  output  signed [31:0] CoefOut_149;  // sfix32_En36
  output  signed [31:0] CoefOut_150;  // sfix32_En36
  output  signed [31:0] CoefOut_151;  // sfix32_En36
  output  signed [31:0] CoefOut_152;  // sfix32_En36
  output  signed [31:0] CoefOut_153;  // sfix32_En36
  output  signed [31:0] CoefOut_154;  // sfix32_En36
  output  signed [31:0] CoefOut_155;  // sfix32_En36
  output  signed [31:0] CoefOut_156;  // sfix32_En36
  output  signed [31:0] CoefOut_157;  // sfix32_En36
  output  signed [31:0] CoefOut_158;  // sfix32_En36
  output  signed [31:0] CoefOut_159;  // sfix32_En36
  output  signed [31:0] CoefOut_160;  // sfix32_En36
  output  signed [31:0] CoefOut_161;  // sfix32_En36
  output  signed [31:0] CoefOut_162;  // sfix32_En36
  output  signed [31:0] CoefOut_163;  // sfix32_En36
  output  signed [31:0] CoefOut_164;  // sfix32_En36
  output  signed [31:0] CoefOut_165;  // sfix32_En36


  wire signed [31:0] CoefData;  // sfix32_En36
  wire signed [31:0] CoefData_1;  // sfix32_En36
  wire signed [31:0] CoefData_2;  // sfix32_En36
  wire signed [31:0] CoefData_3;  // sfix32_En36
  wire signed [31:0] CoefData_4;  // sfix32_En36
  wire signed [31:0] CoefData_5;  // sfix32_En36
  wire signed [31:0] CoefData_6;  // sfix32_En36
  wire signed [31:0] CoefData_7;  // sfix32_En36
  wire signed [31:0] CoefData_8;  // sfix32_En36
  wire signed [31:0] CoefData_9;  // sfix32_En36
  wire signed [31:0] CoefData_10;  // sfix32_En36
  wire signed [31:0] CoefData_11;  // sfix32_En36
  wire signed [31:0] CoefData_12;  // sfix32_En36
  wire signed [31:0] CoefData_13;  // sfix32_En36
  wire signed [31:0] CoefData_14;  // sfix32_En36
  wire signed [31:0] CoefData_15;  // sfix32_En36
  wire signed [31:0] CoefData_16;  // sfix32_En36
  wire signed [31:0] CoefData_17;  // sfix32_En36
  wire signed [31:0] CoefData_18;  // sfix32_En36
  wire signed [31:0] CoefData_19;  // sfix32_En36
  wire signed [31:0] CoefData_20;  // sfix32_En36
  wire signed [31:0] CoefData_21;  // sfix32_En36
  wire signed [31:0] CoefData_22;  // sfix32_En36
  wire signed [31:0] CoefData_23;  // sfix32_En36
  wire signed [31:0] CoefData_24;  // sfix32_En36
  wire signed [31:0] CoefData_25;  // sfix32_En36
  wire signed [31:0] CoefData_26;  // sfix32_En36
  wire signed [31:0] CoefData_27;  // sfix32_En36
  wire signed [31:0] CoefData_28;  // sfix32_En36
  wire signed [31:0] CoefData_29;  // sfix32_En36
  wire signed [31:0] CoefData_30;  // sfix32_En36
  wire signed [31:0] CoefData_31;  // sfix32_En36
  wire signed [31:0] CoefData_32;  // sfix32_En36
  wire signed [31:0] CoefData_33;  // sfix32_En36
  wire signed [31:0] CoefData_34;  // sfix32_En36
  wire signed [31:0] CoefData_35;  // sfix32_En36
  wire signed [31:0] CoefData_36;  // sfix32_En36
  wire signed [31:0] CoefData_37;  // sfix32_En36
  wire signed [31:0] CoefData_38;  // sfix32_En36
  wire signed [31:0] CoefData_39;  // sfix32_En36
  wire signed [31:0] CoefData_40;  // sfix32_En36
  wire signed [31:0] CoefData_41;  // sfix32_En36
  wire signed [31:0] CoefData_42;  // sfix32_En36
  wire signed [31:0] CoefData_43;  // sfix32_En36
  wire signed [31:0] CoefData_44;  // sfix32_En36
  wire signed [31:0] CoefData_45;  // sfix32_En36
  wire signed [31:0] CoefData_46;  // sfix32_En36
  wire signed [31:0] CoefData_47;  // sfix32_En36
  wire signed [31:0] CoefData_48;  // sfix32_En36
  wire signed [31:0] CoefData_49;  // sfix32_En36
  wire signed [31:0] CoefData_50;  // sfix32_En36
  wire signed [31:0] CoefData_51;  // sfix32_En36
  wire signed [31:0] CoefData_52;  // sfix32_En36
  wire signed [31:0] CoefData_53;  // sfix32_En36
  wire signed [31:0] CoefData_54;  // sfix32_En36
  wire signed [31:0] CoefData_55;  // sfix32_En36
  wire signed [31:0] CoefData_56;  // sfix32_En36
  wire signed [31:0] CoefData_57;  // sfix32_En36
  wire signed [31:0] CoefData_58;  // sfix32_En36
  wire signed [31:0] CoefData_59;  // sfix32_En36
  wire signed [31:0] CoefData_60;  // sfix32_En36
  wire signed [31:0] CoefData_61;  // sfix32_En36
  wire signed [31:0] CoefData_62;  // sfix32_En36
  wire signed [31:0] CoefData_63;  // sfix32_En36
  wire signed [31:0] CoefData_64;  // sfix32_En36
  wire signed [31:0] CoefData_65;  // sfix32_En36
  wire signed [31:0] CoefData_66;  // sfix32_En36
  wire signed [31:0] CoefData_67;  // sfix32_En36
  wire signed [31:0] CoefData_68;  // sfix32_En36
  wire signed [31:0] CoefData_69;  // sfix32_En36
  wire signed [31:0] CoefData_70;  // sfix32_En36
  wire signed [31:0] CoefData_71;  // sfix32_En36
  wire signed [31:0] CoefData_72;  // sfix32_En36
  wire signed [31:0] CoefData_73;  // sfix32_En36
  wire signed [31:0] CoefData_74;  // sfix32_En36
  wire signed [31:0] CoefData_75;  // sfix32_En36
  wire signed [31:0] CoefData_76;  // sfix32_En36
  wire signed [31:0] CoefData_77;  // sfix32_En36
  wire signed [31:0] CoefData_78;  // sfix32_En36
  wire signed [31:0] CoefData_79;  // sfix32_En36
  wire signed [31:0] CoefData_80;  // sfix32_En36
  wire signed [31:0] CoefData_81;  // sfix32_En36
  wire signed [31:0] CoefData_82;  // sfix32_En36
  wire signed [31:0] CoefData_83;  // sfix32_En36
  wire signed [31:0] CoefData_84;  // sfix32_En36
  wire signed [31:0] CoefData_85;  // sfix32_En36
  wire signed [31:0] CoefData_86;  // sfix32_En36
  wire signed [31:0] CoefData_87;  // sfix32_En36
  wire signed [31:0] CoefData_88;  // sfix32_En36
  wire signed [31:0] CoefData_89;  // sfix32_En36
  wire signed [31:0] CoefData_90;  // sfix32_En36
  wire signed [31:0] CoefData_91;  // sfix32_En36
  wire signed [31:0] CoefData_92;  // sfix32_En36
  wire signed [31:0] CoefData_93;  // sfix32_En36
  wire signed [31:0] CoefData_94;  // sfix32_En36
  wire signed [31:0] CoefData_95;  // sfix32_En36
  wire signed [31:0] CoefData_96;  // sfix32_En36
  wire signed [31:0] CoefData_97;  // sfix32_En36
  wire signed [31:0] CoefData_98;  // sfix32_En36
  wire signed [31:0] CoefData_99;  // sfix32_En36
  wire signed [31:0] CoefData_100;  // sfix32_En36
  wire signed [31:0] CoefData_101;  // sfix32_En36
  wire signed [31:0] CoefData_102;  // sfix32_En36
  wire signed [31:0] CoefData_103;  // sfix32_En36
  wire signed [31:0] CoefData_104;  // sfix32_En36
  wire signed [31:0] CoefData_105;  // sfix32_En36
  wire signed [31:0] CoefData_106;  // sfix32_En36
  wire signed [31:0] CoefData_107;  // sfix32_En36
  wire signed [31:0] CoefData_108;  // sfix32_En36
  wire signed [31:0] CoefData_109;  // sfix32_En36
  wire signed [31:0] CoefData_110;  // sfix32_En36
  wire signed [31:0] CoefData_111;  // sfix32_En36
  wire signed [31:0] CoefData_112;  // sfix32_En36
  wire signed [31:0] CoefData_113;  // sfix32_En36
  wire signed [31:0] CoefData_114;  // sfix32_En36
  wire signed [31:0] CoefData_115;  // sfix32_En36
  wire signed [31:0] CoefData_116;  // sfix32_En36
  wire signed [31:0] CoefData_117;  // sfix32_En36
  wire signed [31:0] CoefData_118;  // sfix32_En36
  wire signed [31:0] CoefData_119;  // sfix32_En36
  wire signed [31:0] CoefData_120;  // sfix32_En36
  wire signed [31:0] CoefData_121;  // sfix32_En36
  wire signed [31:0] CoefData_122;  // sfix32_En36
  wire signed [31:0] CoefData_123;  // sfix32_En36
  wire signed [31:0] CoefData_124;  // sfix32_En36
  wire signed [31:0] CoefData_125;  // sfix32_En36
  wire signed [31:0] CoefData_126;  // sfix32_En36
  wire signed [31:0] CoefData_127;  // sfix32_En36
  wire signed [31:0] CoefData_128;  // sfix32_En36
  wire signed [31:0] CoefData_129;  // sfix32_En36
  wire signed [31:0] CoefData_130;  // sfix32_En36
  wire signed [31:0] CoefData_131;  // sfix32_En36
  wire signed [31:0] CoefData_132;  // sfix32_En36
  wire signed [31:0] CoefData_133;  // sfix32_En36
  wire signed [31:0] CoefData_134;  // sfix32_En36
  wire signed [31:0] CoefData_135;  // sfix32_En36
  wire signed [31:0] CoefData_136;  // sfix32_En36
  wire signed [31:0] CoefData_137;  // sfix32_En36
  wire signed [31:0] CoefData_138;  // sfix32_En36
  wire signed [31:0] CoefData_139;  // sfix32_En36
  wire signed [31:0] CoefData_140;  // sfix32_En36
  wire signed [31:0] CoefData_141;  // sfix32_En36
  wire signed [31:0] CoefData_142;  // sfix32_En36
  wire signed [31:0] CoefData_143;  // sfix32_En36
  wire signed [31:0] CoefData_144;  // sfix32_En36
  wire signed [31:0] CoefData_145;  // sfix32_En36
  wire signed [31:0] CoefData_146;  // sfix32_En36
  wire signed [31:0] CoefData_147;  // sfix32_En36
  wire signed [31:0] CoefData_148;  // sfix32_En36
  wire signed [31:0] CoefData_149;  // sfix32_En36
  wire signed [31:0] CoefData_150;  // sfix32_En36
  wire signed [31:0] CoefData_151;  // sfix32_En36
  wire signed [31:0] CoefData_152;  // sfix32_En36
  wire signed [31:0] CoefData_153;  // sfix32_En36
  wire signed [31:0] CoefData_154;  // sfix32_En36
  wire signed [31:0] CoefData_155;  // sfix32_En36
  wire signed [31:0] CoefData_156;  // sfix32_En36
  wire signed [31:0] CoefData_157;  // sfix32_En36
  wire signed [31:0] CoefData_158;  // sfix32_En36
  wire signed [31:0] CoefData_159;  // sfix32_En36
  wire signed [31:0] CoefData_160;  // sfix32_En36
  wire signed [31:0] CoefData_161;  // sfix32_En36
  wire signed [31:0] CoefData_162;  // sfix32_En36
  wire signed [31:0] CoefData_163;  // sfix32_En36
  wire signed [31:0] CoefData_164;  // sfix32_En36
  wire signed [31:0] CoefData_165;  // sfix32_En36


  // CoefReg_1
  assign CoefData = 32'sb00000010100101011011101001000000;

  assign CoefOut_0 = CoefData;

  // CoefReg_2
  assign CoefData_1 = 32'sb11111101110110100000010110000000;

  assign CoefOut_1 = CoefData_1;

  // CoefReg_3
  assign CoefData_2 = 32'sb11111110101000010010011110000000;

  assign CoefOut_2 = CoefData_2;

  // CoefReg_4
  assign CoefData_3 = 32'sb11111111001100010000110111000000;

  assign CoefOut_3 = CoefData_3;

  // CoefReg_5
  assign CoefData_4 = 32'sb11111111100110010110110100000000;

  assign CoefOut_4 = CoefData_4;

  // CoefReg_6
  assign CoefData_5 = 32'sb11111111110110110001110000000000;

  assign CoefOut_5 = CoefData_5;

  // CoefReg_7
  assign CoefData_6 = 32'sb11111111111011010100011110000000;

  assign CoefOut_6 = CoefData_6;

  // CoefReg_8
  assign CoefData_7 = 32'sb11111111110001100110100110000000;

  assign CoefOut_7 = CoefData_7;

  // CoefReg_9
  assign CoefData_8 = 32'sb11111111011010000100011101000000;

  assign CoefOut_8 = CoefData_8;

  // CoefReg_10
  assign CoefData_9 = 32'sb11111110111010000011001001000000;

  assign CoefOut_9 = CoefData_9;

  // CoefReg_11
  assign CoefData_10 = 32'sb11111110011100011110100100000000;

  assign CoefOut_10 = CoefData_10;

  // CoefReg_12
  assign CoefData_11 = 32'sb11111110001111110110011011000000;

  assign CoefOut_11 = CoefData_11;

  // CoefReg_13
  assign CoefData_12 = 32'sb11111110100010001101001110000000;

  assign CoefOut_12 = CoefData_12;

  // CoefReg_14
  assign CoefData_13 = 32'sb11111111011011100011000111000000;

  assign CoefOut_13 = CoefData_13;

  // CoefReg_15
  assign CoefData_14 = 32'sb00000000111000111111011011000000;

  assign CoefOut_14 = CoefData_14;

  // CoefReg_16
  assign CoefData_15 = 32'sb00000010101001111100100101000000;

  assign CoefOut_15 = CoefData_15;

  // CoefReg_17
  assign CoefData_16 = 32'sb00000100010001100101101010000000;

  assign CoefOut_16 = CoefData_16;

  // CoefReg_18
  assign CoefData_17 = 32'sb00000101001100100001111001000000;

  assign CoefOut_17 = CoefData_17;

  // CoefReg_19
  assign CoefData_18 = 32'sb00000100111010100101001001000000;

  assign CoefOut_18 = CoefData_18;

  // CoefReg_20
  assign CoefData_19 = 32'sb00000011001001101010111000000000;

  assign CoefOut_19 = CoefData_19;

  // CoefReg_21
  assign CoefData_20 = 32'sb11111111111111011011010001000000;

  assign CoefOut_20 = CoefData_20;

  // CoefReg_22
  assign CoefData_21 = 32'sb11111011111101010011001011000000;

  assign CoefOut_21 = CoefData_21;

  // CoefReg_23
  assign CoefData_22 = 32'sb11110111111101101011101010000000;

  assign CoefOut_22 = CoefData_22;

  // CoefReg_24
  assign CoefData_23 = 32'sb11110101001000010011111111000000;

  assign CoefOut_23 = CoefData_23;

  // CoefReg_25
  assign CoefData_24 = 32'sb11110100100000110010111000000000;

  assign CoefOut_24 = CoefData_24;

  // CoefReg_26
  assign CoefData_25 = 32'sb11110110110001111110111100000000;

  assign CoefOut_25 = CoefData_25;

  // CoefReg_27
  assign CoefData_26 = 32'sb11111011111101000100000110000000;

  assign CoefOut_26 = CoefData_26;

  // CoefReg_28
  assign CoefData_27 = 32'sb00000011010000010010001111000000;

  assign CoefOut_27 = CoefData_27;

  // CoefReg_29
  assign CoefData_28 = 32'sb00001011001011101011101100000000;

  assign CoefOut_28 = CoefData_28;

  // CoefReg_30
  assign CoefData_29 = 32'sb00010001110001001111111110000000;

  assign CoefOut_29 = CoefData_29;

  // CoefReg_31
  assign CoefData_30 = 32'sb00010101000011111111000001000000;

  assign CoefOut_30 = CoefData_30;

  // CoefReg_32
  assign CoefData_31 = 32'sb00010011100111000111111010000000;

  assign CoefOut_31 = CoefData_31;

  // CoefReg_33
  assign CoefData_32 = 32'sb00001100111110101110010101000000;

  assign CoefOut_32 = CoefData_32;

  // CoefReg_34
  assign CoefData_33 = 32'sb00000010000000101100101100000000;

  assign CoefOut_33 = CoefData_33;

  // CoefReg_35
  assign CoefData_34 = 32'sb11110100110010111010010001000000;

  assign CoefOut_34 = CoefData_34;

  // CoefReg_36
  assign CoefData_35 = 32'sb11101000010101010101001011000000;

  assign CoefOut_35 = CoefData_35;

  // CoefReg_37
  assign CoefData_36 = 32'sb11011111111000000110101100000000;

  assign CoefOut_36 = CoefData_36;

  // CoefReg_38
  assign CoefData_37 = 32'sb11011110000111100000001111000000;

  assign CoefOut_37 = CoefData_37;

  // CoefReg_39
  assign CoefData_38 = 32'sb11100100011010101110111101000000;

  assign CoefOut_38 = CoefData_38;

  // CoefReg_40
  assign CoefData_39 = 32'sb11110010010010011110111011000000;

  assign CoefOut_39 = CoefData_39;

  // CoefReg_41
  assign CoefData_40 = 32'sb00000101010001100000111111000000;

  assign CoefOut_40 = CoefData_40;

  // CoefReg_42
  assign CoefData_41 = 32'sb00011001010100110111111100000000;

  assign CoefOut_41 = CoefData_41;

  // CoefReg_43
  assign CoefData_42 = 32'sb00101001101001010010010101000000;

  assign CoefOut_42 = CoefData_42;

  // CoefReg_44
  assign CoefData_43 = 32'sb00110001110011001100100100000000;

  assign CoefOut_43 = CoefData_43;

  // CoefReg_45
  assign CoefData_44 = 32'sb00101110111000110010011111000000;

  assign CoefOut_44 = CoefData_44;

  // CoefReg_46
  assign CoefData_45 = 32'sb00100000011011000000111001000000;

  assign CoefOut_45 = CoefData_45;

  // CoefReg_47
  assign CoefData_46 = 32'sb00001000101101011111010100000000;

  assign CoefOut_46 = CoefData_46;

  // CoefReg_48
  assign CoefData_47 = 32'sb11101100100011111000001100000000;

  assign CoefOut_47 = CoefData_47;

  // CoefReg_49
  assign CoefData_48 = 32'sb11010010010101010111110101000000;

  assign CoefOut_48 = CoefData_48;

  // CoefReg_50
  assign CoefData_49 = 32'sb11000000100001010111111100000000;

  assign CoefOut_49 = CoefData_49;

  // CoefReg_51
  assign CoefData_50 = 32'sb10111100001010000001101101000000;

  assign CoefOut_50 = CoefData_50;

  // CoefReg_52
  assign CoefData_51 = 32'sb11000111011100101101001100000000;

  assign CoefOut_51 = CoefData_51;

  // CoefReg_53
  assign CoefData_52 = 32'sb11100001000000010010101110000000;

  assign CoefOut_52 = CoefData_52;

  // CoefReg_54
  assign CoefData_53 = 32'sb00000011111000000101100100000000;

  assign CoefOut_53 = CoefData_53;

  // CoefReg_55
  assign CoefData_54 = 32'sb00101000011111010100000000000000;

  assign CoefOut_54 = CoefData_54;

  // CoefReg_56
  assign CoefData_55 = 32'sb01000110010010001010010100000000;

  assign CoefOut_55 = CoefData_55;

  // CoefReg_57
  assign CoefData_56 = 32'sb01010101101110010010100101000000;

  assign CoefOut_56 = CoefData_56;

  // CoefReg_58
  assign CoefData_57 = 32'sb01010010001011101110100110000000;

  assign CoefOut_57 = CoefData_57;

  // CoefReg_59
  assign CoefData_58 = 32'sb00111011010001000110011100000000;

  assign CoefOut_58 = CoefData_58;

  // CoefReg_60
  assign CoefData_59 = 32'sb00010101001010011100011001000000;

  assign CoefOut_59 = CoefData_59;

  // CoefReg_61
  assign CoefData_60 = 32'sb11100111111011000001110010000000;

  assign CoefOut_60 = CoefData_60;

  // CoefReg_62
  assign CoefData_61 = 32'sb10111101110000000010001010000000;

  assign CoefOut_61 = CoefData_61;

  // CoefReg_63
  assign CoefData_62 = 32'sb10100000101011101100001001000000;

  assign CoefOut_62 = CoefData_62;

  // CoefReg_64
  assign CoefData_63 = 32'sb10011000001011101000101101000000;

  assign CoefOut_63 = CoefData_63;

  // CoefReg_65
  assign CoefData_64 = 32'sb10100111001110100000001010000000;

  assign CoefOut_64 = CoefData_64;

  // CoefReg_66
  assign CoefData_65 = 32'sb11001011011001000010000001000000;

  assign CoefOut_65 = CoefData_65;

  // CoefReg_67
  assign CoefData_66 = 32'sb11111101001011100010001011000000;

  assign CoefOut_66 = CoefData_66;

  // CoefReg_68
  assign CoefData_67 = 32'sb00110001100101110000101001000000;

  assign CoefOut_67 = CoefData_67;

  // CoefReg_69
  assign CoefData_68 = 32'sb01011100100100100110101101000000;

  assign CoefOut_68 = CoefData_68;

  // CoefReg_70
  assign CoefData_69 = 32'sb01110011110110000000000111000000;

  assign CoefOut_69 = CoefData_69;

  // CoefReg_71
  assign CoefData_70 = 32'sb01110001011000000101010001000000;

  assign CoefOut_70 = CoefData_70;

  // CoefReg_72
  assign CoefData_71 = 32'sb01010100111100110100011110000000;

  assign CoefOut_71 = CoefData_71;

  // CoefReg_73
  assign CoefData_72 = 32'sb00100100011000100101001000000000;

  assign CoefOut_72 = CoefData_72;

  // CoefReg_74
  assign CoefData_73 = 32'sb11101010010101010111010011000000;

  assign CoefOut_73 = CoefData_73;

  // CoefReg_75
  assign CoefData_74 = 32'sb10110011111010101011100001000000;

  assign CoefOut_74 = CoefData_74;

  // CoefReg_76
  assign CoefData_75 = 32'sb10001101101100100100010010000000;

  assign CoefOut_75 = CoefData_75;

  // CoefReg_77
  assign CoefData_76 = 32'sb10000000101110110110011011000000;

  assign CoefOut_76 = CoefData_76;

  // CoefReg_78
  assign CoefData_77 = 32'sb10010000011001100101101001000000;

  assign CoefOut_77 = CoefData_77;

  // CoefReg_79
  assign CoefData_78 = 32'sb10111001100001000100111100000000;

  assign CoefOut_78 = CoefData_78;

  // CoefReg_80
  assign CoefData_79 = 32'sb11110010111111010101010110000000;

  assign CoefOut_79 = CoefData_79;

  // CoefReg_81
  assign CoefData_80 = 32'sb00101111110111010011100111000000;

  assign CoefOut_80 = CoefData_80;

  // CoefReg_82
  assign CoefData_81 = 32'sb01100010010011001111111000000000;

  assign CoefOut_81 = CoefData_81;

  // CoefReg_83
  assign CoefData_82 = 32'sb01111110110001110110100010000000;

  assign CoefOut_82 = CoefData_82;

  // CoefReg_84
  assign CoefData_83 = 32'sb01111110110001110110100010000000;

  assign CoefOut_83 = CoefData_83;

  // CoefReg_85
  assign CoefData_84 = 32'sb01100010010011001111111000000000;

  assign CoefOut_84 = CoefData_84;

  // CoefReg_86
  assign CoefData_85 = 32'sb00101111110111010011100111000000;

  assign CoefOut_85 = CoefData_85;

  // CoefReg_87
  assign CoefData_86 = 32'sb11110010111111010101010110000000;

  assign CoefOut_86 = CoefData_86;

  // CoefReg_88
  assign CoefData_87 = 32'sb10111001100001000100111100000000;

  assign CoefOut_87 = CoefData_87;

  // CoefReg_89
  assign CoefData_88 = 32'sb10010000011001100101101001000000;

  assign CoefOut_88 = CoefData_88;

  // CoefReg_90
  assign CoefData_89 = 32'sb10000000101110110110011011000000;

  assign CoefOut_89 = CoefData_89;

  // CoefReg_91
  assign CoefData_90 = 32'sb10001101101100100100010010000000;

  assign CoefOut_90 = CoefData_90;

  // CoefReg_92
  assign CoefData_91 = 32'sb10110011111010101011100001000000;

  assign CoefOut_91 = CoefData_91;

  // CoefReg_93
  assign CoefData_92 = 32'sb11101010010101010111010011000000;

  assign CoefOut_92 = CoefData_92;

  // CoefReg_94
  assign CoefData_93 = 32'sb00100100011000100101001000000000;

  assign CoefOut_93 = CoefData_93;

  // CoefReg_95
  assign CoefData_94 = 32'sb01010100111100110100011110000000;

  assign CoefOut_94 = CoefData_94;

  // CoefReg_96
  assign CoefData_95 = 32'sb01110001011000000101010001000000;

  assign CoefOut_95 = CoefData_95;

  // CoefReg_97
  assign CoefData_96 = 32'sb01110011110110000000000111000000;

  assign CoefOut_96 = CoefData_96;

  // CoefReg_98
  assign CoefData_97 = 32'sb01011100100100100110101101000000;

  assign CoefOut_97 = CoefData_97;

  // CoefReg_99
  assign CoefData_98 = 32'sb00110001100101110000101001000000;

  assign CoefOut_98 = CoefData_98;

  // CoefReg_100
  assign CoefData_99 = 32'sb11111101001011100010001011000000;

  assign CoefOut_99 = CoefData_99;

  // CoefReg_101
  assign CoefData_100 = 32'sb11001011011001000010000001000000;

  assign CoefOut_100 = CoefData_100;

  // CoefReg_102
  assign CoefData_101 = 32'sb10100111001110100000001010000000;

  assign CoefOut_101 = CoefData_101;

  // CoefReg_103
  assign CoefData_102 = 32'sb10011000001011101000101101000000;

  assign CoefOut_102 = CoefData_102;

  // CoefReg_104
  assign CoefData_103 = 32'sb10100000101011101100001001000000;

  assign CoefOut_103 = CoefData_103;

  // CoefReg_105
  assign CoefData_104 = 32'sb10111101110000000010001010000000;

  assign CoefOut_104 = CoefData_104;

  // CoefReg_106
  assign CoefData_105 = 32'sb11100111111011000001110010000000;

  assign CoefOut_105 = CoefData_105;

  // CoefReg_107
  assign CoefData_106 = 32'sb00010101001010011100011001000000;

  assign CoefOut_106 = CoefData_106;

  // CoefReg_108
  assign CoefData_107 = 32'sb00111011010001000110011100000000;

  assign CoefOut_107 = CoefData_107;

  // CoefReg_109
  assign CoefData_108 = 32'sb01010010001011101110100110000000;

  assign CoefOut_108 = CoefData_108;

  // CoefReg_110
  assign CoefData_109 = 32'sb01010101101110010010100101000000;

  assign CoefOut_109 = CoefData_109;

  // CoefReg_111
  assign CoefData_110 = 32'sb01000110010010001010010100000000;

  assign CoefOut_110 = CoefData_110;

  // CoefReg_112
  assign CoefData_111 = 32'sb00101000011111010100000000000000;

  assign CoefOut_111 = CoefData_111;

  // CoefReg_113
  assign CoefData_112 = 32'sb00000011111000000101100100000000;

  assign CoefOut_112 = CoefData_112;

  // CoefReg_114
  assign CoefData_113 = 32'sb11100001000000010010101110000000;

  assign CoefOut_113 = CoefData_113;

  // CoefReg_115
  assign CoefData_114 = 32'sb11000111011100101101001100000000;

  assign CoefOut_114 = CoefData_114;

  // CoefReg_116
  assign CoefData_115 = 32'sb10111100001010000001101101000000;

  assign CoefOut_115 = CoefData_115;

  // CoefReg_117
  assign CoefData_116 = 32'sb11000000100001010111111100000000;

  assign CoefOut_116 = CoefData_116;

  // CoefReg_118
  assign CoefData_117 = 32'sb11010010010101010111110101000000;

  assign CoefOut_117 = CoefData_117;

  // CoefReg_119
  assign CoefData_118 = 32'sb11101100100011111000001100000000;

  assign CoefOut_118 = CoefData_118;

  // CoefReg_120
  assign CoefData_119 = 32'sb00001000101101011111010100000000;

  assign CoefOut_119 = CoefData_119;

  // CoefReg_121
  assign CoefData_120 = 32'sb00100000011011000000111001000000;

  assign CoefOut_120 = CoefData_120;

  // CoefReg_122
  assign CoefData_121 = 32'sb00101110111000110010011111000000;

  assign CoefOut_121 = CoefData_121;

  // CoefReg_123
  assign CoefData_122 = 32'sb00110001110011001100100100000000;

  assign CoefOut_122 = CoefData_122;

  // CoefReg_124
  assign CoefData_123 = 32'sb00101001101001010010010101000000;

  assign CoefOut_123 = CoefData_123;

  // CoefReg_125
  assign CoefData_124 = 32'sb00011001010100110111111100000000;

  assign CoefOut_124 = CoefData_124;

  // CoefReg_126
  assign CoefData_125 = 32'sb00000101010001100000111111000000;

  assign CoefOut_125 = CoefData_125;

  // CoefReg_127
  assign CoefData_126 = 32'sb11110010010010011110111011000000;

  assign CoefOut_126 = CoefData_126;

  // CoefReg_128
  assign CoefData_127 = 32'sb11100100011010101110111101000000;

  assign CoefOut_127 = CoefData_127;

  // CoefReg_129
  assign CoefData_128 = 32'sb11011110000111100000001111000000;

  assign CoefOut_128 = CoefData_128;

  // CoefReg_130
  assign CoefData_129 = 32'sb11011111111000000110101100000000;

  assign CoefOut_129 = CoefData_129;

  // CoefReg_131
  assign CoefData_130 = 32'sb11101000010101010101001011000000;

  assign CoefOut_130 = CoefData_130;

  // CoefReg_132
  assign CoefData_131 = 32'sb11110100110010111010010001000000;

  assign CoefOut_131 = CoefData_131;

  // CoefReg_133
  assign CoefData_132 = 32'sb00000010000000101100101100000000;

  assign CoefOut_132 = CoefData_132;

  // CoefReg_134
  assign CoefData_133 = 32'sb00001100111110101110010101000000;

  assign CoefOut_133 = CoefData_133;

  // CoefReg_135
  assign CoefData_134 = 32'sb00010011100111000111111010000000;

  assign CoefOut_134 = CoefData_134;

  // CoefReg_136
  assign CoefData_135 = 32'sb00010101000011111111000001000000;

  assign CoefOut_135 = CoefData_135;

  // CoefReg_137
  assign CoefData_136 = 32'sb00010001110001001111111110000000;

  assign CoefOut_136 = CoefData_136;

  // CoefReg_138
  assign CoefData_137 = 32'sb00001011001011101011101100000000;

  assign CoefOut_137 = CoefData_137;

  // CoefReg_139
  assign CoefData_138 = 32'sb00000011010000010010001111000000;

  assign CoefOut_138 = CoefData_138;

  // CoefReg_140
  assign CoefData_139 = 32'sb11111011111101000100000110000000;

  assign CoefOut_139 = CoefData_139;

  // CoefReg_141
  assign CoefData_140 = 32'sb11110110110001111110111100000000;

  assign CoefOut_140 = CoefData_140;

  // CoefReg_142
  assign CoefData_141 = 32'sb11110100100000110010111000000000;

  assign CoefOut_141 = CoefData_141;

  // CoefReg_143
  assign CoefData_142 = 32'sb11110101001000010011111111000000;

  assign CoefOut_142 = CoefData_142;

  // CoefReg_144
  assign CoefData_143 = 32'sb11110111111101101011101010000000;

  assign CoefOut_143 = CoefData_143;

  // CoefReg_145
  assign CoefData_144 = 32'sb11111011111101010011001011000000;

  assign CoefOut_144 = CoefData_144;

  // CoefReg_146
  assign CoefData_145 = 32'sb11111111111111011011010001000000;

  assign CoefOut_145 = CoefData_145;

  // CoefReg_147
  assign CoefData_146 = 32'sb00000011001001101010111000000000;

  assign CoefOut_146 = CoefData_146;

  // CoefReg_148
  assign CoefData_147 = 32'sb00000100111010100101001001000000;

  assign CoefOut_147 = CoefData_147;

  // CoefReg_149
  assign CoefData_148 = 32'sb00000101001100100001111001000000;

  assign CoefOut_148 = CoefData_148;

  // CoefReg_150
  assign CoefData_149 = 32'sb00000100010001100101101010000000;

  assign CoefOut_149 = CoefData_149;

  // CoefReg_151
  assign CoefData_150 = 32'sb00000010101001111100100101000000;

  assign CoefOut_150 = CoefData_150;

  // CoefReg_152
  assign CoefData_151 = 32'sb00000000111000111111011011000000;

  assign CoefOut_151 = CoefData_151;

  // CoefReg_153
  assign CoefData_152 = 32'sb11111111011011100011000111000000;

  assign CoefOut_152 = CoefData_152;

  // CoefReg_154
  assign CoefData_153 = 32'sb11111110100010001101001110000000;

  assign CoefOut_153 = CoefData_153;

  // CoefReg_155
  assign CoefData_154 = 32'sb11111110001111110110011011000000;

  assign CoefOut_154 = CoefData_154;

  // CoefReg_156
  assign CoefData_155 = 32'sb11111110011100011110100100000000;

  assign CoefOut_155 = CoefData_155;

  // CoefReg_157
  assign CoefData_156 = 32'sb11111110111010000011001001000000;

  assign CoefOut_156 = CoefData_156;

  // CoefReg_158
  assign CoefData_157 = 32'sb11111111011010000100011101000000;

  assign CoefOut_157 = CoefData_157;

  // CoefReg_159
  assign CoefData_158 = 32'sb11111111110001100110100110000000;

  assign CoefOut_158 = CoefData_158;

  // CoefReg_160
  assign CoefData_159 = 32'sb11111111111011010100011110000000;

  assign CoefOut_159 = CoefData_159;

  // CoefReg_161
  assign CoefData_160 = 32'sb11111111110110110001110000000000;

  assign CoefOut_160 = CoefData_160;

  // CoefReg_162
  assign CoefData_161 = 32'sb11111111100110010110110100000000;

  assign CoefOut_161 = CoefData_161;

  // CoefReg_163
  assign CoefData_162 = 32'sb11111111001100010000110111000000;

  assign CoefOut_162 = CoefData_162;

  // CoefReg_164
  assign CoefData_163 = 32'sb11111110101000010010011110000000;

  assign CoefOut_163 = CoefData_163;

  // CoefReg_165
  assign CoefData_164 = 32'sb11111101110110100000010110000000;

  assign CoefOut_164 = CoefData_164;

  // CoefReg_166
  assign CoefData_165 = 32'sb00000010100101011011101001000000;

  assign CoefOut_165 = CoefData_165;

endmodule  // FilterCoef

