// -------------------------------------------------------------
// 
// File Name: /MATLAB Drive/codegen/fm_filter/hdlsrc/Filter.v
// Created: 2025-12-07 22:11:16
// 
// Generated by MATLAB 25.2, MATLAB Coder 25.2 and HDL Coder 25.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter
// Source Path: fm_filter/dsphdl.FIRFilter/Filter
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] dataIn;  // sfix16_En15
  input   validIn;
  input   syncReset;
  output  signed [46:0] dataOut;  // sfix47_En45
  output  validOut;


  reg  dinRegVld;
  reg signed [15:0] dinReg_0_re;  // sfix16_En15
  reg signed [15:0] dinReg2_0_re;  // sfix16_En15
  wire signed [32:0] CoefOut_0;  // sfix33_En30
  wire signed [32:0] CoefOut_1;  // sfix33_En30
  wire signed [32:0] CoefOut_2;  // sfix33_En30
  wire signed [32:0] CoefOut_3;  // sfix33_En30
  wire signed [32:0] CoefOut_4;  // sfix33_En30
  wire signed [32:0] CoefOut_5;  // sfix33_En30
  wire signed [32:0] CoefOut_6;  // sfix33_En30
  wire signed [32:0] CoefOut_7;  // sfix33_En30
  wire signed [32:0] CoefOut_8;  // sfix33_En30
  wire signed [32:0] CoefOut_9;  // sfix33_En30
  wire signed [32:0] CoefOut_10;  // sfix33_En30
  wire signed [32:0] CoefOut_11;  // sfix33_En30
  wire signed [32:0] CoefOut_12;  // sfix33_En30
  wire signed [32:0] CoefOut_13;  // sfix33_En30
  wire signed [32:0] CoefOut_14;  // sfix33_En30
  wire signed [32:0] CoefOut_15;  // sfix33_En30
  wire signed [32:0] CoefOut_16;  // sfix33_En30
  wire signed [32:0] CoefOut_17;  // sfix33_En30
  wire signed [32:0] CoefOut_18;  // sfix33_En30
  wire signed [32:0] CoefOut_19;  // sfix33_En30
  wire signed [32:0] CoefOut_20;  // sfix33_En30
  wire signed [32:0] CoefOut_21;  // sfix33_En30
  wire signed [32:0] CoefOut_22;  // sfix33_En30
  wire signed [32:0] CoefOut_23;  // sfix33_En30
  wire signed [32:0] CoefOut_24;  // sfix33_En30
  wire signed [32:0] CoefOut_25;  // sfix33_En30
  wire signed [32:0] CoefOut_26;  // sfix33_En30
  wire signed [32:0] CoefOut_27;  // sfix33_En30
  wire signed [32:0] CoefOut_28;  // sfix33_En30
  wire signed [32:0] CoefOut_29;  // sfix33_En30
  wire signed [32:0] CoefOut_30;  // sfix33_En30
  wire signed [32:0] CoefOut_31;  // sfix33_En30
  wire signed [32:0] CoefOut_32;  // sfix33_En30
  wire signed [32:0] CoefOut_33;  // sfix33_En30
  wire signed [32:0] CoefOut_34;  // sfix33_En30
  wire signed [32:0] CoefOut_35;  // sfix33_En30
  wire signed [32:0] CoefOut_36;  // sfix33_En30
  wire signed [32:0] CoefOut_37;  // sfix33_En30
  wire signed [32:0] CoefOut_38;  // sfix33_En30
  wire signed [32:0] CoefOut_39;  // sfix33_En30
  wire signed [32:0] CoefOut_40;  // sfix33_En30
  wire signed [32:0] CoefOut_41;  // sfix33_En30
  wire signed [32:0] CoefOut_42;  // sfix33_En30
  wire signed [32:0] CoefOut_43;  // sfix33_En30
  wire signed [32:0] CoefOut_44;  // sfix33_En30
  wire signed [32:0] CoefOut_45;  // sfix33_En30
  wire signed [32:0] CoefOut_46;  // sfix33_En30
  wire signed [32:0] CoefOut_47;  // sfix33_En30
  wire signed [32:0] CoefOut_48;  // sfix33_En30
  wire signed [32:0] CoefOut_49;  // sfix33_En30
  wire signed [32:0] CoefOut_50;  // sfix33_En30
  wire signed [32:0] CoefOut_51;  // sfix33_En30
  wire signed [32:0] CoefOut_52;  // sfix33_En30
  wire signed [32:0] CoefOut_53;  // sfix33_En30
  wire signed [32:0] CoefOut_54;  // sfix33_En30
  wire signed [32:0] CoefOut_55;  // sfix33_En30
  wire signed [32:0] CoefOut_56;  // sfix33_En30
  wire signed [32:0] CoefOut_57;  // sfix33_En30
  wire signed [32:0] CoefOut_58;  // sfix33_En30
  wire signed [32:0] CoefOut_59;  // sfix33_En30
  wire signed [32:0] CoefOut_60;  // sfix33_En30
  wire signed [32:0] CoefOut_61;  // sfix33_En30
  wire signed [32:0] CoefOut_62;  // sfix33_En30
  wire signed [32:0] CoefOut_63;  // sfix33_En30
  wire signed [32:0] CoefOut_64;  // sfix33_En30
  wire signed [32:0] CoefOut_65;  // sfix33_En30
  wire signed [32:0] CoefOut_66;  // sfix33_En30
  wire signed [32:0] CoefOut_67;  // sfix33_En30
  wire signed [32:0] CoefOut_68;  // sfix33_En30
  wire signed [32:0] CoefOut_69;  // sfix33_En30
  wire signed [32:0] CoefOut_70;  // sfix33_En30
  wire signed [32:0] CoefOut_71;  // sfix33_En30
  wire signed [32:0] CoefOut_72;  // sfix33_En30
  wire signed [32:0] CoefOut_73;  // sfix33_En30
  wire signed [32:0] CoefOut_74;  // sfix33_En30
  wire signed [32:0] CoefOut_75;  // sfix33_En30
  wire signed [32:0] CoefOut_76;  // sfix33_En30
  wire signed [32:0] CoefOut_77;  // sfix33_En30
  wire signed [32:0] CoefOut_78;  // sfix33_En30
  wire signed [32:0] CoefOut_79;  // sfix33_En30
  wire signed [32:0] CoefOut_80;  // sfix33_En30
  wire signed [32:0] CoefOut_81;  // sfix33_En30
  wire signed [32:0] CoefOut_82;  // sfix33_En30
  wire signed [32:0] CoefOut_83;  // sfix33_En30
  wire signed [32:0] CoefOut_84;  // sfix33_En30
  wire signed [32:0] CoefOut_85;  // sfix33_En30
  wire signed [32:0] CoefOut_86;  // sfix33_En30
  wire signed [32:0] CoefOut_87;  // sfix33_En30
  wire signed [32:0] CoefOut_88;  // sfix33_En30
  wire signed [32:0] CoefOut_89;  // sfix33_En30
  wire signed [32:0] CoefOut_90;  // sfix33_En30
  wire signed [32:0] CoefOut_91;  // sfix33_En30
  wire signed [32:0] CoefOut_92;  // sfix33_En30
  wire signed [32:0] CoefOut_93;  // sfix33_En30
  wire signed [32:0] CoefOut_94;  // sfix33_En30
  wire signed [32:0] CoefOut_95;  // sfix33_En30
  wire signed [32:0] CoefOut_96;  // sfix33_En30
  wire signed [32:0] CoefOut_97;  // sfix33_En30
  wire signed [32:0] CoefOut_98;  // sfix33_En30
  wire signed [32:0] CoefOut_99;  // sfix33_En30
  wire signed [32:0] CoefOut_100;  // sfix33_En30
  wire signed [32:0] CoefOut_101;  // sfix33_En30
  wire signed [32:0] CoefOut_102;  // sfix33_En30
  wire signed [32:0] CoefOut_103;  // sfix33_En30
  wire signed [32:0] CoefOut_104;  // sfix33_En30
  wire signed [32:0] CoefOut_105;  // sfix33_En30
  wire signed [32:0] CoefOut_106;  // sfix33_En30
  wire signed [32:0] CoefOut_107;  // sfix33_En30
  wire signed [32:0] CoefOut_108;  // sfix33_En30
  wire signed [32:0] CoefOut_109;  // sfix33_En30
  wire signed [32:0] CoefOut_110;  // sfix33_En30
  wire signed [32:0] CoefOut_111;  // sfix33_En30
  wire signed [32:0] CoefOut_112;  // sfix33_En30
  wire signed [32:0] CoefOut_113;  // sfix33_En30
  wire signed [32:0] CoefOut_114;  // sfix33_En30
  wire signed [32:0] CoefOut_115;  // sfix33_En30
  wire signed [32:0] CoefOut_116;  // sfix33_En30
  wire signed [32:0] CoefOut_117;  // sfix33_En30
  wire signed [32:0] CoefOut_118;  // sfix33_En30
  wire signed [32:0] CoefOut_119;  // sfix33_En30
  wire signed [32:0] CoefOut_120;  // sfix33_En30
  wire signed [32:0] CoefOut_121;  // sfix33_En30
  wire signed [32:0] CoefOut_122;  // sfix33_En30
  wire signed [32:0] CoefOut_123;  // sfix33_En30
  wire signed [32:0] CoefOut_124;  // sfix33_En30
  wire signed [32:0] CoefOut_125;  // sfix33_En30
  wire signed [32:0] CoefOut_126;  // sfix33_En30
  wire signed [32:0] CoefOut_127;  // sfix33_En30
  wire signed [32:0] CoefOut_128;  // sfix33_En30
  wire signed [32:0] CoefOut_129;  // sfix33_En30
  wire signed [32:0] CoefOut_130;  // sfix33_En30
  wire signed [32:0] CoefOut_131;  // sfix33_En30
  wire signed [32:0] CoefOut_132;  // sfix33_En30
  wire signed [32:0] CoefOut_133;  // sfix33_En30
  wire signed [32:0] CoefOut_134;  // sfix33_En30
  wire signed [32:0] CoefOut_135;  // sfix33_En30
  wire signed [32:0] CoefOut_136;  // sfix33_En30
  wire signed [32:0] CoefOut_137;  // sfix33_En30
  wire signed [32:0] CoefOut_138;  // sfix33_En30
  wire signed [32:0] CoefOut_139;  // sfix33_En30
  wire signed [32:0] CoefOut_140;  // sfix33_En30
  wire signed [32:0] CoefOut_141;  // sfix33_En30
  wire signed [32:0] CoefOut_142;  // sfix33_En30
  wire signed [32:0] CoefOut_143;  // sfix33_En30
  wire signed [32:0] CoefOut_144;  // sfix33_En30
  wire signed [32:0] CoefOut_145;  // sfix33_En30
  wire signed [32:0] CoefOut_146;  // sfix33_En30
  wire signed [32:0] CoefOut_147;  // sfix33_En30
  wire signed [32:0] CoefOut_148;  // sfix33_En30
  wire signed [32:0] CoefOut_149;  // sfix33_En30
  wire signed [32:0] CoefOut_150;  // sfix33_En30
  wire signed [32:0] CoefOut_151;  // sfix33_En30
  wire signed [32:0] CoefOut_152;  // sfix33_En30
  wire signed [32:0] CoefOut_153;  // sfix33_En30
  wire signed [32:0] CoefOut_154;  // sfix33_En30
  wire signed [32:0] CoefOut_155;  // sfix33_En30
  wire signed [32:0] CoefOut_156;  // sfix33_En30
  wire signed [32:0] CoefOut_157;  // sfix33_En30
  wire signed [32:0] CoefOut_158;  // sfix33_En30
  wire signed [32:0] CoefOut_159;  // sfix33_En30
  wire signed [32:0] CoefOut_160;  // sfix33_En30
  wire signed [32:0] CoefOut_161;  // sfix33_En30
  wire signed [32:0] CoefOut_162;  // sfix33_En30
  wire signed [32:0] CoefOut_163;  // sfix33_En30
  wire signed [32:0] CoefOut_164;  // sfix33_En30
  wire signed [32:0] CoefOut_165;  // sfix33_En30
  wire signed [32:0] CoefOut_166;  // sfix33_En30
  wire signed [32:0] CoefOut_167;  // sfix33_En30
  wire signed [32:0] CoefOut_168;  // sfix33_En30
  wire signed [32:0] CoefOut_169;  // sfix33_En30
  wire signed [32:0] CoefOut_170;  // sfix33_En30
  wire signed [32:0] CoefOut_171;  // sfix33_En30
  wire signed [32:0] CoefOut_172;  // sfix33_En30
  wire signed [32:0] CoefOut_173;  // sfix33_En30
  wire signed [32:0] CoefOut_174;  // sfix33_En30
  wire signed [32:0] CoefOut_175;  // sfix33_En30
  wire signed [32:0] CoefOut_176;  // sfix33_En30
  wire signed [32:0] CoefOut_177;  // sfix33_En30
  wire signed [32:0] CoefOut_178;  // sfix33_En30
  wire signed [32:0] CoefOut_179;  // sfix33_En30
  wire signed [32:0] CoefOut_180;  // sfix33_En30
  wire signed [32:0] CoefOut_181;  // sfix33_En30
  wire signed [32:0] CoefOut_182;  // sfix33_En30
  wire signed [32:0] CoefOut_183;  // sfix33_En30
  wire signed [32:0] CoefOut_184;  // sfix33_En30
  wire signed [32:0] CoefOut_185;  // sfix33_En30
  wire signed [32:0] CoefOut_186;  // sfix33_En30
  wire signed [32:0] CoefOut_187;  // sfix33_En30
  wire signed [32:0] CoefOut_188;  // sfix33_En30
  wire signed [32:0] CoefOut_189;  // sfix33_En30
  wire signed [32:0] CoefOut_190;  // sfix33_En30
  wire signed [32:0] CoefOut_191;  // sfix33_En30
  wire signed [32:0] CoefOut_192;  // sfix33_En30
  wire signed [32:0] CoefOut_193;  // sfix33_En30
  wire signed [32:0] CoefOut_194;  // sfix33_En30
  wire signed [32:0] CoefOut_195;  // sfix33_En30
  wire signed [32:0] CoefOut_196;  // sfix33_En30
  wire signed [32:0] CoefOut_197;  // sfix33_En30
  wire signed [32:0] CoefOut_198;  // sfix33_En30
  wire signed [32:0] CoefOut_199;  // sfix33_En30
  wire signed [32:0] CoefOut_200;  // sfix33_En30
  wire signed [32:0] CoefOut_201;  // sfix33_En30
  wire signed [32:0] CoefOut_202;  // sfix33_En30
  wire signed [32:0] CoefOut_203;  // sfix33_En30
  wire signed [32:0] CoefOut_204;  // sfix33_En30
  wire signed [32:0] CoefOut_205;  // sfix33_En30
  wire signed [32:0] CoefOut_206;  // sfix33_En30
  wire signed [32:0] CoefOut_207;  // sfix33_En30
  wire signed [32:0] CoefOut_208;  // sfix33_En30
  wire signed [32:0] CoefOut_209;  // sfix33_En30
  wire signed [32:0] CoefOut_210;  // sfix33_En30
  wire signed [32:0] CoefOut_211;  // sfix33_En30
  wire signed [32:0] CoefOut_212;  // sfix33_En30
  wire signed [32:0] CoefOut_213;  // sfix33_En30
  wire signed [32:0] CoefOut_214;  // sfix33_En30
  wire signed [32:0] CoefOut_215;  // sfix33_En30
  wire signed [32:0] CoefOut_216;  // sfix33_En30
  wire signed [32:0] CoefOut_217;  // sfix33_En30
  wire signed [32:0] CoefOut_218;  // sfix33_En30
  wire signed [32:0] CoefOut_219;  // sfix33_En30
  wire signed [32:0] CoefOut_220;  // sfix33_En30
  wire signed [32:0] CoefOut_221;  // sfix33_En30
  wire signed [32:0] CoefOut_222;  // sfix33_En30
  wire signed [32:0] CoefOut_223;  // sfix33_En30
  wire signed [32:0] CoefOut_224;  // sfix33_En30
  wire signed [32:0] CoefOut_225;  // sfix33_En30
  wire signed [32:0] CoefOut_226;  // sfix33_En30
  wire signed [32:0] CoefOut_227;  // sfix33_En30
  wire signed [32:0] CoefOut_228;  // sfix33_En30
  wire signed [32:0] CoefOut_229;  // sfix33_En30
  wire signed [32:0] CoefOut_230;  // sfix33_En30
  wire signed [32:0] CoefOut_231;  // sfix33_En30
  wire signed [32:0] CoefOut_232;  // sfix33_En30
  wire signed [32:0] CoefOut_233;  // sfix33_En30
  wire signed [32:0] CoefOut_234;  // sfix33_En30
  wire signed [32:0] CoefOut_235;  // sfix33_En30
  wire signed [32:0] CoefOut_236;  // sfix33_En30
  wire signed [32:0] CoefOut_237;  // sfix33_En30
  wire signed [32:0] CoefOut_238;  // sfix33_En30
  wire signed [32:0] CoefOut_239;  // sfix33_En30
  wire signed [32:0] CoefOut_240;  // sfix33_En30
  wire signed [32:0] CoefOut_241;  // sfix33_En30
  wire signed [32:0] CoefOut_242;  // sfix33_En30
  wire signed [32:0] CoefOut_243;  // sfix33_En30
  wire signed [32:0] CoefOut_244;  // sfix33_En30
  wire signed [32:0] CoefOut_245;  // sfix33_En30
  wire signed [32:0] CoefOut_246;  // sfix33_En30
  wire signed [32:0] CoefOut_247;  // sfix33_En30
  wire signed [32:0] CoefOut_248;  // sfix33_En30
  wire signed [32:0] CoefOut_249;  // sfix33_En30
  wire signed [32:0] CoefOut_250;  // sfix33_En30
  wire signed [32:0] CoefOut_251;  // sfix33_En30
  wire signed [32:0] CoefOut_252;  // sfix33_En30
  wire signed [32:0] CoefOut_253;  // sfix33_En30
  wire signed [32:0] CoefOut_254;  // sfix33_En30
  wire signed [32:0] CoefOut_255;  // sfix33_En30
  wire signed [32:0] CoefOut_256;  // sfix33_En30
  wire signed [32:0] CoefOut_257;  // sfix33_En30
  wire signed [32:0] CoefOut_258;  // sfix33_En30
  wire signed [32:0] CoefOut_259;  // sfix33_En30
  wire signed [32:0] CoefOut_260;  // sfix33_En30
  wire signed [32:0] CoefOut_261;  // sfix33_En30
  wire signed [32:0] CoefOut_262;  // sfix33_En30
  wire signed [32:0] CoefOut_263;  // sfix33_En30
  wire signed [32:0] CoefOut_264;  // sfix33_En30
  wire signed [32:0] CoefOut_265;  // sfix33_En30
  wire signed [32:0] CoefOut_266;  // sfix33_En30
  wire signed [32:0] CoefOut_267;  // sfix33_En30
  wire signed [32:0] CoefOut_268;  // sfix33_En30
  wire signed [32:0] CoefOut_269;  // sfix33_En30
  wire signed [32:0] CoefOut_270;  // sfix33_En30
  wire signed [32:0] CoefOut_271;  // sfix33_En30
  wire signed [32:0] CoefOut_272;  // sfix33_En30
  wire signed [32:0] CoefOut_273;  // sfix33_En30
  wire signed [32:0] CoefOut_274;  // sfix33_En30
  wire signed [32:0] CoefOut_275;  // sfix33_En30
  wire signed [32:0] CoefOut_276;  // sfix33_En30
  wire signed [32:0] CoefOut_277;  // sfix33_En30
  wire signed [32:0] CoefOut_278;  // sfix33_En30
  wire signed [32:0] CoefOut_279;  // sfix33_En30
  wire signed [32:0] CoefOut_280;  // sfix33_En30
  wire signed [32:0] CoefOut_281;  // sfix33_En30
  wire signed [32:0] CoefOut_282;  // sfix33_En30
  wire signed [32:0] CoefOut_283;  // sfix33_En30
  wire signed [32:0] CoefOut_284;  // sfix33_En30
  wire signed [32:0] CoefOut_285;  // sfix33_En30
  wire signed [32:0] CoefOut_286;  // sfix33_En30
  wire signed [32:0] CoefOut_287;  // sfix33_En30
  wire signed [32:0] CoefOut_288;  // sfix33_En30
  wire signed [32:0] CoefOut_289;  // sfix33_En30
  wire signed [32:0] CoefOut_290;  // sfix33_En30
  wire signed [32:0] CoefOut_291;  // sfix33_En30
  wire signed [32:0] CoefOut_292;  // sfix33_En30
  wire signed [32:0] CoefOut_293;  // sfix33_En30
  wire signed [32:0] CoefOut_294;  // sfix33_En30
  wire signed [32:0] CoefOut_295;  // sfix33_En30
  wire signed [32:0] CoefOut_296;  // sfix33_En30
  wire signed [32:0] CoefOut_297;  // sfix33_En30
  wire signed [32:0] CoefOut_298;  // sfix33_En30
  wire signed [32:0] CoefOut_299;  // sfix33_En30
  wire signed [32:0] CoefOut_300;  // sfix33_En30
  wire signed [32:0] CoefOut_301;  // sfix33_En30
  wire signed [32:0] CoefOut_302;  // sfix33_En30
  wire signed [32:0] CoefOut_303;  // sfix33_En30
  wire signed [32:0] CoefOut_304;  // sfix33_En30
  wire signed [32:0] CoefOut_305;  // sfix33_En30
  wire signed [32:0] CoefOut_306;  // sfix33_En30
  wire signed [32:0] CoefOut_307;  // sfix33_En30
  wire signed [32:0] CoefOut_308;  // sfix33_En30
  wire signed [32:0] CoefOut_309;  // sfix33_En30
  wire signed [32:0] CoefOut_310;  // sfix33_En30
  wire signed [32:0] CoefOut_311;  // sfix33_En30
  wire signed [32:0] CoefOut_312;  // sfix33_En30
  wire signed [32:0] CoefOut_313;  // sfix33_En30
  wire signed [32:0] CoefOut_314;  // sfix33_En30
  wire signed [32:0] CoefOut_315;  // sfix33_En30
  wire signed [32:0] CoefOut_316;  // sfix33_En30
  wire signed [32:0] CoefOut_317;  // sfix33_En30
  wire signed [32:0] CoefOut_318;  // sfix33_En30
  wire signed [32:0] CoefOut_319;  // sfix33_En30
  wire signed [32:0] CoefOut_320;  // sfix33_En30
  wire signed [32:0] CoefOut_321;  // sfix33_En30
  wire signed [32:0] CoefOut_322;  // sfix33_En30
  wire signed [32:0] CoefOut_323;  // sfix33_En30
  wire signed [32:0] CoefOut_324;  // sfix33_En30
  wire signed [32:0] CoefOut_325;  // sfix33_En30
  wire signed [32:0] CoefOut_326;  // sfix33_En30
  wire signed [32:0] CoefOut_327;  // sfix33_En30
  wire signed [32:0] CoefOut_328;  // sfix33_En30
  wire signed [32:0] CoefOut_329;  // sfix33_En30
  wire signed [32:0] CoefOut_330;  // sfix33_En30
  wire signed [32:0] CoefOut_331;  // sfix33_En30
  wire signed [32:0] CoefOut_332;  // sfix33_En30
  wire signed [32:0] CoefOut_333;  // sfix33_En30
  wire signed [32:0] CoefOut_334;  // sfix33_En30
  wire signed [32:0] CoefOut_335;  // sfix33_En30
  wire signed [32:0] CoefOut_336;  // sfix33_En30
  wire signed [32:0] CoefOut_337;  // sfix33_En30
  wire signed [32:0] CoefOut_338;  // sfix33_En30
  wire signed [32:0] CoefOut_339;  // sfix33_En30
  wire signed [32:0] CoefOut_340;  // sfix33_En30
  wire signed [32:0] CoefOut_341;  // sfix33_En30
  wire signed [32:0] CoefOut_342;  // sfix33_En30
  wire signed [32:0] CoefOut_343;  // sfix33_En30
  wire signed [32:0] CoefOut_344;  // sfix33_En30
  wire signed [32:0] CoefOut_345;  // sfix33_En30
  wire signed [32:0] CoefOut_346;  // sfix33_En30
  wire signed [32:0] CoefOut_347;  // sfix33_En30
  wire signed [32:0] CoefOut_348;  // sfix33_En30
  wire signed [32:0] CoefOut_349;  // sfix33_En30
  wire signed [32:0] CoefOut_350;  // sfix33_En30
  wire signed [32:0] CoefOut_351;  // sfix33_En30
  wire signed [32:0] CoefOut_352;  // sfix33_En30
  wire signed [32:0] CoefOut_353;  // sfix33_En30
  wire signed [32:0] CoefOut_354;  // sfix33_En30
  wire signed [32:0] CoefOut_355;  // sfix33_En30
  wire signed [32:0] CoefOut_356;  // sfix33_En30
  wire signed [32:0] CoefOut_357;  // sfix33_En30
  wire signed [32:0] CoefOut_358;  // sfix33_En30
  wire signed [32:0] CoefOut_359;  // sfix33_En30
  wire signed [32:0] CoefOut_360;  // sfix33_En30
  wire signed [32:0] CoefOut_361;  // sfix33_En30
  wire signed [32:0] CoefOut_362;  // sfix33_En30
  wire signed [32:0] CoefOut_363;  // sfix33_En30
  wire signed [32:0] CoefOut_364;  // sfix33_En30
  wire signed [32:0] CoefOut_365;  // sfix33_En30
  wire signed [32:0] CoefOut_366;  // sfix33_En30
  wire signed [32:0] CoefOut_367;  // sfix33_En30
  wire signed [32:0] CoefOut_368;  // sfix33_En30
  wire signed [32:0] CoefOut_369;  // sfix33_En30
  wire signed [32:0] CoefOut_370;  // sfix33_En30
  wire signed [32:0] CoefOut_371;  // sfix33_En30
  wire signed [32:0] CoefOut_372;  // sfix33_En30
  wire signed [32:0] CoefOut_373;  // sfix33_En30
  wire signed [32:0] CoefOut_374;  // sfix33_En30
  wire signed [32:0] CoefOut_375;  // sfix33_En30
  wire signed [32:0] CoefOut_376;  // sfix33_En30
  wire signed [32:0] CoefOut_377;  // sfix33_En30
  wire signed [32:0] CoefOut_378;  // sfix33_En30
  wire signed [32:0] CoefOut_379;  // sfix33_En30
  wire signed [32:0] CoefOut_380;  // sfix33_En30
  wire signed [32:0] CoefOut_381;  // sfix33_En30
  wire signed [32:0] CoefOut_382;  // sfix33_En30
  wire signed [32:0] CoefOut_383;  // sfix33_En30
  wire signed [32:0] CoefOut_384;  // sfix33_En30
  wire signed [32:0] CoefOut_385;  // sfix33_En30
  wire signed [32:0] CoefOut_386;  // sfix33_En30
  wire signed [32:0] CoefOut_387;  // sfix33_En30
  wire signed [32:0] CoefOut_388;  // sfix33_En30
  wire signed [32:0] CoefOut_389;  // sfix33_En30
  wire signed [32:0] CoefOut_390;  // sfix33_En30
  wire signed [32:0] CoefOut_391;  // sfix33_En30
  wire signed [32:0] CoefOut_392;  // sfix33_En30
  wire signed [32:0] CoefOut_393;  // sfix33_En30
  wire signed [32:0] CoefOut_394;  // sfix33_En30
  wire signed [32:0] CoefOut_395;  // sfix33_En30
  wire signed [32:0] CoefOut_396;  // sfix33_En30
  wire signed [32:0] CoefOut_397;  // sfix33_En30
  wire signed [32:0] CoefOut_398;  // sfix33_En30
  wire signed [32:0] CoefOut_399;  // sfix33_En30
  wire signed [32:0] CoefOut_400;  // sfix33_En30
  wire signed [32:0] CoefOut_401;  // sfix33_En30
  wire signed [32:0] CoefOut_402;  // sfix33_En30
  wire signed [32:0] CoefOut_403;  // sfix33_En30
  wire signed [32:0] CoefOut_404;  // sfix33_En30
  wire signed [32:0] CoefOut_405;  // sfix33_En30
  wire signed [32:0] CoefOut_406;  // sfix33_En30
  wire signed [32:0] CoefOut_407;  // sfix33_En30
  wire signed [32:0] CoefOut_408;  // sfix33_En30
  wire signed [32:0] CoefOut_409;  // sfix33_En30
  wire signed [32:0] CoefOut_410;  // sfix33_En30
  wire signed [32:0] CoefOut_411;  // sfix33_En30
  wire signed [32:0] CoefOut_412;  // sfix33_En30
  wire signed [32:0] CoefOut_413;  // sfix33_En30
  wire signed [32:0] CoefOut_414;  // sfix33_En30
  wire signed [32:0] CoefOut_415;  // sfix33_En30
  wire signed [32:0] CoefOut_416;  // sfix33_En30
  wire signed [32:0] CoefOut_417;  // sfix33_En30
  wire signed [32:0] CoefOut_418;  // sfix33_En30
  wire signed [32:0] CoefOut_419;  // sfix33_En30
  wire signed [32:0] CoefOut_420;  // sfix33_En30
  wire signed [32:0] CoefOut_421;  // sfix33_En30
  wire signed [32:0] CoefOut_422;  // sfix33_En30
  wire signed [32:0] CoefOut_423;  // sfix33_En30
  wire signed [32:0] CoefOut_424;  // sfix33_En30
  wire signed [32:0] CoefOut_425;  // sfix33_En30
  wire signed [32:0] CoefOut_426;  // sfix33_En30
  wire signed [32:0] CoefOut_427;  // sfix33_En30
  wire signed [32:0] CoefOut_428;  // sfix33_En30
  wire signed [32:0] CoefOut_429;  // sfix33_En30
  wire signed [32:0] CoefOut_430;  // sfix33_En30
  wire signed [32:0] CoefOut_431;  // sfix33_En30
  wire signed [32:0] CoefOut_432;  // sfix33_En30
  wire signed [32:0] CoefOut_433;  // sfix33_En30
  wire signed [32:0] CoefOut_434;  // sfix33_En30
  wire signed [32:0] CoefOut_435;  // sfix33_En30
  wire signed [32:0] CoefOut_436;  // sfix33_En30
  wire signed [32:0] CoefOut_437;  // sfix33_En30
  wire signed [32:0] CoefOut_438;  // sfix33_En30
  wire signed [32:0] CoefOut_439;  // sfix33_En30
  wire signed [32:0] CoefOut_440;  // sfix33_En30
  wire signed [32:0] CoefOut_441;  // sfix33_En30
  wire signed [32:0] CoefOut_442;  // sfix33_En30
  wire signed [32:0] CoefOut_443;  // sfix33_En30
  wire signed [32:0] CoefOut_444;  // sfix33_En30
  wire signed [32:0] CoefOut_445;  // sfix33_En30
  wire signed [32:0] CoefOut_446;  // sfix33_En30
  wire signed [32:0] CoefOut_447;  // sfix33_En30
  wire signed [32:0] CoefOut_448;  // sfix33_En30
  wire signed [32:0] CoefOut_449;  // sfix33_En30
  wire signed [32:0] CoefOut_450;  // sfix33_En30
  wire signed [32:0] CoefOut_451;  // sfix33_En30
  wire signed [32:0] CoefOut_452;  // sfix33_En30
  wire signed [32:0] CoefOut_453;  // sfix33_En30
  wire signed [32:0] CoefOut_454;  // sfix33_En30
  wire signed [32:0] CoefOut_455;  // sfix33_En30
  wire signed [32:0] CoefOut_456;  // sfix33_En30
  wire signed [32:0] CoefOut_457;  // sfix33_En30
  wire signed [32:0] CoefOut_458;  // sfix33_En30
  wire signed [32:0] CoefOut_459;  // sfix33_En30
  wire signed [32:0] CoefOut_460;  // sfix33_En30
  wire signed [32:0] CoefOut_461;  // sfix33_En30
  wire signed [32:0] CoefOut_462;  // sfix33_En30
  wire signed [32:0] CoefOut_463;  // sfix33_En30
  wire signed [32:0] CoefOut_464;  // sfix33_En30
  wire signed [32:0] CoefOut_465;  // sfix33_En30
  wire signed [32:0] CoefOut_466;  // sfix33_En30
  wire signed [32:0] CoefOut_467;  // sfix33_En30
  wire signed [32:0] CoefOut_468;  // sfix33_En30
  wire signed [32:0] CoefOut_469;  // sfix33_En30
  wire signed [32:0] CoefOut_470;  // sfix33_En30
  wire signed [32:0] CoefOut_471;  // sfix33_En30
  wire signed [32:0] CoefOut_472;  // sfix33_En30
  wire signed [32:0] CoefOut_473;  // sfix33_En30
  wire signed [32:0] CoefOut_474;  // sfix33_En30
  wire signed [32:0] CoefOut_475;  // sfix33_En30
  wire signed [32:0] CoefOut_476;  // sfix33_En30
  wire signed [32:0] CoefOut_477;  // sfix33_En30
  wire signed [32:0] CoefOut_478;  // sfix33_En30
  wire signed [32:0] CoefOut_479;  // sfix33_En30
  wire signed [32:0] CoefOut_480;  // sfix33_En30
  wire signed [32:0] CoefOut_481;  // sfix33_En30
  wire signed [32:0] CoefOut_482;  // sfix33_En30
  wire signed [32:0] CoefOut_483;  // sfix33_En30
  wire signed [32:0] CoefOut_484;  // sfix33_En30
  wire signed [32:0] CoefOut_485;  // sfix33_En30
  wire signed [32:0] CoefOut_486;  // sfix33_En30
  wire signed [32:0] CoefOut_487;  // sfix33_En30
  wire signed [32:0] CoefOut_488;  // sfix33_En30
  wire signed [32:0] CoefOut_489;  // sfix33_En30
  wire signed [32:0] CoefOut_490;  // sfix33_En30
  wire signed [32:0] CoefOut_491;  // sfix33_En30
  wire signed [32:0] CoefOut_492;  // sfix33_En30
  wire signed [32:0] CoefOut_493;  // sfix33_En30
  wire signed [32:0] CoefOut_494;  // sfix33_En30
  reg  dinReg2Vld;
  wire signed [46:0] dout_1_re;  // sfix47_En45
  wire doutVld;


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 16'sb0000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end

  FilterCoef u_CoefTable_1 (.validIn(validIn),
                            .syncReset(syncReset),
                            .CoefOut_0(CoefOut_0),  // sfix33_En30
                            .CoefOut_1(CoefOut_1),  // sfix33_En30
                            .CoefOut_2(CoefOut_2),  // sfix33_En30
                            .CoefOut_3(CoefOut_3),  // sfix33_En30
                            .CoefOut_4(CoefOut_4),  // sfix33_En30
                            .CoefOut_5(CoefOut_5),  // sfix33_En30
                            .CoefOut_6(CoefOut_6),  // sfix33_En30
                            .CoefOut_7(CoefOut_7),  // sfix33_En30
                            .CoefOut_8(CoefOut_8),  // sfix33_En30
                            .CoefOut_9(CoefOut_9),  // sfix33_En30
                            .CoefOut_10(CoefOut_10),  // sfix33_En30
                            .CoefOut_11(CoefOut_11),  // sfix33_En30
                            .CoefOut_12(CoefOut_12),  // sfix33_En30
                            .CoefOut_13(CoefOut_13),  // sfix33_En30
                            .CoefOut_14(CoefOut_14),  // sfix33_En30
                            .CoefOut_15(CoefOut_15),  // sfix33_En30
                            .CoefOut_16(CoefOut_16),  // sfix33_En30
                            .CoefOut_17(CoefOut_17),  // sfix33_En30
                            .CoefOut_18(CoefOut_18),  // sfix33_En30
                            .CoefOut_19(CoefOut_19),  // sfix33_En30
                            .CoefOut_20(CoefOut_20),  // sfix33_En30
                            .CoefOut_21(CoefOut_21),  // sfix33_En30
                            .CoefOut_22(CoefOut_22),  // sfix33_En30
                            .CoefOut_23(CoefOut_23),  // sfix33_En30
                            .CoefOut_24(CoefOut_24),  // sfix33_En30
                            .CoefOut_25(CoefOut_25),  // sfix33_En30
                            .CoefOut_26(CoefOut_26),  // sfix33_En30
                            .CoefOut_27(CoefOut_27),  // sfix33_En30
                            .CoefOut_28(CoefOut_28),  // sfix33_En30
                            .CoefOut_29(CoefOut_29),  // sfix33_En30
                            .CoefOut_30(CoefOut_30),  // sfix33_En30
                            .CoefOut_31(CoefOut_31),  // sfix33_En30
                            .CoefOut_32(CoefOut_32),  // sfix33_En30
                            .CoefOut_33(CoefOut_33),  // sfix33_En30
                            .CoefOut_34(CoefOut_34),  // sfix33_En30
                            .CoefOut_35(CoefOut_35),  // sfix33_En30
                            .CoefOut_36(CoefOut_36),  // sfix33_En30
                            .CoefOut_37(CoefOut_37),  // sfix33_En30
                            .CoefOut_38(CoefOut_38),  // sfix33_En30
                            .CoefOut_39(CoefOut_39),  // sfix33_En30
                            .CoefOut_40(CoefOut_40),  // sfix33_En30
                            .CoefOut_41(CoefOut_41),  // sfix33_En30
                            .CoefOut_42(CoefOut_42),  // sfix33_En30
                            .CoefOut_43(CoefOut_43),  // sfix33_En30
                            .CoefOut_44(CoefOut_44),  // sfix33_En30
                            .CoefOut_45(CoefOut_45),  // sfix33_En30
                            .CoefOut_46(CoefOut_46),  // sfix33_En30
                            .CoefOut_47(CoefOut_47),  // sfix33_En30
                            .CoefOut_48(CoefOut_48),  // sfix33_En30
                            .CoefOut_49(CoefOut_49),  // sfix33_En30
                            .CoefOut_50(CoefOut_50),  // sfix33_En30
                            .CoefOut_51(CoefOut_51),  // sfix33_En30
                            .CoefOut_52(CoefOut_52),  // sfix33_En30
                            .CoefOut_53(CoefOut_53),  // sfix33_En30
                            .CoefOut_54(CoefOut_54),  // sfix33_En30
                            .CoefOut_55(CoefOut_55),  // sfix33_En30
                            .CoefOut_56(CoefOut_56),  // sfix33_En30
                            .CoefOut_57(CoefOut_57),  // sfix33_En30
                            .CoefOut_58(CoefOut_58),  // sfix33_En30
                            .CoefOut_59(CoefOut_59),  // sfix33_En30
                            .CoefOut_60(CoefOut_60),  // sfix33_En30
                            .CoefOut_61(CoefOut_61),  // sfix33_En30
                            .CoefOut_62(CoefOut_62),  // sfix33_En30
                            .CoefOut_63(CoefOut_63),  // sfix33_En30
                            .CoefOut_64(CoefOut_64),  // sfix33_En30
                            .CoefOut_65(CoefOut_65),  // sfix33_En30
                            .CoefOut_66(CoefOut_66),  // sfix33_En30
                            .CoefOut_67(CoefOut_67),  // sfix33_En30
                            .CoefOut_68(CoefOut_68),  // sfix33_En30
                            .CoefOut_69(CoefOut_69),  // sfix33_En30
                            .CoefOut_70(CoefOut_70),  // sfix33_En30
                            .CoefOut_71(CoefOut_71),  // sfix33_En30
                            .CoefOut_72(CoefOut_72),  // sfix33_En30
                            .CoefOut_73(CoefOut_73),  // sfix33_En30
                            .CoefOut_74(CoefOut_74),  // sfix33_En30
                            .CoefOut_75(CoefOut_75),  // sfix33_En30
                            .CoefOut_76(CoefOut_76),  // sfix33_En30
                            .CoefOut_77(CoefOut_77),  // sfix33_En30
                            .CoefOut_78(CoefOut_78),  // sfix33_En30
                            .CoefOut_79(CoefOut_79),  // sfix33_En30
                            .CoefOut_80(CoefOut_80),  // sfix33_En30
                            .CoefOut_81(CoefOut_81),  // sfix33_En30
                            .CoefOut_82(CoefOut_82),  // sfix33_En30
                            .CoefOut_83(CoefOut_83),  // sfix33_En30
                            .CoefOut_84(CoefOut_84),  // sfix33_En30
                            .CoefOut_85(CoefOut_85),  // sfix33_En30
                            .CoefOut_86(CoefOut_86),  // sfix33_En30
                            .CoefOut_87(CoefOut_87),  // sfix33_En30
                            .CoefOut_88(CoefOut_88),  // sfix33_En30
                            .CoefOut_89(CoefOut_89),  // sfix33_En30
                            .CoefOut_90(CoefOut_90),  // sfix33_En30
                            .CoefOut_91(CoefOut_91),  // sfix33_En30
                            .CoefOut_92(CoefOut_92),  // sfix33_En30
                            .CoefOut_93(CoefOut_93),  // sfix33_En30
                            .CoefOut_94(CoefOut_94),  // sfix33_En30
                            .CoefOut_95(CoefOut_95),  // sfix33_En30
                            .CoefOut_96(CoefOut_96),  // sfix33_En30
                            .CoefOut_97(CoefOut_97),  // sfix33_En30
                            .CoefOut_98(CoefOut_98),  // sfix33_En30
                            .CoefOut_99(CoefOut_99),  // sfix33_En30
                            .CoefOut_100(CoefOut_100),  // sfix33_En30
                            .CoefOut_101(CoefOut_101),  // sfix33_En30
                            .CoefOut_102(CoefOut_102),  // sfix33_En30
                            .CoefOut_103(CoefOut_103),  // sfix33_En30
                            .CoefOut_104(CoefOut_104),  // sfix33_En30
                            .CoefOut_105(CoefOut_105),  // sfix33_En30
                            .CoefOut_106(CoefOut_106),  // sfix33_En30
                            .CoefOut_107(CoefOut_107),  // sfix33_En30
                            .CoefOut_108(CoefOut_108),  // sfix33_En30
                            .CoefOut_109(CoefOut_109),  // sfix33_En30
                            .CoefOut_110(CoefOut_110),  // sfix33_En30
                            .CoefOut_111(CoefOut_111),  // sfix33_En30
                            .CoefOut_112(CoefOut_112),  // sfix33_En30
                            .CoefOut_113(CoefOut_113),  // sfix33_En30
                            .CoefOut_114(CoefOut_114),  // sfix33_En30
                            .CoefOut_115(CoefOut_115),  // sfix33_En30
                            .CoefOut_116(CoefOut_116),  // sfix33_En30
                            .CoefOut_117(CoefOut_117),  // sfix33_En30
                            .CoefOut_118(CoefOut_118),  // sfix33_En30
                            .CoefOut_119(CoefOut_119),  // sfix33_En30
                            .CoefOut_120(CoefOut_120),  // sfix33_En30
                            .CoefOut_121(CoefOut_121),  // sfix33_En30
                            .CoefOut_122(CoefOut_122),  // sfix33_En30
                            .CoefOut_123(CoefOut_123),  // sfix33_En30
                            .CoefOut_124(CoefOut_124),  // sfix33_En30
                            .CoefOut_125(CoefOut_125),  // sfix33_En30
                            .CoefOut_126(CoefOut_126),  // sfix33_En30
                            .CoefOut_127(CoefOut_127),  // sfix33_En30
                            .CoefOut_128(CoefOut_128),  // sfix33_En30
                            .CoefOut_129(CoefOut_129),  // sfix33_En30
                            .CoefOut_130(CoefOut_130),  // sfix33_En30
                            .CoefOut_131(CoefOut_131),  // sfix33_En30
                            .CoefOut_132(CoefOut_132),  // sfix33_En30
                            .CoefOut_133(CoefOut_133),  // sfix33_En30
                            .CoefOut_134(CoefOut_134),  // sfix33_En30
                            .CoefOut_135(CoefOut_135),  // sfix33_En30
                            .CoefOut_136(CoefOut_136),  // sfix33_En30
                            .CoefOut_137(CoefOut_137),  // sfix33_En30
                            .CoefOut_138(CoefOut_138),  // sfix33_En30
                            .CoefOut_139(CoefOut_139),  // sfix33_En30
                            .CoefOut_140(CoefOut_140),  // sfix33_En30
                            .CoefOut_141(CoefOut_141),  // sfix33_En30
                            .CoefOut_142(CoefOut_142),  // sfix33_En30
                            .CoefOut_143(CoefOut_143),  // sfix33_En30
                            .CoefOut_144(CoefOut_144),  // sfix33_En30
                            .CoefOut_145(CoefOut_145),  // sfix33_En30
                            .CoefOut_146(CoefOut_146),  // sfix33_En30
                            .CoefOut_147(CoefOut_147),  // sfix33_En30
                            .CoefOut_148(CoefOut_148),  // sfix33_En30
                            .CoefOut_149(CoefOut_149),  // sfix33_En30
                            .CoefOut_150(CoefOut_150),  // sfix33_En30
                            .CoefOut_151(CoefOut_151),  // sfix33_En30
                            .CoefOut_152(CoefOut_152),  // sfix33_En30
                            .CoefOut_153(CoefOut_153),  // sfix33_En30
                            .CoefOut_154(CoefOut_154),  // sfix33_En30
                            .CoefOut_155(CoefOut_155),  // sfix33_En30
                            .CoefOut_156(CoefOut_156),  // sfix33_En30
                            .CoefOut_157(CoefOut_157),  // sfix33_En30
                            .CoefOut_158(CoefOut_158),  // sfix33_En30
                            .CoefOut_159(CoefOut_159),  // sfix33_En30
                            .CoefOut_160(CoefOut_160),  // sfix33_En30
                            .CoefOut_161(CoefOut_161),  // sfix33_En30
                            .CoefOut_162(CoefOut_162),  // sfix33_En30
                            .CoefOut_163(CoefOut_163),  // sfix33_En30
                            .CoefOut_164(CoefOut_164),  // sfix33_En30
                            .CoefOut_165(CoefOut_165),  // sfix33_En30
                            .CoefOut_166(CoefOut_166),  // sfix33_En30
                            .CoefOut_167(CoefOut_167),  // sfix33_En30
                            .CoefOut_168(CoefOut_168),  // sfix33_En30
                            .CoefOut_169(CoefOut_169),  // sfix33_En30
                            .CoefOut_170(CoefOut_170),  // sfix33_En30
                            .CoefOut_171(CoefOut_171),  // sfix33_En30
                            .CoefOut_172(CoefOut_172),  // sfix33_En30
                            .CoefOut_173(CoefOut_173),  // sfix33_En30
                            .CoefOut_174(CoefOut_174),  // sfix33_En30
                            .CoefOut_175(CoefOut_175),  // sfix33_En30
                            .CoefOut_176(CoefOut_176),  // sfix33_En30
                            .CoefOut_177(CoefOut_177),  // sfix33_En30
                            .CoefOut_178(CoefOut_178),  // sfix33_En30
                            .CoefOut_179(CoefOut_179),  // sfix33_En30
                            .CoefOut_180(CoefOut_180),  // sfix33_En30
                            .CoefOut_181(CoefOut_181),  // sfix33_En30
                            .CoefOut_182(CoefOut_182),  // sfix33_En30
                            .CoefOut_183(CoefOut_183),  // sfix33_En30
                            .CoefOut_184(CoefOut_184),  // sfix33_En30
                            .CoefOut_185(CoefOut_185),  // sfix33_En30
                            .CoefOut_186(CoefOut_186),  // sfix33_En30
                            .CoefOut_187(CoefOut_187),  // sfix33_En30
                            .CoefOut_188(CoefOut_188),  // sfix33_En30
                            .CoefOut_189(CoefOut_189),  // sfix33_En30
                            .CoefOut_190(CoefOut_190),  // sfix33_En30
                            .CoefOut_191(CoefOut_191),  // sfix33_En30
                            .CoefOut_192(CoefOut_192),  // sfix33_En30
                            .CoefOut_193(CoefOut_193),  // sfix33_En30
                            .CoefOut_194(CoefOut_194),  // sfix33_En30
                            .CoefOut_195(CoefOut_195),  // sfix33_En30
                            .CoefOut_196(CoefOut_196),  // sfix33_En30
                            .CoefOut_197(CoefOut_197),  // sfix33_En30
                            .CoefOut_198(CoefOut_198),  // sfix33_En30
                            .CoefOut_199(CoefOut_199),  // sfix33_En30
                            .CoefOut_200(CoefOut_200),  // sfix33_En30
                            .CoefOut_201(CoefOut_201),  // sfix33_En30
                            .CoefOut_202(CoefOut_202),  // sfix33_En30
                            .CoefOut_203(CoefOut_203),  // sfix33_En30
                            .CoefOut_204(CoefOut_204),  // sfix33_En30
                            .CoefOut_205(CoefOut_205),  // sfix33_En30
                            .CoefOut_206(CoefOut_206),  // sfix33_En30
                            .CoefOut_207(CoefOut_207),  // sfix33_En30
                            .CoefOut_208(CoefOut_208),  // sfix33_En30
                            .CoefOut_209(CoefOut_209),  // sfix33_En30
                            .CoefOut_210(CoefOut_210),  // sfix33_En30
                            .CoefOut_211(CoefOut_211),  // sfix33_En30
                            .CoefOut_212(CoefOut_212),  // sfix33_En30
                            .CoefOut_213(CoefOut_213),  // sfix33_En30
                            .CoefOut_214(CoefOut_214),  // sfix33_En30
                            .CoefOut_215(CoefOut_215),  // sfix33_En30
                            .CoefOut_216(CoefOut_216),  // sfix33_En30
                            .CoefOut_217(CoefOut_217),  // sfix33_En30
                            .CoefOut_218(CoefOut_218),  // sfix33_En30
                            .CoefOut_219(CoefOut_219),  // sfix33_En30
                            .CoefOut_220(CoefOut_220),  // sfix33_En30
                            .CoefOut_221(CoefOut_221),  // sfix33_En30
                            .CoefOut_222(CoefOut_222),  // sfix33_En30
                            .CoefOut_223(CoefOut_223),  // sfix33_En30
                            .CoefOut_224(CoefOut_224),  // sfix33_En30
                            .CoefOut_225(CoefOut_225),  // sfix33_En30
                            .CoefOut_226(CoefOut_226),  // sfix33_En30
                            .CoefOut_227(CoefOut_227),  // sfix33_En30
                            .CoefOut_228(CoefOut_228),  // sfix33_En30
                            .CoefOut_229(CoefOut_229),  // sfix33_En30
                            .CoefOut_230(CoefOut_230),  // sfix33_En30
                            .CoefOut_231(CoefOut_231),  // sfix33_En30
                            .CoefOut_232(CoefOut_232),  // sfix33_En30
                            .CoefOut_233(CoefOut_233),  // sfix33_En30
                            .CoefOut_234(CoefOut_234),  // sfix33_En30
                            .CoefOut_235(CoefOut_235),  // sfix33_En30
                            .CoefOut_236(CoefOut_236),  // sfix33_En30
                            .CoefOut_237(CoefOut_237),  // sfix33_En30
                            .CoefOut_238(CoefOut_238),  // sfix33_En30
                            .CoefOut_239(CoefOut_239),  // sfix33_En30
                            .CoefOut_240(CoefOut_240),  // sfix33_En30
                            .CoefOut_241(CoefOut_241),  // sfix33_En30
                            .CoefOut_242(CoefOut_242),  // sfix33_En30
                            .CoefOut_243(CoefOut_243),  // sfix33_En30
                            .CoefOut_244(CoefOut_244),  // sfix33_En30
                            .CoefOut_245(CoefOut_245),  // sfix33_En30
                            .CoefOut_246(CoefOut_246),  // sfix33_En30
                            .CoefOut_247(CoefOut_247),  // sfix33_En30
                            .CoefOut_248(CoefOut_248),  // sfix33_En30
                            .CoefOut_249(CoefOut_249),  // sfix33_En30
                            .CoefOut_250(CoefOut_250),  // sfix33_En30
                            .CoefOut_251(CoefOut_251),  // sfix33_En30
                            .CoefOut_252(CoefOut_252),  // sfix33_En30
                            .CoefOut_253(CoefOut_253),  // sfix33_En30
                            .CoefOut_254(CoefOut_254),  // sfix33_En30
                            .CoefOut_255(CoefOut_255),  // sfix33_En30
                            .CoefOut_256(CoefOut_256),  // sfix33_En30
                            .CoefOut_257(CoefOut_257),  // sfix33_En30
                            .CoefOut_258(CoefOut_258),  // sfix33_En30
                            .CoefOut_259(CoefOut_259),  // sfix33_En30
                            .CoefOut_260(CoefOut_260),  // sfix33_En30
                            .CoefOut_261(CoefOut_261),  // sfix33_En30
                            .CoefOut_262(CoefOut_262),  // sfix33_En30
                            .CoefOut_263(CoefOut_263),  // sfix33_En30
                            .CoefOut_264(CoefOut_264),  // sfix33_En30
                            .CoefOut_265(CoefOut_265),  // sfix33_En30
                            .CoefOut_266(CoefOut_266),  // sfix33_En30
                            .CoefOut_267(CoefOut_267),  // sfix33_En30
                            .CoefOut_268(CoefOut_268),  // sfix33_En30
                            .CoefOut_269(CoefOut_269),  // sfix33_En30
                            .CoefOut_270(CoefOut_270),  // sfix33_En30
                            .CoefOut_271(CoefOut_271),  // sfix33_En30
                            .CoefOut_272(CoefOut_272),  // sfix33_En30
                            .CoefOut_273(CoefOut_273),  // sfix33_En30
                            .CoefOut_274(CoefOut_274),  // sfix33_En30
                            .CoefOut_275(CoefOut_275),  // sfix33_En30
                            .CoefOut_276(CoefOut_276),  // sfix33_En30
                            .CoefOut_277(CoefOut_277),  // sfix33_En30
                            .CoefOut_278(CoefOut_278),  // sfix33_En30
                            .CoefOut_279(CoefOut_279),  // sfix33_En30
                            .CoefOut_280(CoefOut_280),  // sfix33_En30
                            .CoefOut_281(CoefOut_281),  // sfix33_En30
                            .CoefOut_282(CoefOut_282),  // sfix33_En30
                            .CoefOut_283(CoefOut_283),  // sfix33_En30
                            .CoefOut_284(CoefOut_284),  // sfix33_En30
                            .CoefOut_285(CoefOut_285),  // sfix33_En30
                            .CoefOut_286(CoefOut_286),  // sfix33_En30
                            .CoefOut_287(CoefOut_287),  // sfix33_En30
                            .CoefOut_288(CoefOut_288),  // sfix33_En30
                            .CoefOut_289(CoefOut_289),  // sfix33_En30
                            .CoefOut_290(CoefOut_290),  // sfix33_En30
                            .CoefOut_291(CoefOut_291),  // sfix33_En30
                            .CoefOut_292(CoefOut_292),  // sfix33_En30
                            .CoefOut_293(CoefOut_293),  // sfix33_En30
                            .CoefOut_294(CoefOut_294),  // sfix33_En30
                            .CoefOut_295(CoefOut_295),  // sfix33_En30
                            .CoefOut_296(CoefOut_296),  // sfix33_En30
                            .CoefOut_297(CoefOut_297),  // sfix33_En30
                            .CoefOut_298(CoefOut_298),  // sfix33_En30
                            .CoefOut_299(CoefOut_299),  // sfix33_En30
                            .CoefOut_300(CoefOut_300),  // sfix33_En30
                            .CoefOut_301(CoefOut_301),  // sfix33_En30
                            .CoefOut_302(CoefOut_302),  // sfix33_En30
                            .CoefOut_303(CoefOut_303),  // sfix33_En30
                            .CoefOut_304(CoefOut_304),  // sfix33_En30
                            .CoefOut_305(CoefOut_305),  // sfix33_En30
                            .CoefOut_306(CoefOut_306),  // sfix33_En30
                            .CoefOut_307(CoefOut_307),  // sfix33_En30
                            .CoefOut_308(CoefOut_308),  // sfix33_En30
                            .CoefOut_309(CoefOut_309),  // sfix33_En30
                            .CoefOut_310(CoefOut_310),  // sfix33_En30
                            .CoefOut_311(CoefOut_311),  // sfix33_En30
                            .CoefOut_312(CoefOut_312),  // sfix33_En30
                            .CoefOut_313(CoefOut_313),  // sfix33_En30
                            .CoefOut_314(CoefOut_314),  // sfix33_En30
                            .CoefOut_315(CoefOut_315),  // sfix33_En30
                            .CoefOut_316(CoefOut_316),  // sfix33_En30
                            .CoefOut_317(CoefOut_317),  // sfix33_En30
                            .CoefOut_318(CoefOut_318),  // sfix33_En30
                            .CoefOut_319(CoefOut_319),  // sfix33_En30
                            .CoefOut_320(CoefOut_320),  // sfix33_En30
                            .CoefOut_321(CoefOut_321),  // sfix33_En30
                            .CoefOut_322(CoefOut_322),  // sfix33_En30
                            .CoefOut_323(CoefOut_323),  // sfix33_En30
                            .CoefOut_324(CoefOut_324),  // sfix33_En30
                            .CoefOut_325(CoefOut_325),  // sfix33_En30
                            .CoefOut_326(CoefOut_326),  // sfix33_En30
                            .CoefOut_327(CoefOut_327),  // sfix33_En30
                            .CoefOut_328(CoefOut_328),  // sfix33_En30
                            .CoefOut_329(CoefOut_329),  // sfix33_En30
                            .CoefOut_330(CoefOut_330),  // sfix33_En30
                            .CoefOut_331(CoefOut_331),  // sfix33_En30
                            .CoefOut_332(CoefOut_332),  // sfix33_En30
                            .CoefOut_333(CoefOut_333),  // sfix33_En30
                            .CoefOut_334(CoefOut_334),  // sfix33_En30
                            .CoefOut_335(CoefOut_335),  // sfix33_En30
                            .CoefOut_336(CoefOut_336),  // sfix33_En30
                            .CoefOut_337(CoefOut_337),  // sfix33_En30
                            .CoefOut_338(CoefOut_338),  // sfix33_En30
                            .CoefOut_339(CoefOut_339),  // sfix33_En30
                            .CoefOut_340(CoefOut_340),  // sfix33_En30
                            .CoefOut_341(CoefOut_341),  // sfix33_En30
                            .CoefOut_342(CoefOut_342),  // sfix33_En30
                            .CoefOut_343(CoefOut_343),  // sfix33_En30
                            .CoefOut_344(CoefOut_344),  // sfix33_En30
                            .CoefOut_345(CoefOut_345),  // sfix33_En30
                            .CoefOut_346(CoefOut_346),  // sfix33_En30
                            .CoefOut_347(CoefOut_347),  // sfix33_En30
                            .CoefOut_348(CoefOut_348),  // sfix33_En30
                            .CoefOut_349(CoefOut_349),  // sfix33_En30
                            .CoefOut_350(CoefOut_350),  // sfix33_En30
                            .CoefOut_351(CoefOut_351),  // sfix33_En30
                            .CoefOut_352(CoefOut_352),  // sfix33_En30
                            .CoefOut_353(CoefOut_353),  // sfix33_En30
                            .CoefOut_354(CoefOut_354),  // sfix33_En30
                            .CoefOut_355(CoefOut_355),  // sfix33_En30
                            .CoefOut_356(CoefOut_356),  // sfix33_En30
                            .CoefOut_357(CoefOut_357),  // sfix33_En30
                            .CoefOut_358(CoefOut_358),  // sfix33_En30
                            .CoefOut_359(CoefOut_359),  // sfix33_En30
                            .CoefOut_360(CoefOut_360),  // sfix33_En30
                            .CoefOut_361(CoefOut_361),  // sfix33_En30
                            .CoefOut_362(CoefOut_362),  // sfix33_En30
                            .CoefOut_363(CoefOut_363),  // sfix33_En30
                            .CoefOut_364(CoefOut_364),  // sfix33_En30
                            .CoefOut_365(CoefOut_365),  // sfix33_En30
                            .CoefOut_366(CoefOut_366),  // sfix33_En30
                            .CoefOut_367(CoefOut_367),  // sfix33_En30
                            .CoefOut_368(CoefOut_368),  // sfix33_En30
                            .CoefOut_369(CoefOut_369),  // sfix33_En30
                            .CoefOut_370(CoefOut_370),  // sfix33_En30
                            .CoefOut_371(CoefOut_371),  // sfix33_En30
                            .CoefOut_372(CoefOut_372),  // sfix33_En30
                            .CoefOut_373(CoefOut_373),  // sfix33_En30
                            .CoefOut_374(CoefOut_374),  // sfix33_En30
                            .CoefOut_375(CoefOut_375),  // sfix33_En30
                            .CoefOut_376(CoefOut_376),  // sfix33_En30
                            .CoefOut_377(CoefOut_377),  // sfix33_En30
                            .CoefOut_378(CoefOut_378),  // sfix33_En30
                            .CoefOut_379(CoefOut_379),  // sfix33_En30
                            .CoefOut_380(CoefOut_380),  // sfix33_En30
                            .CoefOut_381(CoefOut_381),  // sfix33_En30
                            .CoefOut_382(CoefOut_382),  // sfix33_En30
                            .CoefOut_383(CoefOut_383),  // sfix33_En30
                            .CoefOut_384(CoefOut_384),  // sfix33_En30
                            .CoefOut_385(CoefOut_385),  // sfix33_En30
                            .CoefOut_386(CoefOut_386),  // sfix33_En30
                            .CoefOut_387(CoefOut_387),  // sfix33_En30
                            .CoefOut_388(CoefOut_388),  // sfix33_En30
                            .CoefOut_389(CoefOut_389),  // sfix33_En30
                            .CoefOut_390(CoefOut_390),  // sfix33_En30
                            .CoefOut_391(CoefOut_391),  // sfix33_En30
                            .CoefOut_392(CoefOut_392),  // sfix33_En30
                            .CoefOut_393(CoefOut_393),  // sfix33_En30
                            .CoefOut_394(CoefOut_394),  // sfix33_En30
                            .CoefOut_395(CoefOut_395),  // sfix33_En30
                            .CoefOut_396(CoefOut_396),  // sfix33_En30
                            .CoefOut_397(CoefOut_397),  // sfix33_En30
                            .CoefOut_398(CoefOut_398),  // sfix33_En30
                            .CoefOut_399(CoefOut_399),  // sfix33_En30
                            .CoefOut_400(CoefOut_400),  // sfix33_En30
                            .CoefOut_401(CoefOut_401),  // sfix33_En30
                            .CoefOut_402(CoefOut_402),  // sfix33_En30
                            .CoefOut_403(CoefOut_403),  // sfix33_En30
                            .CoefOut_404(CoefOut_404),  // sfix33_En30
                            .CoefOut_405(CoefOut_405),  // sfix33_En30
                            .CoefOut_406(CoefOut_406),  // sfix33_En30
                            .CoefOut_407(CoefOut_407),  // sfix33_En30
                            .CoefOut_408(CoefOut_408),  // sfix33_En30
                            .CoefOut_409(CoefOut_409),  // sfix33_En30
                            .CoefOut_410(CoefOut_410),  // sfix33_En30
                            .CoefOut_411(CoefOut_411),  // sfix33_En30
                            .CoefOut_412(CoefOut_412),  // sfix33_En30
                            .CoefOut_413(CoefOut_413),  // sfix33_En30
                            .CoefOut_414(CoefOut_414),  // sfix33_En30
                            .CoefOut_415(CoefOut_415),  // sfix33_En30
                            .CoefOut_416(CoefOut_416),  // sfix33_En30
                            .CoefOut_417(CoefOut_417),  // sfix33_En30
                            .CoefOut_418(CoefOut_418),  // sfix33_En30
                            .CoefOut_419(CoefOut_419),  // sfix33_En30
                            .CoefOut_420(CoefOut_420),  // sfix33_En30
                            .CoefOut_421(CoefOut_421),  // sfix33_En30
                            .CoefOut_422(CoefOut_422),  // sfix33_En30
                            .CoefOut_423(CoefOut_423),  // sfix33_En30
                            .CoefOut_424(CoefOut_424),  // sfix33_En30
                            .CoefOut_425(CoefOut_425),  // sfix33_En30
                            .CoefOut_426(CoefOut_426),  // sfix33_En30
                            .CoefOut_427(CoefOut_427),  // sfix33_En30
                            .CoefOut_428(CoefOut_428),  // sfix33_En30
                            .CoefOut_429(CoefOut_429),  // sfix33_En30
                            .CoefOut_430(CoefOut_430),  // sfix33_En30
                            .CoefOut_431(CoefOut_431),  // sfix33_En30
                            .CoefOut_432(CoefOut_432),  // sfix33_En30
                            .CoefOut_433(CoefOut_433),  // sfix33_En30
                            .CoefOut_434(CoefOut_434),  // sfix33_En30
                            .CoefOut_435(CoefOut_435),  // sfix33_En30
                            .CoefOut_436(CoefOut_436),  // sfix33_En30
                            .CoefOut_437(CoefOut_437),  // sfix33_En30
                            .CoefOut_438(CoefOut_438),  // sfix33_En30
                            .CoefOut_439(CoefOut_439),  // sfix33_En30
                            .CoefOut_440(CoefOut_440),  // sfix33_En30
                            .CoefOut_441(CoefOut_441),  // sfix33_En30
                            .CoefOut_442(CoefOut_442),  // sfix33_En30
                            .CoefOut_443(CoefOut_443),  // sfix33_En30
                            .CoefOut_444(CoefOut_444),  // sfix33_En30
                            .CoefOut_445(CoefOut_445),  // sfix33_En30
                            .CoefOut_446(CoefOut_446),  // sfix33_En30
                            .CoefOut_447(CoefOut_447),  // sfix33_En30
                            .CoefOut_448(CoefOut_448),  // sfix33_En30
                            .CoefOut_449(CoefOut_449),  // sfix33_En30
                            .CoefOut_450(CoefOut_450),  // sfix33_En30
                            .CoefOut_451(CoefOut_451),  // sfix33_En30
                            .CoefOut_452(CoefOut_452),  // sfix33_En30
                            .CoefOut_453(CoefOut_453),  // sfix33_En30
                            .CoefOut_454(CoefOut_454),  // sfix33_En30
                            .CoefOut_455(CoefOut_455),  // sfix33_En30
                            .CoefOut_456(CoefOut_456),  // sfix33_En30
                            .CoefOut_457(CoefOut_457),  // sfix33_En30
                            .CoefOut_458(CoefOut_458),  // sfix33_En30
                            .CoefOut_459(CoefOut_459),  // sfix33_En30
                            .CoefOut_460(CoefOut_460),  // sfix33_En30
                            .CoefOut_461(CoefOut_461),  // sfix33_En30
                            .CoefOut_462(CoefOut_462),  // sfix33_En30
                            .CoefOut_463(CoefOut_463),  // sfix33_En30
                            .CoefOut_464(CoefOut_464),  // sfix33_En30
                            .CoefOut_465(CoefOut_465),  // sfix33_En30
                            .CoefOut_466(CoefOut_466),  // sfix33_En30
                            .CoefOut_467(CoefOut_467),  // sfix33_En30
                            .CoefOut_468(CoefOut_468),  // sfix33_En30
                            .CoefOut_469(CoefOut_469),  // sfix33_En30
                            .CoefOut_470(CoefOut_470),  // sfix33_En30
                            .CoefOut_471(CoefOut_471),  // sfix33_En30
                            .CoefOut_472(CoefOut_472),  // sfix33_En30
                            .CoefOut_473(CoefOut_473),  // sfix33_En30
                            .CoefOut_474(CoefOut_474),  // sfix33_En30
                            .CoefOut_475(CoefOut_475),  // sfix33_En30
                            .CoefOut_476(CoefOut_476),  // sfix33_En30
                            .CoefOut_477(CoefOut_477),  // sfix33_En30
                            .CoefOut_478(CoefOut_478),  // sfix33_En30
                            .CoefOut_479(CoefOut_479),  // sfix33_En30
                            .CoefOut_480(CoefOut_480),  // sfix33_En30
                            .CoefOut_481(CoefOut_481),  // sfix33_En30
                            .CoefOut_482(CoefOut_482),  // sfix33_En30
                            .CoefOut_483(CoefOut_483),  // sfix33_En30
                            .CoefOut_484(CoefOut_484),  // sfix33_En30
                            .CoefOut_485(CoefOut_485),  // sfix33_En30
                            .CoefOut_486(CoefOut_486),  // sfix33_En30
                            .CoefOut_487(CoefOut_487),  // sfix33_En30
                            .CoefOut_488(CoefOut_488),  // sfix33_En30
                            .CoefOut_489(CoefOut_489),  // sfix33_En30
                            .CoefOut_490(CoefOut_490),  // sfix33_En30
                            .CoefOut_491(CoefOut_491),  // sfix33_En30
                            .CoefOut_492(CoefOut_492),  // sfix33_En30
                            .CoefOut_493(CoefOut_493),  // sfix33_En30
                            .CoefOut_494(CoefOut_494)  // sfix33_En30
                            );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  subFilter u_subFilter_1_re (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .dinReg2_0_re(dinReg2_0_re),  // sfix16_En15
                              .coefIn_0(CoefOut_0),  // sfix33_En30
                              .coefIn_1(CoefOut_1),  // sfix33_En30
                              .coefIn_2(CoefOut_2),  // sfix33_En30
                              .coefIn_3(CoefOut_3),  // sfix33_En30
                              .coefIn_4(CoefOut_4),  // sfix33_En30
                              .coefIn_5(CoefOut_5),  // sfix33_En30
                              .coefIn_6(CoefOut_6),  // sfix33_En30
                              .coefIn_7(CoefOut_7),  // sfix33_En30
                              .coefIn_8(CoefOut_8),  // sfix33_En30
                              .coefIn_9(CoefOut_9),  // sfix33_En30
                              .coefIn_10(CoefOut_10),  // sfix33_En30
                              .coefIn_11(CoefOut_11),  // sfix33_En30
                              .coefIn_12(CoefOut_12),  // sfix33_En30
                              .coefIn_13(CoefOut_13),  // sfix33_En30
                              .coefIn_14(CoefOut_14),  // sfix33_En30
                              .coefIn_15(CoefOut_15),  // sfix33_En30
                              .coefIn_16(CoefOut_16),  // sfix33_En30
                              .coefIn_17(CoefOut_17),  // sfix33_En30
                              .coefIn_18(CoefOut_18),  // sfix33_En30
                              .coefIn_19(CoefOut_19),  // sfix33_En30
                              .coefIn_20(CoefOut_20),  // sfix33_En30
                              .coefIn_21(CoefOut_21),  // sfix33_En30
                              .coefIn_22(CoefOut_22),  // sfix33_En30
                              .coefIn_23(CoefOut_23),  // sfix33_En30
                              .coefIn_24(CoefOut_24),  // sfix33_En30
                              .coefIn_25(CoefOut_25),  // sfix33_En30
                              .coefIn_26(CoefOut_26),  // sfix33_En30
                              .coefIn_27(CoefOut_27),  // sfix33_En30
                              .coefIn_28(CoefOut_28),  // sfix33_En30
                              .coefIn_29(CoefOut_29),  // sfix33_En30
                              .coefIn_30(CoefOut_30),  // sfix33_En30
                              .coefIn_31(CoefOut_31),  // sfix33_En30
                              .coefIn_32(CoefOut_32),  // sfix33_En30
                              .coefIn_33(CoefOut_33),  // sfix33_En30
                              .coefIn_34(CoefOut_34),  // sfix33_En30
                              .coefIn_35(CoefOut_35),  // sfix33_En30
                              .coefIn_36(CoefOut_36),  // sfix33_En30
                              .coefIn_37(CoefOut_37),  // sfix33_En30
                              .coefIn_38(CoefOut_38),  // sfix33_En30
                              .coefIn_39(CoefOut_39),  // sfix33_En30
                              .coefIn_40(CoefOut_40),  // sfix33_En30
                              .coefIn_41(CoefOut_41),  // sfix33_En30
                              .coefIn_42(CoefOut_42),  // sfix33_En30
                              .coefIn_43(CoefOut_43),  // sfix33_En30
                              .coefIn_44(CoefOut_44),  // sfix33_En30
                              .coefIn_45(CoefOut_45),  // sfix33_En30
                              .coefIn_46(CoefOut_46),  // sfix33_En30
                              .coefIn_47(CoefOut_47),  // sfix33_En30
                              .coefIn_48(CoefOut_48),  // sfix33_En30
                              .coefIn_49(CoefOut_49),  // sfix33_En30
                              .coefIn_50(CoefOut_50),  // sfix33_En30
                              .coefIn_51(CoefOut_51),  // sfix33_En30
                              .coefIn_52(CoefOut_52),  // sfix33_En30
                              .coefIn_53(CoefOut_53),  // sfix33_En30
                              .coefIn_54(CoefOut_54),  // sfix33_En30
                              .coefIn_55(CoefOut_55),  // sfix33_En30
                              .coefIn_56(CoefOut_56),  // sfix33_En30
                              .coefIn_57(CoefOut_57),  // sfix33_En30
                              .coefIn_58(CoefOut_58),  // sfix33_En30
                              .coefIn_59(CoefOut_59),  // sfix33_En30
                              .coefIn_60(CoefOut_60),  // sfix33_En30
                              .coefIn_61(CoefOut_61),  // sfix33_En30
                              .coefIn_62(CoefOut_62),  // sfix33_En30
                              .coefIn_63(CoefOut_63),  // sfix33_En30
                              .coefIn_64(CoefOut_64),  // sfix33_En30
                              .coefIn_65(CoefOut_65),  // sfix33_En30
                              .coefIn_66(CoefOut_66),  // sfix33_En30
                              .coefIn_67(CoefOut_67),  // sfix33_En30
                              .coefIn_68(CoefOut_68),  // sfix33_En30
                              .coefIn_69(CoefOut_69),  // sfix33_En30
                              .coefIn_70(CoefOut_70),  // sfix33_En30
                              .coefIn_71(CoefOut_71),  // sfix33_En30
                              .coefIn_72(CoefOut_72),  // sfix33_En30
                              .coefIn_73(CoefOut_73),  // sfix33_En30
                              .coefIn_74(CoefOut_74),  // sfix33_En30
                              .coefIn_75(CoefOut_75),  // sfix33_En30
                              .coefIn_76(CoefOut_76),  // sfix33_En30
                              .coefIn_77(CoefOut_77),  // sfix33_En30
                              .coefIn_78(CoefOut_78),  // sfix33_En30
                              .coefIn_79(CoefOut_79),  // sfix33_En30
                              .coefIn_80(CoefOut_80),  // sfix33_En30
                              .coefIn_81(CoefOut_81),  // sfix33_En30
                              .coefIn_82(CoefOut_82),  // sfix33_En30
                              .coefIn_83(CoefOut_83),  // sfix33_En30
                              .coefIn_84(CoefOut_84),  // sfix33_En30
                              .coefIn_85(CoefOut_85),  // sfix33_En30
                              .coefIn_86(CoefOut_86),  // sfix33_En30
                              .coefIn_87(CoefOut_87),  // sfix33_En30
                              .coefIn_88(CoefOut_88),  // sfix33_En30
                              .coefIn_89(CoefOut_89),  // sfix33_En30
                              .coefIn_90(CoefOut_90),  // sfix33_En30
                              .coefIn_91(CoefOut_91),  // sfix33_En30
                              .coefIn_92(CoefOut_92),  // sfix33_En30
                              .coefIn_93(CoefOut_93),  // sfix33_En30
                              .coefIn_94(CoefOut_94),  // sfix33_En30
                              .coefIn_95(CoefOut_95),  // sfix33_En30
                              .coefIn_96(CoefOut_96),  // sfix33_En30
                              .coefIn_97(CoefOut_97),  // sfix33_En30
                              .coefIn_98(CoefOut_98),  // sfix33_En30
                              .coefIn_99(CoefOut_99),  // sfix33_En30
                              .coefIn_100(CoefOut_100),  // sfix33_En30
                              .coefIn_101(CoefOut_101),  // sfix33_En30
                              .coefIn_102(CoefOut_102),  // sfix33_En30
                              .coefIn_103(CoefOut_103),  // sfix33_En30
                              .coefIn_104(CoefOut_104),  // sfix33_En30
                              .coefIn_105(CoefOut_105),  // sfix33_En30
                              .coefIn_106(CoefOut_106),  // sfix33_En30
                              .coefIn_107(CoefOut_107),  // sfix33_En30
                              .coefIn_108(CoefOut_108),  // sfix33_En30
                              .coefIn_109(CoefOut_109),  // sfix33_En30
                              .coefIn_110(CoefOut_110),  // sfix33_En30
                              .coefIn_111(CoefOut_111),  // sfix33_En30
                              .coefIn_112(CoefOut_112),  // sfix33_En30
                              .coefIn_113(CoefOut_113),  // sfix33_En30
                              .coefIn_114(CoefOut_114),  // sfix33_En30
                              .coefIn_115(CoefOut_115),  // sfix33_En30
                              .coefIn_116(CoefOut_116),  // sfix33_En30
                              .coefIn_117(CoefOut_117),  // sfix33_En30
                              .coefIn_118(CoefOut_118),  // sfix33_En30
                              .coefIn_119(CoefOut_119),  // sfix33_En30
                              .coefIn_120(CoefOut_120),  // sfix33_En30
                              .coefIn_121(CoefOut_121),  // sfix33_En30
                              .coefIn_122(CoefOut_122),  // sfix33_En30
                              .coefIn_123(CoefOut_123),  // sfix33_En30
                              .coefIn_124(CoefOut_124),  // sfix33_En30
                              .coefIn_125(CoefOut_125),  // sfix33_En30
                              .coefIn_126(CoefOut_126),  // sfix33_En30
                              .coefIn_127(CoefOut_127),  // sfix33_En30
                              .coefIn_128(CoefOut_128),  // sfix33_En30
                              .coefIn_129(CoefOut_129),  // sfix33_En30
                              .coefIn_130(CoefOut_130),  // sfix33_En30
                              .coefIn_131(CoefOut_131),  // sfix33_En30
                              .coefIn_132(CoefOut_132),  // sfix33_En30
                              .coefIn_133(CoefOut_133),  // sfix33_En30
                              .coefIn_134(CoefOut_134),  // sfix33_En30
                              .coefIn_135(CoefOut_135),  // sfix33_En30
                              .coefIn_136(CoefOut_136),  // sfix33_En30
                              .coefIn_137(CoefOut_137),  // sfix33_En30
                              .coefIn_138(CoefOut_138),  // sfix33_En30
                              .coefIn_139(CoefOut_139),  // sfix33_En30
                              .coefIn_140(CoefOut_140),  // sfix33_En30
                              .coefIn_141(CoefOut_141),  // sfix33_En30
                              .coefIn_142(CoefOut_142),  // sfix33_En30
                              .coefIn_143(CoefOut_143),  // sfix33_En30
                              .coefIn_144(CoefOut_144),  // sfix33_En30
                              .coefIn_145(CoefOut_145),  // sfix33_En30
                              .coefIn_146(CoefOut_146),  // sfix33_En30
                              .coefIn_147(CoefOut_147),  // sfix33_En30
                              .coefIn_148(CoefOut_148),  // sfix33_En30
                              .coefIn_149(CoefOut_149),  // sfix33_En30
                              .coefIn_150(CoefOut_150),  // sfix33_En30
                              .coefIn_151(CoefOut_151),  // sfix33_En30
                              .coefIn_152(CoefOut_152),  // sfix33_En30
                              .coefIn_153(CoefOut_153),  // sfix33_En30
                              .coefIn_154(CoefOut_154),  // sfix33_En30
                              .coefIn_155(CoefOut_155),  // sfix33_En30
                              .coefIn_156(CoefOut_156),  // sfix33_En30
                              .coefIn_157(CoefOut_157),  // sfix33_En30
                              .coefIn_158(CoefOut_158),  // sfix33_En30
                              .coefIn_159(CoefOut_159),  // sfix33_En30
                              .coefIn_160(CoefOut_160),  // sfix33_En30
                              .coefIn_161(CoefOut_161),  // sfix33_En30
                              .coefIn_162(CoefOut_162),  // sfix33_En30
                              .coefIn_163(CoefOut_163),  // sfix33_En30
                              .coefIn_164(CoefOut_164),  // sfix33_En30
                              .coefIn_165(CoefOut_165),  // sfix33_En30
                              .coefIn_166(CoefOut_166),  // sfix33_En30
                              .coefIn_167(CoefOut_167),  // sfix33_En30
                              .coefIn_168(CoefOut_168),  // sfix33_En30
                              .coefIn_169(CoefOut_169),  // sfix33_En30
                              .coefIn_170(CoefOut_170),  // sfix33_En30
                              .coefIn_171(CoefOut_171),  // sfix33_En30
                              .coefIn_172(CoefOut_172),  // sfix33_En30
                              .coefIn_173(CoefOut_173),  // sfix33_En30
                              .coefIn_174(CoefOut_174),  // sfix33_En30
                              .coefIn_175(CoefOut_175),  // sfix33_En30
                              .coefIn_176(CoefOut_176),  // sfix33_En30
                              .coefIn_177(CoefOut_177),  // sfix33_En30
                              .coefIn_178(CoefOut_178),  // sfix33_En30
                              .coefIn_179(CoefOut_179),  // sfix33_En30
                              .coefIn_180(CoefOut_180),  // sfix33_En30
                              .coefIn_181(CoefOut_181),  // sfix33_En30
                              .coefIn_182(CoefOut_182),  // sfix33_En30
                              .coefIn_183(CoefOut_183),  // sfix33_En30
                              .coefIn_184(CoefOut_184),  // sfix33_En30
                              .coefIn_185(CoefOut_185),  // sfix33_En30
                              .coefIn_186(CoefOut_186),  // sfix33_En30
                              .coefIn_187(CoefOut_187),  // sfix33_En30
                              .coefIn_188(CoefOut_188),  // sfix33_En30
                              .coefIn_189(CoefOut_189),  // sfix33_En30
                              .coefIn_190(CoefOut_190),  // sfix33_En30
                              .coefIn_191(CoefOut_191),  // sfix33_En30
                              .coefIn_192(CoefOut_192),  // sfix33_En30
                              .coefIn_193(CoefOut_193),  // sfix33_En30
                              .coefIn_194(CoefOut_194),  // sfix33_En30
                              .coefIn_195(CoefOut_195),  // sfix33_En30
                              .coefIn_196(CoefOut_196),  // sfix33_En30
                              .coefIn_197(CoefOut_197),  // sfix33_En30
                              .coefIn_198(CoefOut_198),  // sfix33_En30
                              .coefIn_199(CoefOut_199),  // sfix33_En30
                              .coefIn_200(CoefOut_200),  // sfix33_En30
                              .coefIn_201(CoefOut_201),  // sfix33_En30
                              .coefIn_202(CoefOut_202),  // sfix33_En30
                              .coefIn_203(CoefOut_203),  // sfix33_En30
                              .coefIn_204(CoefOut_204),  // sfix33_En30
                              .coefIn_205(CoefOut_205),  // sfix33_En30
                              .coefIn_206(CoefOut_206),  // sfix33_En30
                              .coefIn_207(CoefOut_207),  // sfix33_En30
                              .coefIn_208(CoefOut_208),  // sfix33_En30
                              .coefIn_209(CoefOut_209),  // sfix33_En30
                              .coefIn_210(CoefOut_210),  // sfix33_En30
                              .coefIn_211(CoefOut_211),  // sfix33_En30
                              .coefIn_212(CoefOut_212),  // sfix33_En30
                              .coefIn_213(CoefOut_213),  // sfix33_En30
                              .coefIn_214(CoefOut_214),  // sfix33_En30
                              .coefIn_215(CoefOut_215),  // sfix33_En30
                              .coefIn_216(CoefOut_216),  // sfix33_En30
                              .coefIn_217(CoefOut_217),  // sfix33_En30
                              .coefIn_218(CoefOut_218),  // sfix33_En30
                              .coefIn_219(CoefOut_219),  // sfix33_En30
                              .coefIn_220(CoefOut_220),  // sfix33_En30
                              .coefIn_221(CoefOut_221),  // sfix33_En30
                              .coefIn_222(CoefOut_222),  // sfix33_En30
                              .coefIn_223(CoefOut_223),  // sfix33_En30
                              .coefIn_224(CoefOut_224),  // sfix33_En30
                              .coefIn_225(CoefOut_225),  // sfix33_En30
                              .coefIn_226(CoefOut_226),  // sfix33_En30
                              .coefIn_227(CoefOut_227),  // sfix33_En30
                              .coefIn_228(CoefOut_228),  // sfix33_En30
                              .coefIn_229(CoefOut_229),  // sfix33_En30
                              .coefIn_230(CoefOut_230),  // sfix33_En30
                              .coefIn_231(CoefOut_231),  // sfix33_En30
                              .coefIn_232(CoefOut_232),  // sfix33_En30
                              .coefIn_233(CoefOut_233),  // sfix33_En30
                              .coefIn_234(CoefOut_234),  // sfix33_En30
                              .coefIn_235(CoefOut_235),  // sfix33_En30
                              .coefIn_236(CoefOut_236),  // sfix33_En30
                              .coefIn_237(CoefOut_237),  // sfix33_En30
                              .coefIn_238(CoefOut_238),  // sfix33_En30
                              .coefIn_239(CoefOut_239),  // sfix33_En30
                              .coefIn_240(CoefOut_240),  // sfix33_En30
                              .coefIn_241(CoefOut_241),  // sfix33_En30
                              .coefIn_242(CoefOut_242),  // sfix33_En30
                              .coefIn_243(CoefOut_243),  // sfix33_En30
                              .coefIn_244(CoefOut_244),  // sfix33_En30
                              .coefIn_245(CoefOut_245),  // sfix33_En30
                              .coefIn_246(CoefOut_246),  // sfix33_En30
                              .coefIn_247(CoefOut_247),  // sfix33_En30
                              .coefIn_248(CoefOut_248),  // sfix33_En30
                              .coefIn_249(CoefOut_249),  // sfix33_En30
                              .coefIn_250(CoefOut_250),  // sfix33_En30
                              .coefIn_251(CoefOut_251),  // sfix33_En30
                              .coefIn_252(CoefOut_252),  // sfix33_En30
                              .coefIn_253(CoefOut_253),  // sfix33_En30
                              .coefIn_254(CoefOut_254),  // sfix33_En30
                              .coefIn_255(CoefOut_255),  // sfix33_En30
                              .coefIn_256(CoefOut_256),  // sfix33_En30
                              .coefIn_257(CoefOut_257),  // sfix33_En30
                              .coefIn_258(CoefOut_258),  // sfix33_En30
                              .coefIn_259(CoefOut_259),  // sfix33_En30
                              .coefIn_260(CoefOut_260),  // sfix33_En30
                              .coefIn_261(CoefOut_261),  // sfix33_En30
                              .coefIn_262(CoefOut_262),  // sfix33_En30
                              .coefIn_263(CoefOut_263),  // sfix33_En30
                              .coefIn_264(CoefOut_264),  // sfix33_En30
                              .coefIn_265(CoefOut_265),  // sfix33_En30
                              .coefIn_266(CoefOut_266),  // sfix33_En30
                              .coefIn_267(CoefOut_267),  // sfix33_En30
                              .coefIn_268(CoefOut_268),  // sfix33_En30
                              .coefIn_269(CoefOut_269),  // sfix33_En30
                              .coefIn_270(CoefOut_270),  // sfix33_En30
                              .coefIn_271(CoefOut_271),  // sfix33_En30
                              .coefIn_272(CoefOut_272),  // sfix33_En30
                              .coefIn_273(CoefOut_273),  // sfix33_En30
                              .coefIn_274(CoefOut_274),  // sfix33_En30
                              .coefIn_275(CoefOut_275),  // sfix33_En30
                              .coefIn_276(CoefOut_276),  // sfix33_En30
                              .coefIn_277(CoefOut_277),  // sfix33_En30
                              .coefIn_278(CoefOut_278),  // sfix33_En30
                              .coefIn_279(CoefOut_279),  // sfix33_En30
                              .coefIn_280(CoefOut_280),  // sfix33_En30
                              .coefIn_281(CoefOut_281),  // sfix33_En30
                              .coefIn_282(CoefOut_282),  // sfix33_En30
                              .coefIn_283(CoefOut_283),  // sfix33_En30
                              .coefIn_284(CoefOut_284),  // sfix33_En30
                              .coefIn_285(CoefOut_285),  // sfix33_En30
                              .coefIn_286(CoefOut_286),  // sfix33_En30
                              .coefIn_287(CoefOut_287),  // sfix33_En30
                              .coefIn_288(CoefOut_288),  // sfix33_En30
                              .coefIn_289(CoefOut_289),  // sfix33_En30
                              .coefIn_290(CoefOut_290),  // sfix33_En30
                              .coefIn_291(CoefOut_291),  // sfix33_En30
                              .coefIn_292(CoefOut_292),  // sfix33_En30
                              .coefIn_293(CoefOut_293),  // sfix33_En30
                              .coefIn_294(CoefOut_294),  // sfix33_En30
                              .coefIn_295(CoefOut_295),  // sfix33_En30
                              .coefIn_296(CoefOut_296),  // sfix33_En30
                              .coefIn_297(CoefOut_297),  // sfix33_En30
                              .coefIn_298(CoefOut_298),  // sfix33_En30
                              .coefIn_299(CoefOut_299),  // sfix33_En30
                              .coefIn_300(CoefOut_300),  // sfix33_En30
                              .coefIn_301(CoefOut_301),  // sfix33_En30
                              .coefIn_302(CoefOut_302),  // sfix33_En30
                              .coefIn_303(CoefOut_303),  // sfix33_En30
                              .coefIn_304(CoefOut_304),  // sfix33_En30
                              .coefIn_305(CoefOut_305),  // sfix33_En30
                              .coefIn_306(CoefOut_306),  // sfix33_En30
                              .coefIn_307(CoefOut_307),  // sfix33_En30
                              .coefIn_308(CoefOut_308),  // sfix33_En30
                              .coefIn_309(CoefOut_309),  // sfix33_En30
                              .coefIn_310(CoefOut_310),  // sfix33_En30
                              .coefIn_311(CoefOut_311),  // sfix33_En30
                              .coefIn_312(CoefOut_312),  // sfix33_En30
                              .coefIn_313(CoefOut_313),  // sfix33_En30
                              .coefIn_314(CoefOut_314),  // sfix33_En30
                              .coefIn_315(CoefOut_315),  // sfix33_En30
                              .coefIn_316(CoefOut_316),  // sfix33_En30
                              .coefIn_317(CoefOut_317),  // sfix33_En30
                              .coefIn_318(CoefOut_318),  // sfix33_En30
                              .coefIn_319(CoefOut_319),  // sfix33_En30
                              .coefIn_320(CoefOut_320),  // sfix33_En30
                              .coefIn_321(CoefOut_321),  // sfix33_En30
                              .coefIn_322(CoefOut_322),  // sfix33_En30
                              .coefIn_323(CoefOut_323),  // sfix33_En30
                              .coefIn_324(CoefOut_324),  // sfix33_En30
                              .coefIn_325(CoefOut_325),  // sfix33_En30
                              .coefIn_326(CoefOut_326),  // sfix33_En30
                              .coefIn_327(CoefOut_327),  // sfix33_En30
                              .coefIn_328(CoefOut_328),  // sfix33_En30
                              .coefIn_329(CoefOut_329),  // sfix33_En30
                              .coefIn_330(CoefOut_330),  // sfix33_En30
                              .coefIn_331(CoefOut_331),  // sfix33_En30
                              .coefIn_332(CoefOut_332),  // sfix33_En30
                              .coefIn_333(CoefOut_333),  // sfix33_En30
                              .coefIn_334(CoefOut_334),  // sfix33_En30
                              .coefIn_335(CoefOut_335),  // sfix33_En30
                              .coefIn_336(CoefOut_336),  // sfix33_En30
                              .coefIn_337(CoefOut_337),  // sfix33_En30
                              .coefIn_338(CoefOut_338),  // sfix33_En30
                              .coefIn_339(CoefOut_339),  // sfix33_En30
                              .coefIn_340(CoefOut_340),  // sfix33_En30
                              .coefIn_341(CoefOut_341),  // sfix33_En30
                              .coefIn_342(CoefOut_342),  // sfix33_En30
                              .coefIn_343(CoefOut_343),  // sfix33_En30
                              .coefIn_344(CoefOut_344),  // sfix33_En30
                              .coefIn_345(CoefOut_345),  // sfix33_En30
                              .coefIn_346(CoefOut_346),  // sfix33_En30
                              .coefIn_347(CoefOut_347),  // sfix33_En30
                              .coefIn_348(CoefOut_348),  // sfix33_En30
                              .coefIn_349(CoefOut_349),  // sfix33_En30
                              .coefIn_350(CoefOut_350),  // sfix33_En30
                              .coefIn_351(CoefOut_351),  // sfix33_En30
                              .coefIn_352(CoefOut_352),  // sfix33_En30
                              .coefIn_353(CoefOut_353),  // sfix33_En30
                              .coefIn_354(CoefOut_354),  // sfix33_En30
                              .coefIn_355(CoefOut_355),  // sfix33_En30
                              .coefIn_356(CoefOut_356),  // sfix33_En30
                              .coefIn_357(CoefOut_357),  // sfix33_En30
                              .coefIn_358(CoefOut_358),  // sfix33_En30
                              .coefIn_359(CoefOut_359),  // sfix33_En30
                              .coefIn_360(CoefOut_360),  // sfix33_En30
                              .coefIn_361(CoefOut_361),  // sfix33_En30
                              .coefIn_362(CoefOut_362),  // sfix33_En30
                              .coefIn_363(CoefOut_363),  // sfix33_En30
                              .coefIn_364(CoefOut_364),  // sfix33_En30
                              .coefIn_365(CoefOut_365),  // sfix33_En30
                              .coefIn_366(CoefOut_366),  // sfix33_En30
                              .coefIn_367(CoefOut_367),  // sfix33_En30
                              .coefIn_368(CoefOut_368),  // sfix33_En30
                              .coefIn_369(CoefOut_369),  // sfix33_En30
                              .coefIn_370(CoefOut_370),  // sfix33_En30
                              .coefIn_371(CoefOut_371),  // sfix33_En30
                              .coefIn_372(CoefOut_372),  // sfix33_En30
                              .coefIn_373(CoefOut_373),  // sfix33_En30
                              .coefIn_374(CoefOut_374),  // sfix33_En30
                              .coefIn_375(CoefOut_375),  // sfix33_En30
                              .coefIn_376(CoefOut_376),  // sfix33_En30
                              .coefIn_377(CoefOut_377),  // sfix33_En30
                              .coefIn_378(CoefOut_378),  // sfix33_En30
                              .coefIn_379(CoefOut_379),  // sfix33_En30
                              .coefIn_380(CoefOut_380),  // sfix33_En30
                              .coefIn_381(CoefOut_381),  // sfix33_En30
                              .coefIn_382(CoefOut_382),  // sfix33_En30
                              .coefIn_383(CoefOut_383),  // sfix33_En30
                              .coefIn_384(CoefOut_384),  // sfix33_En30
                              .coefIn_385(CoefOut_385),  // sfix33_En30
                              .coefIn_386(CoefOut_386),  // sfix33_En30
                              .coefIn_387(CoefOut_387),  // sfix33_En30
                              .coefIn_388(CoefOut_388),  // sfix33_En30
                              .coefIn_389(CoefOut_389),  // sfix33_En30
                              .coefIn_390(CoefOut_390),  // sfix33_En30
                              .coefIn_391(CoefOut_391),  // sfix33_En30
                              .coefIn_392(CoefOut_392),  // sfix33_En30
                              .coefIn_393(CoefOut_393),  // sfix33_En30
                              .coefIn_394(CoefOut_394),  // sfix33_En30
                              .coefIn_395(CoefOut_395),  // sfix33_En30
                              .coefIn_396(CoefOut_396),  // sfix33_En30
                              .coefIn_397(CoefOut_397),  // sfix33_En30
                              .coefIn_398(CoefOut_398),  // sfix33_En30
                              .coefIn_399(CoefOut_399),  // sfix33_En30
                              .coefIn_400(CoefOut_400),  // sfix33_En30
                              .coefIn_401(CoefOut_401),  // sfix33_En30
                              .coefIn_402(CoefOut_402),  // sfix33_En30
                              .coefIn_403(CoefOut_403),  // sfix33_En30
                              .coefIn_404(CoefOut_404),  // sfix33_En30
                              .coefIn_405(CoefOut_405),  // sfix33_En30
                              .coefIn_406(CoefOut_406),  // sfix33_En30
                              .coefIn_407(CoefOut_407),  // sfix33_En30
                              .coefIn_408(CoefOut_408),  // sfix33_En30
                              .coefIn_409(CoefOut_409),  // sfix33_En30
                              .coefIn_410(CoefOut_410),  // sfix33_En30
                              .coefIn_411(CoefOut_411),  // sfix33_En30
                              .coefIn_412(CoefOut_412),  // sfix33_En30
                              .coefIn_413(CoefOut_413),  // sfix33_En30
                              .coefIn_414(CoefOut_414),  // sfix33_En30
                              .coefIn_415(CoefOut_415),  // sfix33_En30
                              .coefIn_416(CoefOut_416),  // sfix33_En30
                              .coefIn_417(CoefOut_417),  // sfix33_En30
                              .coefIn_418(CoefOut_418),  // sfix33_En30
                              .coefIn_419(CoefOut_419),  // sfix33_En30
                              .coefIn_420(CoefOut_420),  // sfix33_En30
                              .coefIn_421(CoefOut_421),  // sfix33_En30
                              .coefIn_422(CoefOut_422),  // sfix33_En30
                              .coefIn_423(CoefOut_423),  // sfix33_En30
                              .coefIn_424(CoefOut_424),  // sfix33_En30
                              .coefIn_425(CoefOut_425),  // sfix33_En30
                              .coefIn_426(CoefOut_426),  // sfix33_En30
                              .coefIn_427(CoefOut_427),  // sfix33_En30
                              .coefIn_428(CoefOut_428),  // sfix33_En30
                              .coefIn_429(CoefOut_429),  // sfix33_En30
                              .coefIn_430(CoefOut_430),  // sfix33_En30
                              .coefIn_431(CoefOut_431),  // sfix33_En30
                              .coefIn_432(CoefOut_432),  // sfix33_En30
                              .coefIn_433(CoefOut_433),  // sfix33_En30
                              .coefIn_434(CoefOut_434),  // sfix33_En30
                              .coefIn_435(CoefOut_435),  // sfix33_En30
                              .coefIn_436(CoefOut_436),  // sfix33_En30
                              .coefIn_437(CoefOut_437),  // sfix33_En30
                              .coefIn_438(CoefOut_438),  // sfix33_En30
                              .coefIn_439(CoefOut_439),  // sfix33_En30
                              .coefIn_440(CoefOut_440),  // sfix33_En30
                              .coefIn_441(CoefOut_441),  // sfix33_En30
                              .coefIn_442(CoefOut_442),  // sfix33_En30
                              .coefIn_443(CoefOut_443),  // sfix33_En30
                              .coefIn_444(CoefOut_444),  // sfix33_En30
                              .coefIn_445(CoefOut_445),  // sfix33_En30
                              .coefIn_446(CoefOut_446),  // sfix33_En30
                              .coefIn_447(CoefOut_447),  // sfix33_En30
                              .coefIn_448(CoefOut_448),  // sfix33_En30
                              .coefIn_449(CoefOut_449),  // sfix33_En30
                              .coefIn_450(CoefOut_450),  // sfix33_En30
                              .coefIn_451(CoefOut_451),  // sfix33_En30
                              .coefIn_452(CoefOut_452),  // sfix33_En30
                              .coefIn_453(CoefOut_453),  // sfix33_En30
                              .coefIn_454(CoefOut_454),  // sfix33_En30
                              .coefIn_455(CoefOut_455),  // sfix33_En30
                              .coefIn_456(CoefOut_456),  // sfix33_En30
                              .coefIn_457(CoefOut_457),  // sfix33_En30
                              .coefIn_458(CoefOut_458),  // sfix33_En30
                              .coefIn_459(CoefOut_459),  // sfix33_En30
                              .coefIn_460(CoefOut_460),  // sfix33_En30
                              .coefIn_461(CoefOut_461),  // sfix33_En30
                              .coefIn_462(CoefOut_462),  // sfix33_En30
                              .coefIn_463(CoefOut_463),  // sfix33_En30
                              .coefIn_464(CoefOut_464),  // sfix33_En30
                              .coefIn_465(CoefOut_465),  // sfix33_En30
                              .coefIn_466(CoefOut_466),  // sfix33_En30
                              .coefIn_467(CoefOut_467),  // sfix33_En30
                              .coefIn_468(CoefOut_468),  // sfix33_En30
                              .coefIn_469(CoefOut_469),  // sfix33_En30
                              .coefIn_470(CoefOut_470),  // sfix33_En30
                              .coefIn_471(CoefOut_471),  // sfix33_En30
                              .coefIn_472(CoefOut_472),  // sfix33_En30
                              .coefIn_473(CoefOut_473),  // sfix33_En30
                              .coefIn_474(CoefOut_474),  // sfix33_En30
                              .coefIn_475(CoefOut_475),  // sfix33_En30
                              .coefIn_476(CoefOut_476),  // sfix33_En30
                              .coefIn_477(CoefOut_477),  // sfix33_En30
                              .coefIn_478(CoefOut_478),  // sfix33_En30
                              .coefIn_479(CoefOut_479),  // sfix33_En30
                              .coefIn_480(CoefOut_480),  // sfix33_En30
                              .coefIn_481(CoefOut_481),  // sfix33_En30
                              .coefIn_482(CoefOut_482),  // sfix33_En30
                              .coefIn_483(CoefOut_483),  // sfix33_En30
                              .coefIn_484(CoefOut_484),  // sfix33_En30
                              .coefIn_485(CoefOut_485),  // sfix33_En30
                              .coefIn_486(CoefOut_486),  // sfix33_En30
                              .coefIn_487(CoefOut_487),  // sfix33_En30
                              .coefIn_488(CoefOut_488),  // sfix33_En30
                              .coefIn_489(CoefOut_489),  // sfix33_En30
                              .coefIn_490(CoefOut_490),  // sfix33_En30
                              .coefIn_491(CoefOut_491),  // sfix33_En30
                              .coefIn_492(CoefOut_492),  // sfix33_En30
                              .coefIn_493(CoefOut_493),  // sfix33_En30
                              .coefIn_494(CoefOut_494),  // sfix33_En30
                              .dinRegVld(dinReg2Vld),
                              .syncReset(syncReset),
                              .dout_1_re(dout_1_re),  // sfix47_En45
                              .doutVld(doutVld)
                              );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter

