// -------------------------------------------------------------
// 
// File Name: /Users/yoland/Documents/MATLAB/hdlsrc/codegen/fm32bit_19kHz_filter/hdlsrc/Filter.v
// Created: 2025-12-08 16:51:37
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Filter
// Source Path: fm32bit_19kHz_filter/dsphdl.FIRFilter/Filter
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Filter19
          (clk,
           reset,
           enb,
           dataIn,
           validIn,
           syncReset,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] dataIn;  // sfix32_En30
  input   validIn;
  input   syncReset;
  output  signed [68:0] dataOut;  // sfix69_En66
  output  validOut;


  reg  dinRegVld;
  reg signed [31:0] dinReg_0_re;  // sfix32_En30
  reg signed [31:0] dinReg2_0_re;  // sfix32_En30
  wire signed [31:0] CoefOut_0;  // sfix32_En36
  wire signed [31:0] CoefOut_1;  // sfix32_En36
  wire signed [31:0] CoefOut_2;  // sfix32_En36
  wire signed [31:0] CoefOut_3;  // sfix32_En36
  wire signed [31:0] CoefOut_4;  // sfix32_En36
  wire signed [31:0] CoefOut_5;  // sfix32_En36
  wire signed [31:0] CoefOut_6;  // sfix32_En36
  wire signed [31:0] CoefOut_7;  // sfix32_En36
  wire signed [31:0] CoefOut_8;  // sfix32_En36
  wire signed [31:0] CoefOut_9;  // sfix32_En36
  wire signed [31:0] CoefOut_10;  // sfix32_En36
  wire signed [31:0] CoefOut_11;  // sfix32_En36
  wire signed [31:0] CoefOut_12;  // sfix32_En36
  wire signed [31:0] CoefOut_13;  // sfix32_En36
  wire signed [31:0] CoefOut_14;  // sfix32_En36
  wire signed [31:0] CoefOut_15;  // sfix32_En36
  wire signed [31:0] CoefOut_16;  // sfix32_En36
  wire signed [31:0] CoefOut_17;  // sfix32_En36
  wire signed [31:0] CoefOut_18;  // sfix32_En36
  wire signed [31:0] CoefOut_19;  // sfix32_En36
  wire signed [31:0] CoefOut_20;  // sfix32_En36
  wire signed [31:0] CoefOut_21;  // sfix32_En36
  wire signed [31:0] CoefOut_22;  // sfix32_En36
  wire signed [31:0] CoefOut_23;  // sfix32_En36
  wire signed [31:0] CoefOut_24;  // sfix32_En36
  wire signed [31:0] CoefOut_25;  // sfix32_En36
  wire signed [31:0] CoefOut_26;  // sfix32_En36
  wire signed [31:0] CoefOut_27;  // sfix32_En36
  wire signed [31:0] CoefOut_28;  // sfix32_En36
  wire signed [31:0] CoefOut_29;  // sfix32_En36
  wire signed [31:0] CoefOut_30;  // sfix32_En36
  wire signed [31:0] CoefOut_31;  // sfix32_En36
  wire signed [31:0] CoefOut_32;  // sfix32_En36
  wire signed [31:0] CoefOut_33;  // sfix32_En36
  wire signed [31:0] CoefOut_34;  // sfix32_En36
  wire signed [31:0] CoefOut_35;  // sfix32_En36
  wire signed [31:0] CoefOut_36;  // sfix32_En36
  wire signed [31:0] CoefOut_37;  // sfix32_En36
  wire signed [31:0] CoefOut_38;  // sfix32_En36
  wire signed [31:0] CoefOut_39;  // sfix32_En36
  wire signed [31:0] CoefOut_40;  // sfix32_En36
  wire signed [31:0] CoefOut_41;  // sfix32_En36
  wire signed [31:0] CoefOut_42;  // sfix32_En36
  wire signed [31:0] CoefOut_43;  // sfix32_En36
  wire signed [31:0] CoefOut_44;  // sfix32_En36
  wire signed [31:0] CoefOut_45;  // sfix32_En36
  wire signed [31:0] CoefOut_46;  // sfix32_En36
  wire signed [31:0] CoefOut_47;  // sfix32_En36
  wire signed [31:0] CoefOut_48;  // sfix32_En36
  wire signed [31:0] CoefOut_49;  // sfix32_En36
  wire signed [31:0] CoefOut_50;  // sfix32_En36
  wire signed [31:0] CoefOut_51;  // sfix32_En36
  wire signed [31:0] CoefOut_52;  // sfix32_En36
  wire signed [31:0] CoefOut_53;  // sfix32_En36
  wire signed [31:0] CoefOut_54;  // sfix32_En36
  wire signed [31:0] CoefOut_55;  // sfix32_En36
  wire signed [31:0] CoefOut_56;  // sfix32_En36
  wire signed [31:0] CoefOut_57;  // sfix32_En36
  wire signed [31:0] CoefOut_58;  // sfix32_En36
  wire signed [31:0] CoefOut_59;  // sfix32_En36
  wire signed [31:0] CoefOut_60;  // sfix32_En36
  wire signed [31:0] CoefOut_61;  // sfix32_En36
  wire signed [31:0] CoefOut_62;  // sfix32_En36
  wire signed [31:0] CoefOut_63;  // sfix32_En36
  wire signed [31:0] CoefOut_64;  // sfix32_En36
  wire signed [31:0] CoefOut_65;  // sfix32_En36
  wire signed [31:0] CoefOut_66;  // sfix32_En36
  wire signed [31:0] CoefOut_67;  // sfix32_En36
  wire signed [31:0] CoefOut_68;  // sfix32_En36
  wire signed [31:0] CoefOut_69;  // sfix32_En36
  wire signed [31:0] CoefOut_70;  // sfix32_En36
  wire signed [31:0] CoefOut_71;  // sfix32_En36
  wire signed [31:0] CoefOut_72;  // sfix32_En36
  wire signed [31:0] CoefOut_73;  // sfix32_En36
  wire signed [31:0] CoefOut_74;  // sfix32_En36
  wire signed [31:0] CoefOut_75;  // sfix32_En36
  wire signed [31:0] CoefOut_76;  // sfix32_En36
  wire signed [31:0] CoefOut_77;  // sfix32_En36
  wire signed [31:0] CoefOut_78;  // sfix32_En36
  wire signed [31:0] CoefOut_79;  // sfix32_En36
  wire signed [31:0] CoefOut_80;  // sfix32_En36
  wire signed [31:0] CoefOut_81;  // sfix32_En36 wire signed [31:0] CoefOut_82;  // sfix32_En36
  wire signed [31:0] CoefOut_83;  // sfix32_En36
  wire signed [31:0] CoefOut_84;  // sfix32_En36
  wire signed [31:0] CoefOut_85;  // sfix32_En36
  wire signed [31:0] CoefOut_86;  // sfix32_En36
  wire signed [31:0] CoefOut_87;  // sfix32_En36
  wire signed [31:0] CoefOut_88;  // sfix32_En36
  wire signed [31:0] CoefOut_89;  // sfix32_En36
  wire signed [31:0] CoefOut_90;  // sfix32_En36
  wire signed [31:0] CoefOut_91;  // sfix32_En36
  wire signed [31:0] CoefOut_92;  // sfix32_En36
  wire signed [31:0] CoefOut_93;  // sfix32_En36
  wire signed [31:0] CoefOut_94;  // sfix32_En36
  wire signed [31:0] CoefOut_95;  // sfix32_En36
  wire signed [31:0] CoefOut_96;  // sfix32_En36
  wire signed [31:0] CoefOut_97;  // sfix32_En36
  wire signed [31:0] CoefOut_98;  // sfix32_En36
  wire signed [31:0] CoefOut_99;  // sfix32_En36
  wire signed [31:0] CoefOut_100;  // sfix32_En36
  wire signed [31:0] CoefOut_101;  // sfix32_En36
  wire signed [31:0] CoefOut_102;  // sfix32_En36
  wire signed [31:0] CoefOut_103;  // sfix32_En36
  wire signed [31:0] CoefOut_104;  // sfix32_En36
  wire signed [31:0] CoefOut_105;  // sfix32_En36
  wire signed [31:0] CoefOut_106;  // sfix32_En36
  wire signed [31:0] CoefOut_107;  // sfix32_En36
  wire signed [31:0] CoefOut_108;  // sfix32_En36
  wire signed [31:0] CoefOut_109;  // sfix32_En36
  wire signed [31:0] CoefOut_110;  // sfix32_En36
  wire signed [31:0] CoefOut_111;  // sfix32_En36
  wire signed [31:0] CoefOut_112;  // sfix32_En36
  wire signed [31:0] CoefOut_113;  // sfix32_En36
  wire signed [31:0] CoefOut_114;  // sfix32_En36
  wire signed [31:0] CoefOut_115;  // sfix32_En36
  wire signed [31:0] CoefOut_116;  // sfix32_En36
  wire signed [31:0] CoefOut_117;  // sfix32_En36
  wire signed [31:0] CoefOut_118;  // sfix32_En36
  wire signed [31:0] CoefOut_119;  // sfix32_En36
  wire signed [31:0] CoefOut_120;  // sfix32_En36
  wire signed [31:0] CoefOut_121;  // sfix32_En36
  wire signed [31:0] CoefOut_122;  // sfix32_En36
  wire signed [31:0] CoefOut_123;  // sfix32_En36
  wire signed [31:0] CoefOut_124;  // sfix32_En36
  wire signed [31:0] CoefOut_125;  // sfix32_En36
  wire signed [31:0] CoefOut_126;  // sfix32_En36
  wire signed [31:0] CoefOut_127;  // sfix32_En36
  wire signed [31:0] CoefOut_128;  // sfix32_En36
  wire signed [31:0] CoefOut_129;  // sfix32_En36
  wire signed [31:0] CoefOut_130;  // sfix32_En36
  wire signed [31:0] CoefOut_131;  // sfix32_En36
  wire signed [31:0] CoefOut_132;  // sfix32_En36
  wire signed [31:0] CoefOut_133;  // sfix32_En36
  wire signed [31:0] CoefOut_134;  // sfix32_En36
  wire signed [31:0] CoefOut_135;  // sfix32_En36
  wire signed [31:0] CoefOut_136;  // sfix32_En36
  wire signed [31:0] CoefOut_137;  // sfix32_En36
  wire signed [31:0] CoefOut_138;  // sfix32_En36
  wire signed [31:0] CoefOut_139;  // sfix32_En36
  wire signed [31:0] CoefOut_140;  // sfix32_En36
  wire signed [31:0] CoefOut_141;  // sfix32_En36
  wire signed [31:0] CoefOut_142;  // sfix32_En36
  wire signed [31:0] CoefOut_143;  // sfix32_En36
  wire signed [31:0] CoefOut_144;  // sfix32_En36
  wire signed [31:0] CoefOut_145;  // sfix32_En36
  wire signed [31:0] CoefOut_146;  // sfix32_En36
  wire signed [31:0] CoefOut_147;  // sfix32_En36
  wire signed [31:0] CoefOut_148;  // sfix32_En36
  wire signed [31:0] CoefOut_149;  // sfix32_En36
  wire signed [31:0] CoefOut_150;  // sfix32_En36
  wire signed [31:0] CoefOut_151;  // sfix32_En36
  wire signed [31:0] CoefOut_152;  // sfix32_En36
  wire signed [31:0] CoefOut_153;  // sfix32_En36
  wire signed [31:0] CoefOut_154;  // sfix32_En36
  wire signed [31:0] CoefOut_155;  // sfix32_En36
  wire signed [31:0] CoefOut_156;  // sfix32_En36
  wire signed [31:0] CoefOut_157;  // sfix32_En36
  wire signed [31:0] CoefOut_158;  // sfix32_En36
  wire signed [31:0] CoefOut_159;  // sfix32_En36
  wire signed [31:0] CoefOut_160;  // sfix32_En36
  wire signed [31:0] CoefOut_161;  // sfix32_En36
  wire signed [31:0] CoefOut_162;  // sfix32_En36
  wire signed [31:0] CoefOut_163;  // sfix32_En36
  wire signed [31:0] CoefOut_164;  // sfix32_En36
  wire signed [31:0] CoefOut_165;  // sfix32_En36
  reg  dinReg2Vld;
  wire signed [68:0] dout_1_re;  // sfix69_En66
  wire doutVld;


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dinRegVld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinRegVld <= 1'b0;
          end
          else begin
            dinRegVld <= validIn;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dinReg_0_re <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg_0_re <= 32'sb00000000000000000000000000000000;
          end
          else begin
            if (validIn) begin
              dinReg_0_re <= dataIn;
            end
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        dinReg2_0_re <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2_0_re <= 32'sb00000000000000000000000000000000;
          end
          else begin
            if (dinRegVld) begin
              dinReg2_0_re <= dinReg_0_re;
            end
          end
        end
      end
    end

  FilterCoef19 u_CoefTable_1 (.validIn(validIn),
                            .syncReset(syncReset),
                            .CoefOut_0(CoefOut_0),  // sfix32_En36
                            .CoefOut_1(CoefOut_1),  // sfix32_En36
                            .CoefOut_2(CoefOut_2),  // sfix32_En36
                            .CoefOut_3(CoefOut_3),  // sfix32_En36
                            .CoefOut_4(CoefOut_4),  // sfix32_En36
                            .CoefOut_5(CoefOut_5),  // sfix32_En36
                            .CoefOut_6(CoefOut_6),  // sfix32_En36
                            .CoefOut_7(CoefOut_7),  // sfix32_En36
                            .CoefOut_8(CoefOut_8),  // sfix32_En36
                            .CoefOut_9(CoefOut_9),  // sfix32_En36
                            .CoefOut_10(CoefOut_10),  // sfix32_En36
                            .CoefOut_11(CoefOut_11),  // sfix32_En36
                            .CoefOut_12(CoefOut_12),  // sfix32_En36
                            .CoefOut_13(CoefOut_13),  // sfix32_En36
                            .CoefOut_14(CoefOut_14),  // sfix32_En36
                            .CoefOut_15(CoefOut_15),  // sfix32_En36
                            .CoefOut_16(CoefOut_16),  // sfix32_En36
                            .CoefOut_17(CoefOut_17),  // sfix32_En36
                            .CoefOut_18(CoefOut_18),  // sfix32_En36
                            .CoefOut_19(CoefOut_19),  // sfix32_En36
                            .CoefOut_20(CoefOut_20),  // sfix32_En36
                            .CoefOut_21(CoefOut_21),  // sfix32_En36
                            .CoefOut_22(CoefOut_22),  // sfix32_En36
                            .CoefOut_23(CoefOut_23),  // sfix32_En36
                            .CoefOut_24(CoefOut_24),  // sfix32_En36
                            .CoefOut_25(CoefOut_25),  // sfix32_En36
                            .CoefOut_26(CoefOut_26),  // sfix32_En36
                            .CoefOut_27(CoefOut_27),  // sfix32_En36
                            .CoefOut_28(CoefOut_28),  // sfix32_En36
                            .CoefOut_29(CoefOut_29),  // sfix32_En36
                            .CoefOut_30(CoefOut_30),  // sfix32_En36
                            .CoefOut_31(CoefOut_31),  // sfix32_En36
                            .CoefOut_32(CoefOut_32),  // sfix32_En36
                            .CoefOut_33(CoefOut_33),  // sfix32_En36
                            .CoefOut_34(CoefOut_34),  // sfix32_En36
                            .CoefOut_35(CoefOut_35),  // sfix32_En36
                            .CoefOut_36(CoefOut_36),  // sfix32_En36
                            .CoefOut_37(CoefOut_37),  // sfix32_En36
                            .CoefOut_38(CoefOut_38),  // sfix32_En36
                            .CoefOut_39(CoefOut_39),  // sfix32_En36
                            .CoefOut_40(CoefOut_40),  // sfix32_En36
                            .CoefOut_41(CoefOut_41),  // sfix32_En36
                            .CoefOut_42(CoefOut_42),  // sfix32_En36
                            .CoefOut_43(CoefOut_43),  // sfix32_En36
                            .CoefOut_44(CoefOut_44),  // sfix32_En36
                            .CoefOut_45(CoefOut_45),  // sfix32_En36
                            .CoefOut_46(CoefOut_46),  // sfix32_En36
                            .CoefOut_47(CoefOut_47),  // sfix32_En36
                            .CoefOut_48(CoefOut_48),  // sfix32_En36
                            .CoefOut_49(CoefOut_49),  // sfix32_En36
                            .CoefOut_50(CoefOut_50),  // sfix32_En36
                            .CoefOut_51(CoefOut_51),  // sfix32_En36
                            .CoefOut_52(CoefOut_52),  // sfix32_En36
                            .CoefOut_53(CoefOut_53),  // sfix32_En36
                            .CoefOut_54(CoefOut_54),  // sfix32_En36
                            .CoefOut_55(CoefOut_55),  // sfix32_En36
                            .CoefOut_56(CoefOut_56),  // sfix32_En36
                            .CoefOut_57(CoefOut_57),  // sfix32_En36
                            .CoefOut_58(CoefOut_58),  // sfix32_En36
                            .CoefOut_59(CoefOut_59),  // sfix32_En36
                            .CoefOut_60(CoefOut_60),  // sfix32_En36
                            .CoefOut_61(CoefOut_61),  // sfix32_En36
                            .CoefOut_62(CoefOut_62),  // sfix32_En36
                            .CoefOut_63(CoefOut_63),  // sfix32_En36
                            .CoefOut_64(CoefOut_64),  // sfix32_En36
                            .CoefOut_65(CoefOut_65),  // sfix32_En36
                            .CoefOut_66(CoefOut_66),  // sfix32_En36
                            .CoefOut_67(CoefOut_67),  // sfix32_En36
                            .CoefOut_68(CoefOut_68),  // sfix32_En36
                            .CoefOut_69(CoefOut_69),  // sfix32_En36
                            .CoefOut_70(CoefOut_70),  // sfix32_En36
                            .CoefOut_71(CoefOut_71),  // sfix32_En36
                            .CoefOut_72(CoefOut_72),  // sfix32_En36
                            .CoefOut_73(CoefOut_73),  // sfix32_En36
                            .CoefOut_74(CoefOut_74),  // sfix32_En36
                            .CoefOut_75(CoefOut_75),  // sfix32_En36
                            .CoefOut_76(CoefOut_76),  // sfix32_En36
                            .CoefOut_77(CoefOut_77),  // sfix32_En36
                            .CoefOut_78(CoefOut_78),  // sfix32_En36
                            .CoefOut_79(CoefOut_79),  // sfix32_En36
                            .CoefOut_80(CoefOut_80),  // sfix32_En36
                            .CoefOut_81(CoefOut_81),  // sfix32_En36
                            .CoefOut_82(CoefOut_82),  // sfix32_En36
                            .CoefOut_83(CoefOut_83),  // sfix32_En36
                            .CoefOut_84(CoefOut_84),  // sfix32_En36
                            .CoefOut_85(CoefOut_85),  // sfix32_En36
                            .CoefOut_86(CoefOut_86),  // sfix32_En36
                            .CoefOut_87(CoefOut_87),  // sfix32_En36
                            .CoefOut_88(CoefOut_88),  // sfix32_En36
                            .CoefOut_89(CoefOut_89),  // sfix32_En36
                            .CoefOut_90(CoefOut_90),  // sfix32_En36
                            .CoefOut_91(CoefOut_91),  // sfix32_En36
                            .CoefOut_92(CoefOut_92),  // sfix32_En36
                            .CoefOut_93(CoefOut_93),  // sfix32_En36
                            .CoefOut_94(CoefOut_94),  // sfix32_En36
                            .CoefOut_95(CoefOut_95),  // sfix32_En36
                            .CoefOut_96(CoefOut_96),  // sfix32_En36
                            .CoefOut_97(CoefOut_97),  // sfix32_En36
                            .CoefOut_98(CoefOut_98),  // sfix32_En36
                            .CoefOut_99(CoefOut_99),  // sfix32_En36
                            .CoefOut_100(CoefOut_100),  // sfix32_En36
                            .CoefOut_101(CoefOut_101),  // sfix32_En36
                            .CoefOut_102(CoefOut_102),  // sfix32_En36
                            .CoefOut_103(CoefOut_103),  // sfix32_En36
                            .CoefOut_104(CoefOut_104),  // sfix32_En36
                            .CoefOut_105(CoefOut_105),  // sfix32_En36
                            .CoefOut_106(CoefOut_106),  // sfix32_En36
                            .CoefOut_107(CoefOut_107),  // sfix32_En36
                            .CoefOut_108(CoefOut_108),  // sfix32_En36
                            .CoefOut_109(CoefOut_109),  // sfix32_En36
                            .CoefOut_110(CoefOut_110),  // sfix32_En36
                            .CoefOut_111(CoefOut_111),  // sfix32_En36
                            .CoefOut_112(CoefOut_112),  // sfix32_En36
                            .CoefOut_113(CoefOut_113),  // sfix32_En36
                            .CoefOut_114(CoefOut_114),  // sfix32_En36
                            .CoefOut_115(CoefOut_115),  // sfix32_En36
                            .CoefOut_116(CoefOut_116),  // sfix32_En36
                            .CoefOut_117(CoefOut_117),  // sfix32_En36
                            .CoefOut_118(CoefOut_118),  // sfix32_En36
                            .CoefOut_119(CoefOut_119),  // sfix32_En36
                            .CoefOut_120(CoefOut_120),  // sfix32_En36
                            .CoefOut_121(CoefOut_121),  // sfix32_En36
                            .CoefOut_122(CoefOut_122),  // sfix32_En36
                            .CoefOut_123(CoefOut_123),  // sfix32_En36
                            .CoefOut_124(CoefOut_124),  // sfix32_En36
                            .CoefOut_125(CoefOut_125),  // sfix32_En36
                            .CoefOut_126(CoefOut_126),  // sfix32_En36
                            .CoefOut_127(CoefOut_127),  // sfix32_En36
                            .CoefOut_128(CoefOut_128),  // sfix32_En36
                            .CoefOut_129(CoefOut_129),  // sfix32_En36
                            .CoefOut_130(CoefOut_130),  // sfix32_En36
                            .CoefOut_131(CoefOut_131),  // sfix32_En36
                            .CoefOut_132(CoefOut_132),  // sfix32_En36
                            .CoefOut_133(CoefOut_133),  // sfix32_En36
                            .CoefOut_134(CoefOut_134),  // sfix32_En36
                            .CoefOut_135(CoefOut_135),  // sfix32_En36
                            .CoefOut_136(CoefOut_136),  // sfix32_En36
                            .CoefOut_137(CoefOut_137),  // sfix32_En36
                            .CoefOut_138(CoefOut_138),  // sfix32_En36
                            .CoefOut_139(CoefOut_139),  // sfix32_En36
                            .CoefOut_140(CoefOut_140),  // sfix32_En36
                            .CoefOut_141(CoefOut_141),  // sfix32_En36
                            .CoefOut_142(CoefOut_142),  // sfix32_En36
                            .CoefOut_143(CoefOut_143),  // sfix32_En36
                            .CoefOut_144(CoefOut_144),  // sfix32_En36
                            .CoefOut_145(CoefOut_145),  // sfix32_En36
                            .CoefOut_146(CoefOut_146),  // sfix32_En36
                            .CoefOut_147(CoefOut_147),  // sfix32_En36
                            .CoefOut_148(CoefOut_148),  // sfix32_En36
                            .CoefOut_149(CoefOut_149),  // sfix32_En36
                            .CoefOut_150(CoefOut_150),  // sfix32_En36
                            .CoefOut_151(CoefOut_151),  // sfix32_En36
                            .CoefOut_152(CoefOut_152),  // sfix32_En36
                            .CoefOut_153(CoefOut_153),  // sfix32_En36
                            .CoefOut_154(CoefOut_154),  // sfix32_En36
                            .CoefOut_155(CoefOut_155),  // sfix32_En36
                            .CoefOut_156(CoefOut_156),  // sfix32_En36
                            .CoefOut_157(CoefOut_157),  // sfix32_En36
                            .CoefOut_158(CoefOut_158),  // sfix32_En36
                            .CoefOut_159(CoefOut_159),  // sfix32_En36
                            .CoefOut_160(CoefOut_160),  // sfix32_En36
                            .CoefOut_161(CoefOut_161),  // sfix32_En36
                            .CoefOut_162(CoefOut_162),  // sfix32_En36
                            .CoefOut_163(CoefOut_163),  // sfix32_En36
                            .CoefOut_164(CoefOut_164),  // sfix32_En36
                            .CoefOut_165(CoefOut_165)  // sfix32_En36
                            );

  always @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        dinReg2Vld <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dinReg2Vld <= 1'b0;
          end
          else begin
            dinReg2Vld <= dinRegVld;
          end
        end
      end
    end

  subFilter19 u_subFilter_1_re (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .dinReg2_0_re(dinReg2_0_re),  // sfix32_En30
                              .coefIn_0(CoefOut_0),  // sfix32_En36
                              .coefIn_1(CoefOut_1),  // sfix32_En36
                              .coefIn_2(CoefOut_2),  // sfix32_En36
                              .coefIn_3(CoefOut_3),  // sfix32_En36
                              .coefIn_4(CoefOut_4),  // sfix32_En36
                              .coefIn_5(CoefOut_5),  // sfix32_En36
                              .coefIn_6(CoefOut_6),  // sfix32_En36
                              .coefIn_7(CoefOut_7),  // sfix32_En36
                              .coefIn_8(CoefOut_8),  // sfix32_En36
                              .coefIn_9(CoefOut_9),  // sfix32_En36
                              .coefIn_10(CoefOut_10),  // sfix32_En36
                              .coefIn_11(CoefOut_11),  // sfix32_En36
                              .coefIn_12(CoefOut_12),  // sfix32_En36
                              .coefIn_13(CoefOut_13),  // sfix32_En36
                              .coefIn_14(CoefOut_14),  // sfix32_En36
                              .coefIn_15(CoefOut_15),  // sfix32_En36
                              .coefIn_16(CoefOut_16),  // sfix32_En36
                              .coefIn_17(CoefOut_17),  // sfix32_En36
                              .coefIn_18(CoefOut_18),  // sfix32_En36
                              .coefIn_19(CoefOut_19),  // sfix32_En36
                              .coefIn_20(CoefOut_20),  // sfix32_En36
                              .coefIn_21(CoefOut_21),  // sfix32_En36
                              .coefIn_22(CoefOut_22),  // sfix32_En36
                              .coefIn_23(CoefOut_23),  // sfix32_En36
                              .coefIn_24(CoefOut_24),  // sfix32_En36
                              .coefIn_25(CoefOut_25),  // sfix32_En36
                              .coefIn_26(CoefOut_26),  // sfix32_En36
                              .coefIn_27(CoefOut_27),  // sfix32_En36
                              .coefIn_28(CoefOut_28),  // sfix32_En36
                              .coefIn_29(CoefOut_29),  // sfix32_En36
                              .coefIn_30(CoefOut_30),  // sfix32_En36
                              .coefIn_31(CoefOut_31),  // sfix32_En36
                              .coefIn_32(CoefOut_32),  // sfix32_En36
                              .coefIn_33(CoefOut_33),  // sfix32_En36
                              .coefIn_34(CoefOut_34),  // sfix32_En36
                              .coefIn_35(CoefOut_35),  // sfix32_En36
                              .coefIn_36(CoefOut_36),  // sfix32_En36
                              .coefIn_37(CoefOut_37),  // sfix32_En36
                              .coefIn_38(CoefOut_38),  // sfix32_En36
                              .coefIn_39(CoefOut_39),  // sfix32_En36
                              .coefIn_40(CoefOut_40),  // sfix32_En36
                              .coefIn_41(CoefOut_41),  // sfix32_En36
                              .coefIn_42(CoefOut_42),  // sfix32_En36
                              .coefIn_43(CoefOut_43),  // sfix32_En36
                              .coefIn_44(CoefOut_44),  // sfix32_En36
                              .coefIn_45(CoefOut_45),  // sfix32_En36
                              .coefIn_46(CoefOut_46),  // sfix32_En36
                              .coefIn_47(CoefOut_47),  // sfix32_En36
                              .coefIn_48(CoefOut_48),  // sfix32_En36
                              .coefIn_49(CoefOut_49),  // sfix32_En36
                              .coefIn_50(CoefOut_50),  // sfix32_En36
                              .coefIn_51(CoefOut_51),  // sfix32_En36
                              .coefIn_52(CoefOut_52),  // sfix32_En36
                              .coefIn_53(CoefOut_53),  // sfix32_En36
                              .coefIn_54(CoefOut_54),  // sfix32_En36
                              .coefIn_55(CoefOut_55),  // sfix32_En36
                              .coefIn_56(CoefOut_56),  // sfix32_En36
                              .coefIn_57(CoefOut_57),  // sfix32_En36
                              .coefIn_58(CoefOut_58),  // sfix32_En36
                              .coefIn_59(CoefOut_59),  // sfix32_En36
                              .coefIn_60(CoefOut_60),  // sfix32_En36
                              .coefIn_61(CoefOut_61),  // sfix32_En36
                              .coefIn_62(CoefOut_62),  // sfix32_En36
                              .coefIn_63(CoefOut_63),  // sfix32_En36
                              .coefIn_64(CoefOut_64),  // sfix32_En36
                              .coefIn_65(CoefOut_65),  // sfix32_En36
                              .coefIn_66(CoefOut_66),  // sfix32_En36
                              .coefIn_67(CoefOut_67),  // sfix32_En36
                              .coefIn_68(CoefOut_68),  // sfix32_En36
                              .coefIn_69(CoefOut_69),  // sfix32_En36
                              .coefIn_70(CoefOut_70),  // sfix32_En36
                              .coefIn_71(CoefOut_71),  // sfix32_En36
                              .coefIn_72(CoefOut_72),  // sfix32_En36
                              .coefIn_73(CoefOut_73),  // sfix32_En36
                              .coefIn_74(CoefOut_74),  // sfix32_En36
                              .coefIn_75(CoefOut_75),  // sfix32_En36
                              .coefIn_76(CoefOut_76),  // sfix32_En36
                              .coefIn_77(CoefOut_77),  // sfix32_En36
                              .coefIn_78(CoefOut_78),  // sfix32_En36
                              .coefIn_79(CoefOut_79),  // sfix32_En36
                              .coefIn_80(CoefOut_80),  // sfix32_En36
                              .coefIn_81(CoefOut_81),  // sfix32_En36
                              .coefIn_82(CoefOut_82),  // sfix32_En36
                              .coefIn_83(CoefOut_83),  // sfix32_En36
                              .coefIn_84(CoefOut_84),  // sfix32_En36
                              .coefIn_85(CoefOut_85),  // sfix32_En36
                              .coefIn_86(CoefOut_86),  // sfix32_En36
                              .coefIn_87(CoefOut_87),  // sfix32_En36
                              .coefIn_88(CoefOut_88),  // sfix32_En36
                              .coefIn_89(CoefOut_89),  // sfix32_En36
                              .coefIn_90(CoefOut_90),  // sfix32_En36
                              .coefIn_91(CoefOut_91),  // sfix32_En36
                              .coefIn_92(CoefOut_92),  // sfix32_En36
                              .coefIn_93(CoefOut_93),  // sfix32_En36
                              .coefIn_94(CoefOut_94),  // sfix32_En36
                              .coefIn_95(CoefOut_95),  // sfix32_En36
                              .coefIn_96(CoefOut_96),  // sfix32_En36
                              .coefIn_97(CoefOut_97),  // sfix32_En36
                              .coefIn_98(CoefOut_98),  // sfix32_En36
                              .coefIn_99(CoefOut_99),  // sfix32_En36
                              .coefIn_100(CoefOut_100),  // sfix32_En36
                              .coefIn_101(CoefOut_101),  // sfix32_En36
                              .coefIn_102(CoefOut_102),  // sfix32_En36
                              .coefIn_103(CoefOut_103),  // sfix32_En36
                              .coefIn_104(CoefOut_104),  // sfix32_En36
                              .coefIn_105(CoefOut_105),  // sfix32_En36
                              .coefIn_106(CoefOut_106),  // sfix32_En36
                              .coefIn_107(CoefOut_107),  // sfix32_En36
                              .coefIn_108(CoefOut_108),  // sfix32_En36
                              .coefIn_109(CoefOut_109),  // sfix32_En36
                              .coefIn_110(CoefOut_110),  // sfix32_En36
                              .coefIn_111(CoefOut_111),  // sfix32_En36
                              .coefIn_112(CoefOut_112),  // sfix32_En36
                              .coefIn_113(CoefOut_113),  // sfix32_En36
                              .coefIn_114(CoefOut_114),  // sfix32_En36
                              .coefIn_115(CoefOut_115),  // sfix32_En36
                              .coefIn_116(CoefOut_116),  // sfix32_En36
                              .coefIn_117(CoefOut_117),  // sfix32_En36
                              .coefIn_118(CoefOut_118),  // sfix32_En36
                              .coefIn_119(CoefOut_119),  // sfix32_En36
                              .coefIn_120(CoefOut_120),  // sfix32_En36
                              .coefIn_121(CoefOut_121),  // sfix32_En36
                              .coefIn_122(CoefOut_122),  // sfix32_En36
                              .coefIn_123(CoefOut_123),  // sfix32_En36
                              .coefIn_124(CoefOut_124),  // sfix32_En36
                              .coefIn_125(CoefOut_125),  // sfix32_En36
                              .coefIn_126(CoefOut_126),  // sfix32_En36
                              .coefIn_127(CoefOut_127),  // sfix32_En36
                              .coefIn_128(CoefOut_128),  // sfix32_En36
                              .coefIn_129(CoefOut_129),  // sfix32_En36
                              .coefIn_130(CoefOut_130),  // sfix32_En36
                              .coefIn_131(CoefOut_131),  // sfix32_En36
                              .coefIn_132(CoefOut_132),  // sfix32_En36
                              .coefIn_133(CoefOut_133),  // sfix32_En36
                              .coefIn_134(CoefOut_134),  // sfix32_En36
                              .coefIn_135(CoefOut_135),  // sfix32_En36
                              .coefIn_136(CoefOut_136),  // sfix32_En36
                              .coefIn_137(CoefOut_137),  // sfix32_En36
                              .coefIn_138(CoefOut_138),  // sfix32_En36
                              .coefIn_139(CoefOut_139),  // sfix32_En36
                              .coefIn_140(CoefOut_140),  // sfix32_En36
                              .coefIn_141(CoefOut_141),  // sfix32_En36
                              .coefIn_142(CoefOut_142),  // sfix32_En36
                              .coefIn_143(CoefOut_143),  // sfix32_En36
                              .coefIn_144(CoefOut_144),  // sfix32_En36
                              .coefIn_145(CoefOut_145),  // sfix32_En36
                              .coefIn_146(CoefOut_146),  // sfix32_En36
                              .coefIn_147(CoefOut_147),  // sfix32_En36
                              .coefIn_148(CoefOut_148),  // sfix32_En36
                              .coefIn_149(CoefOut_149),  // sfix32_En36
                              .coefIn_150(CoefOut_150),  // sfix32_En36
                              .coefIn_151(CoefOut_151),  // sfix32_En36
                              .coefIn_152(CoefOut_152),  // sfix32_En36
                              .coefIn_153(CoefOut_153),  // sfix32_En36
                              .coefIn_154(CoefOut_154),  // sfix32_En36
                              .coefIn_155(CoefOut_155),  // sfix32_En36
                              .coefIn_156(CoefOut_156),  // sfix32_En36
                              .coefIn_157(CoefOut_157),  // sfix32_En36
                              .coefIn_158(CoefOut_158),  // sfix32_En36
                              .coefIn_159(CoefOut_159),  // sfix32_En36
                              .coefIn_160(CoefOut_160),  // sfix32_En36
                              .coefIn_161(CoefOut_161),  // sfix32_En36
                              .coefIn_162(CoefOut_162),  // sfix32_En36
                              .coefIn_163(CoefOut_163),  // sfix32_En36
                              .coefIn_164(CoefOut_164),  // sfix32_En36
                              .coefIn_165(CoefOut_165),  // sfix32_En36
                              .dinRegVld(dinReg2Vld),
                              .syncReset(syncReset),
                              .dout_1_re(dout_1_re),  // sfix69_En66
                              .doutVld(doutVld)
                              );

  assign dataOut = dout_1_re;

  assign validOut = doutVld;

endmodule  // Filter

