// -------------------------------------------------------------
// 
// File Name: /Users/yoland/Documents/MATLAB/hdlsrc/codegen/fm32bit_19kHz_filter/hdlsrc/fm32bit_19kHz_filter.v
// Created: 2025-12-08 16:51:37
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// dataOut                       ce_out        1
// validOut                      ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fm32bit_19kHz_filter
// Source Path: fm32bit_19kHz_filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fm32bit_19kHz_filter
          (clk,
           reset,
           clk_enable,
           dataIn,
           validIn,
           ce_out,
           dataOut,
           validOut);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [31:0] dataIn;  // sfix32_En30
  input   validIn;
  output  ce_out;
  output  signed [68:0] dataOut;  // sfix69_En66
  output  validOut;


  wire signed [68:0] varargout_1;  // sfix69_En66
  wire varargout_2;


  // Generated by HDL IP Designer.
  dsphdl_FIRFilter19 u_dsphdl_FIRFilter (.clk(clk),
                                       .reset(reset),
                                       .enb(clk_enable),
                                       .dataIn(dataIn),  // sfix32_En30
                                       .validIn(validIn),
                                       .dataOut(varargout_1),  // sfix69_En66
                                       .validOut(varargout_2)
                                       );

  assign dataOut = varargout_1;

  assign validOut = varargout_2;

  assign ce_out = clk_enable;

endmodule  // fm32bit_19kHz_filter

