// -------------------------------------------------------------
// 
// File Name: /Users/yoland/Documents/MATLAB/hdlsrc/codegen/fm32bit_19kHz_filter/hdlsrc/subFilter.v
// Created: 2025-12-08 16:51:37
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: subFilter
// Source Path: fm32bit_19kHz_filter/dsphdl.FIRFilter/Filter/subFilter
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module subFilter19
          (clk,
           reset,
           enb,
           dinReg2_0_re,
           coefIn_0,
           coefIn_1,
           coefIn_2,
           coefIn_3,
           coefIn_4,
           coefIn_5,
           coefIn_6,
           coefIn_7,
           coefIn_8,
           coefIn_9,
           coefIn_10,
           coefIn_11,
           coefIn_12,
           coefIn_13,
           coefIn_14,
           coefIn_15,
           coefIn_16,
           coefIn_17,
           coefIn_18,
           coefIn_19,
           coefIn_20,
           coefIn_21,
           coefIn_22,
           coefIn_23,
           coefIn_24,
           coefIn_25,
           coefIn_26,
           coefIn_27,
           coefIn_28,
           coefIn_29,
           coefIn_30,
           coefIn_31,
           coefIn_32,
           coefIn_33,
           coefIn_34,
           coefIn_35,
           coefIn_36,
           coefIn_37,
           coefIn_38,
           coefIn_39,
           coefIn_40,
           coefIn_41,
           coefIn_42,
           coefIn_43,
           coefIn_44,
           coefIn_45,
           coefIn_46,
           coefIn_47,
           coefIn_48,
           coefIn_49,
           coefIn_50,
           coefIn_51,
           coefIn_52,
           coefIn_53,
           coefIn_54,
           coefIn_55,
           coefIn_56,
           coefIn_57,
           coefIn_58,
           coefIn_59,
           coefIn_60,
           coefIn_61,
           coefIn_62,
           coefIn_63,
           coefIn_64,
           coefIn_65,
           coefIn_66,
           coefIn_67,
           coefIn_68,
           coefIn_69,
           coefIn_70,
           coefIn_71,
           coefIn_72,
           coefIn_73,
           coefIn_74,
           coefIn_75,
           coefIn_76,
           coefIn_77,
           coefIn_78,
           coefIn_79,
           coefIn_80,
           coefIn_81,
           coefIn_82,
           coefIn_83,
           coefIn_84,
           coefIn_85,
           coefIn_86,
           coefIn_87,
           coefIn_88,
           coefIn_89,
           coefIn_90,
           coefIn_91,
           coefIn_92,
           coefIn_93,
           coefIn_94,
           coefIn_95,
           coefIn_96,
           coefIn_97,
           coefIn_98,
           coefIn_99,
           coefIn_100,
           coefIn_101,
           coefIn_102,
           coefIn_103,
           coefIn_104,
           coefIn_105,
           coefIn_106,
           coefIn_107,
           coefIn_108,
           coefIn_109,
           coefIn_110,
           coefIn_111,
           coefIn_112,
           coefIn_113,
           coefIn_114,
           coefIn_115,
           coefIn_116,
           coefIn_117,
           coefIn_118,
           coefIn_119,
           coefIn_120,
           coefIn_121,
           coefIn_122,
           coefIn_123,
           coefIn_124,
           coefIn_125,
           coefIn_126,
           coefIn_127,
           coefIn_128,
           coefIn_129,
           coefIn_130,
           coefIn_131,
           coefIn_132,
           coefIn_133,
           coefIn_134,
           coefIn_135,
           coefIn_136,
           coefIn_137,
           coefIn_138,
           coefIn_139,
           coefIn_140,
           coefIn_141,
           coefIn_142,
           coefIn_143,
           coefIn_144,
           coefIn_145,
           coefIn_146,
           coefIn_147,
           coefIn_148,
           coefIn_149,
           coefIn_150,
           coefIn_151,
           coefIn_152,
           coefIn_153,
           coefIn_154,
           coefIn_155,
           coefIn_156,
           coefIn_157,
           coefIn_158,
           coefIn_159,
           coefIn_160,
           coefIn_161,
           coefIn_162,
           coefIn_163,
           coefIn_164,
           coefIn_165,
           dinRegVld,
           syncReset,
           dout_1_re,
           doutVld);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] dinReg2_0_re;  // sfix32_En30
  input   signed [31:0] coefIn_0;  // sfix32_En36
  input   signed [31:0] coefIn_1;  // sfix32_En36
  input   signed [31:0] coefIn_2;  // sfix32_En36
  input   signed [31:0] coefIn_3;  // sfix32_En36
  input   signed [31:0] coefIn_4;  // sfix32_En36
  input   signed [31:0] coefIn_5;  // sfix32_En36
  input   signed [31:0] coefIn_6;  // sfix32_En36
  input   signed [31:0] coefIn_7;  // sfix32_En36
  input   signed [31:0] coefIn_8;  // sfix32_En36
  input   signed [31:0] coefIn_9;  // sfix32_En36
  input   signed [31:0] coefIn_10;  // sfix32_En36
  input   signed [31:0] coefIn_11;  // sfix32_En36
  input   signed [31:0] coefIn_12;  // sfix32_En36
  input   signed [31:0] coefIn_13;  // sfix32_En36
  input   signed [31:0] coefIn_14;  // sfix32_En36
  input   signed [31:0] coefIn_15;  // sfix32_En36
  input   signed [31:0] coefIn_16;  // sfix32_En36
  input   signed [31:0] coefIn_17;  // sfix32_En36
  input   signed [31:0] coefIn_18;  // sfix32_En36
  input   signed [31:0] coefIn_19;  // sfix32_En36
  input   signed [31:0] coefIn_20;  // sfix32_En36
  input   signed [31:0] coefIn_21;  // sfix32_En36
  input   signed [31:0] coefIn_22;  // sfix32_En36
  input   signed [31:0] coefIn_23;  // sfix32_En36
  input   signed [31:0] coefIn_24;  // sfix32_En36
  input   signed [31:0] coefIn_25;  // sfix32_En36
  input   signed [31:0] coefIn_26;  // sfix32_En36
  input   signed [31:0] coefIn_27;  // sfix32_En36
  input   signed [31:0] coefIn_28;  // sfix32_En36
  input   signed [31:0] coefIn_29;  // sfix32_En36
  input   signed [31:0] coefIn_30;  // sfix32_En36
  input   signed [31:0] coefIn_31;  // sfix32_En36
  input   signed [31:0] coefIn_32;  // sfix32_En36
  input   signed [31:0] coefIn_33;  // sfix32_En36
  input   signed [31:0] coefIn_34;  // sfix32_En36
  input   signed [31:0] coefIn_35;  // sfix32_En36
  input   signed [31:0] coefIn_36;  // sfix32_En36
  input   signed [31:0] coefIn_37;  // sfix32_En36
  input   signed [31:0] coefIn_38;  // sfix32_En36
  input   signed [31:0] coefIn_39;  // sfix32_En36
  input   signed [31:0] coefIn_40;  // sfix32_En36
  input   signed [31:0] coefIn_41;  // sfix32_En36
  input   signed [31:0] coefIn_42;  // sfix32_En36
  input   signed [31:0] coefIn_43;  // sfix32_En36
  input   signed [31:0] coefIn_44;  // sfix32_En36
  input   signed [31:0] coefIn_45;  // sfix32_En36
  input   signed [31:0] coefIn_46;  // sfix32_En36
  input   signed [31:0] coefIn_47;  // sfix32_En36
  input   signed [31:0] coefIn_48;  // sfix32_En36
  input   signed [31:0] coefIn_49;  // sfix32_En36
  input   signed [31:0] coefIn_50;  // sfix32_En36
  input   signed [31:0] coefIn_51;  // sfix32_En36
  input   signed [31:0] coefIn_52;  // sfix32_En36
  input   signed [31:0] coefIn_53;  // sfix32_En36
  input   signed [31:0] coefIn_54;  // sfix32_En36
  input   signed [31:0] coefIn_55;  // sfix32_En36
  input   signed [31:0] coefIn_56;  // sfix32_En36
  input   signed [31:0] coefIn_57;  // sfix32_En36
  input   signed [31:0] coefIn_58;  // sfix32_En36
  input   signed [31:0] coefIn_59;  // sfix32_En36
  input   signed [31:0] coefIn_60;  // sfix32_En36
  input   signed [31:0] coefIn_61;  // sfix32_En36
  input   signed [31:0] coefIn_62;  // sfix32_En36
  input   signed [31:0] coefIn_63;  // sfix32_En36
  input   signed [31:0] coefIn_64;  // sfix32_En36
  input   signed [31:0] coefIn_65;  // sfix32_En36
  input   signed [31:0] coefIn_66;  // sfix32_En36
  input   signed [31:0] coefIn_67;  // sfix32_En36
  input   signed [31:0] coefIn_68;  // sfix32_En36
  input   signed [31:0] coefIn_69;  // sfix32_En36
  input   signed [31:0] coefIn_70;  // sfix32_En36
  input   signed [31:0] coefIn_71;  // sfix32_En36
  input   signed [31:0] coefIn_72;  // sfix32_En36
  input   signed [31:0] coefIn_73;  // sfix32_En36
  input   signed [31:0] coefIn_74;  // sfix32_En36
  input   signed [31:0] coefIn_75;  // sfix32_En36
  input   signed [31:0] coefIn_76;  // sfix32_En36
  input   signed [31:0] coefIn_77;  // sfix32_En36
  input   signed [31:0] coefIn_78;  // sfix32_En36
  input   signed [31:0] coefIn_79;  // sfix32_En36
  input   signed [31:0] coefIn_80;  // sfix32_En36
  input   signed [31:0] coefIn_81;  // sfix32_En36
  input   signed [31:0] coefIn_82;  // sfix32_En36
  input   signed [31:0] coefIn_83;  // sfix32_En36
  input   signed [31:0] coefIn_84;  // sfix32_En36
  input   signed [31:0] coefIn_85;  // sfix32_En36
  input   signed [31:0] coefIn_86;  // sfix32_En36
  input   signed [31:0] coefIn_87;  // sfix32_En36
  input   signed [31:0] coefIn_88;  // sfix32_En36
  input   signed [31:0] coefIn_89;  // sfix32_En36
  input   signed [31:0] coefIn_90;  // sfix32_En36
  input   signed [31:0] coefIn_91;  // sfix32_En36
  input   signed [31:0] coefIn_92;  // sfix32_En36
  input   signed [31:0] coefIn_93;  // sfix32_En36
  input   signed [31:0] coefIn_94;  // sfix32_En36
  input   signed [31:0] coefIn_95;  // sfix32_En36
  input   signed [31:0] coefIn_96;  // sfix32_En36
  input   signed [31:0] coefIn_97;  // sfix32_En36
  input   signed [31:0] coefIn_98;  // sfix32_En36
  input   signed [31:0] coefIn_99;  // sfix32_En36
  input   signed [31:0] coefIn_100;  // sfix32_En36
  input   signed [31:0] coefIn_101;  // sfix32_En36
  input   signed [31:0] coefIn_102;  // sfix32_En36
  input   signed [31:0] coefIn_103;  // sfix32_En36
  input   signed [31:0] coefIn_104;  // sfix32_En36
  input   signed [31:0] coefIn_105;  // sfix32_En36
  input   signed [31:0] coefIn_106;  // sfix32_En36
  input   signed [31:0] coefIn_107;  // sfix32_En36
  input   signed [31:0] coefIn_108;  // sfix32_En36
  input   signed [31:0] coefIn_109;  // sfix32_En36
  input   signed [31:0] coefIn_110;  // sfix32_En36
  input   signed [31:0] coefIn_111;  // sfix32_En36
  input   signed [31:0] coefIn_112;  // sfix32_En36
  input   signed [31:0] coefIn_113;  // sfix32_En36
  input   signed [31:0] coefIn_114;  // sfix32_En36
  input   signed [31:0] coefIn_115;  // sfix32_En36
  input   signed [31:0] coefIn_116;  // sfix32_En36
  input   signed [31:0] coefIn_117;  // sfix32_En36
  input   signed [31:0] coefIn_118;  // sfix32_En36
  input   signed [31:0] coefIn_119;  // sfix32_En36
  input   signed [31:0] coefIn_120;  // sfix32_En36
  input   signed [31:0] coefIn_121;  // sfix32_En36
  input   signed [31:0] coefIn_122;  // sfix32_En36
  input   signed [31:0] coefIn_123;  // sfix32_En36
  input   signed [31:0] coefIn_124;  // sfix32_En36
  input   signed [31:0] coefIn_125;  // sfix32_En36
  input   signed [31:0] coefIn_126;  // sfix32_En36
  input   signed [31:0] coefIn_127;  // sfix32_En36
  input   signed [31:0] coefIn_128;  // sfix32_En36
  input   signed [31:0] coefIn_129;  // sfix32_En36
  input   signed [31:0] coefIn_130;  // sfix32_En36
  input   signed [31:0] coefIn_131;  // sfix32_En36
  input   signed [31:0] coefIn_132;  // sfix32_En36
  input   signed [31:0] coefIn_133;  // sfix32_En36
  input   signed [31:0] coefIn_134;  // sfix32_En36
  input   signed [31:0] coefIn_135;  // sfix32_En36
  input   signed [31:0] coefIn_136;  // sfix32_En36
  input   signed [31:0] coefIn_137;  // sfix32_En36
  input   signed [31:0] coefIn_138;  // sfix32_En36
  input   signed [31:0] coefIn_139;  // sfix32_En36
  input   signed [31:0] coefIn_140;  // sfix32_En36
  input   signed [31:0] coefIn_141;  // sfix32_En36
  input   signed [31:0] coefIn_142;  // sfix32_En36
  input   signed [31:0] coefIn_143;  // sfix32_En36
  input   signed [31:0] coefIn_144;  // sfix32_En36
  input   signed [31:0] coefIn_145;  // sfix32_En36
  input   signed [31:0] coefIn_146;  // sfix32_En36
  input   signed [31:0] coefIn_147;  // sfix32_En36
  input   signed [31:0] coefIn_148;  // sfix32_En36
  input   signed [31:0] coefIn_149;  // sfix32_En36
  input   signed [31:0] coefIn_150;  // sfix32_En36
  input   signed [31:0] coefIn_151;  // sfix32_En36
  input   signed [31:0] coefIn_152;  // sfix32_En36
  input   signed [31:0] coefIn_153;  // sfix32_En36
  input   signed [31:0] coefIn_154;  // sfix32_En36
  input   signed [31:0] coefIn_155;  // sfix32_En36
  input   signed [31:0] coefIn_156;  // sfix32_En36
  input   signed [31:0] coefIn_157;  // sfix32_En36
  input   signed [31:0] coefIn_158;  // sfix32_En36
  input   signed [31:0] coefIn_159;  // sfix32_En36
  input   signed [31:0] coefIn_160;  // sfix32_En36
  input   signed [31:0] coefIn_161;  // sfix32_En36
  input   signed [31:0] coefIn_162;  // sfix32_En36
  input   signed [31:0] coefIn_163;  // sfix32_En36
  input   signed [31:0] coefIn_164;  // sfix32_En36
  input   signed [31:0] coefIn_165;  // sfix32_En36
  input   dinRegVld;
  input   syncReset;
  output  signed [68:0] dout_1_re;  // sfix69_En66
  output  doutVld;


  reg  [86:0] intdelay_reg;  // ufix1 [87]
  wire vldShift;
  wire vldOutTmp;
  wire signed [68:0] ZERO_OUT;  // sfix69_En66
  wire signed [68:0] addin;  // sfix69_En66
  wire signed [31:0] dinDly2;  // sfix32_En30
  wire signed [31:0] dinDly2_1;  // sfix32_En30
  wire signed [68:0] tapout;  // sfix69_En66
  wire signed [31:0] dinDly2_2;  // sfix32_En30
  wire signed [68:0] tapout_1;  // sfix69_En66
  wire signed [31:0] dinDly2_3;  // sfix32_En30
  wire signed [68:0] tapout_2;  // sfix69_En66
  wire signed [31:0] dinDly2_4;  // sfix32_En30
  wire signed [68:0] tapout_3;  // sfix69_En66
  wire signed [31:0] dinDly2_5;  // sfix32_En30
  wire signed [68:0] tapout_4;  // sfix69_En66
  wire signed [31:0] dinDly2_6;  // sfix32_En30
  wire signed [68:0] tapout_5;  // sfix69_En66
  wire signed [31:0] dinDly2_7;  // sfix32_En30
  wire signed [68:0] tapout_6;  // sfix69_En66
  wire signed [31:0] dinDly2_8;  // sfix32_En30
  wire signed [68:0] tapout_7;  // sfix69_En66
  wire signed [31:0] dinDly2_9;  // sfix32_En30
  wire signed [68:0] tapout_8;  // sfix69_En66
  wire signed [31:0] dinDly2_10;  // sfix32_En30
  wire signed [68:0] tapout_9;  // sfix69_En66
  wire signed [31:0] dinDly2_11;  // sfix32_En30
  wire signed [68:0] tapout_10;  // sfix69_En66
  wire signed [31:0] dinDly2_12;  // sfix32_En30
  wire signed [68:0] tapout_11;  // sfix69_En66
  wire signed [31:0] dinDly2_13;  // sfix32_En30
  wire signed [68:0] tapout_12;  // sfix69_En66
  wire signed [31:0] dinDly2_14;  // sfix32_En30
  wire signed [68:0] tapout_13;  // sfix69_En66
  wire signed [31:0] dinDly2_15;  // sfix32_En30
  wire signed [68:0] tapout_14;  // sfix69_En66
  wire signed [31:0] dinDly2_16;  // sfix32_En30
  wire signed [68:0] tapout_15;  // sfix69_En66
  wire signed [31:0] dinDly2_17;  // sfix32_En30
  wire signed [68:0] tapout_16;  // sfix69_En66
  wire signed [31:0] dinDly2_18;  // sfix32_En30
  wire signed [68:0] tapout_17;  // sfix69_En66
  wire signed [31:0] dinDly2_19;  // sfix32_En30
  wire signed [68:0] tapout_18;  // sfix69_En66
  wire signed [31:0] dinDly2_20;  // sfix32_En30
  wire signed [68:0] tapout_19;  // sfix69_En66
  wire signed [31:0] dinDly2_21;  // sfix32_En30
  wire signed [68:0] tapout_20;  // sfix69_En66
  wire signed [31:0] dinDly2_22;  // sfix32_En30
  wire signed [68:0] tapout_21;  // sfix69_En66
  wire signed [31:0] dinDly2_23;  // sfix32_En30
  wire signed [68:0] tapout_22;  // sfix69_En66
  wire signed [31:0] dinDly2_24;  // sfix32_En30
  wire signed [68:0] tapout_23;  // sfix69_En66
  wire signed [31:0] dinDly2_25;  // sfix32_En30
  wire signed [68:0] tapout_24;  // sfix69_En66
  wire signed [31:0] dinDly2_26;  // sfix32_En30
  wire signed [68:0] tapout_25;  // sfix69_En66
  wire signed [31:0] dinDly2_27;  // sfix32_En30
  wire signed [68:0] tapout_26;  // sfix69_En66
  wire signed [31:0] dinDly2_28;  // sfix32_En30
  wire signed [68:0] tapout_27;  // sfix69_En66
  wire signed [31:0] dinDly2_29;  // sfix32_En30
  wire signed [68:0] tapout_28;  // sfix69_En66
  wire signed [31:0] dinDly2_30;  // sfix32_En30
  wire signed [68:0] tapout_29;  // sfix69_En66
  wire signed [31:0] dinDly2_31;  // sfix32_En30
  wire signed [68:0] tapout_30;  // sfix69_En66
  wire signed [31:0] dinDly2_32;  // sfix32_En30
  wire signed [68:0] tapout_31;  // sfix69_En66
  wire signed [31:0] dinDly2_33;  // sfix32_En30
  wire signed [68:0] tapout_32;  // sfix69_En66
  wire signed [31:0] dinDly2_34;  // sfix32_En30
  wire signed [68:0] tapout_33;  // sfix69_En66
  wire signed [31:0] dinDly2_35;  // sfix32_En30
  wire signed [68:0] tapout_34;  // sfix69_En66
  wire signed [31:0] dinDly2_36;  // sfix32_En30
  wire signed [68:0] tapout_35;  // sfix69_En66
  wire signed [31:0] dinDly2_37;  // sfix32_En30
  wire signed [68:0] tapout_36;  // sfix69_En66
  wire signed [31:0] dinDly2_38;  // sfix32_En30
  wire signed [68:0] tapout_37;  // sfix69_En66
  wire signed [31:0] dinDly2_39;  // sfix32_En30
  wire signed [68:0] tapout_38;  // sfix69_En66
  wire signed [31:0] dinDly2_40;  // sfix32_En30
  wire signed [68:0] tapout_39;  // sfix69_En66
  wire signed [31:0] dinDly2_41;  // sfix32_En30
  wire signed [68:0] tapout_40;  // sfix69_En66
  wire signed [31:0] dinDly2_42;  // sfix32_En30
  wire signed [68:0] tapout_41;  // sfix69_En66
  wire signed [31:0] dinDly2_43;  // sfix32_En30
  wire signed [68:0] tapout_42;  // sfix69_En66
  wire signed [31:0] dinDly2_44;  // sfix32_En30
  wire signed [68:0] tapout_43;  // sfix69_En66
  wire signed [31:0] dinDly2_45;  // sfix32_En30
  wire signed [68:0] tapout_44;  // sfix69_En66
  wire signed [31:0] dinDly2_46;  // sfix32_En30
  wire signed [68:0] tapout_45;  // sfix69_En66
  wire signed [31:0] dinDly2_47;  // sfix32_En30
  wire signed [68:0] tapout_46;  // sfix69_En66
  wire signed [31:0] dinDly2_48;  // sfix32_En30
  wire signed [68:0] tapout_47;  // sfix69_En66
  wire signed [31:0] dinDly2_49;  // sfix32_En30
  wire signed [68:0] tapout_48;  // sfix69_En66
  wire signed [31:0] dinDly2_50;  // sfix32_En30
  wire signed [68:0] tapout_49;  // sfix69_En66
  wire signed [31:0] dinDly2_51;  // sfix32_En30
  wire signed [68:0] tapout_50;  // sfix69_En66
  wire signed [31:0] dinDly2_52;  // sfix32_En30
  wire signed [68:0] tapout_51;  // sfix69_En66
  wire signed [31:0] dinDly2_53;  // sfix32_En30
  wire signed [68:0] tapout_52;  // sfix69_En66
  wire signed [31:0] dinDly2_54;  // sfix32_En30
  wire signed [68:0] tapout_53;  // sfix69_En66
  wire signed [31:0] dinDly2_55;  // sfix32_En30
  wire signed [68:0] tapout_54;  // sfix69_En66
  wire signed [31:0] dinDly2_56;  // sfix32_En30
  wire signed [68:0] tapout_55;  // sfix69_En66
  wire signed [31:0] dinDly2_57;  // sfix32_En30
  wire signed [68:0] tapout_56;  // sfix69_En66
  wire signed [31:0] dinDly2_58;  // sfix32_En30
  wire signed [68:0] tapout_57;  // sfix69_En66
  wire signed [31:0] dinDly2_59;  // sfix32_En30
  wire signed [68:0] tapout_58;  // sfix69_En66
  wire signed [31:0] dinDly2_60;  // sfix32_En30
  wire signed [68:0] tapout_59;  // sfix69_En66
  wire signed [31:0] dinDly2_61;  // sfix32_En30
  wire signed [68:0] tapout_60;  // sfix69_En66
  wire signed [31:0] dinDly2_62;  // sfix32_En30
  wire signed [68:0] tapout_61;  // sfix69_En66
  wire signed [31:0] dinDly2_63;  // sfix32_En30
  wire signed [68:0] tapout_62;  // sfix69_En66
  wire signed [31:0] dinDly2_64;  // sfix32_En30
  wire signed [68:0] tapout_63;  // sfix69_En66
  wire signed [31:0] dinDly2_65;  // sfix32_En30
  wire signed [68:0] tapout_64;  // sfix69_En66
  wire signed [31:0] dinDly2_66;  // sfix32_En30
  wire signed [68:0] tapout_65;  // sfix69_En66
  wire signed [31:0] dinDly2_67;  // sfix32_En30
  wire signed [68:0] tapout_66;  // sfix69_En66
  wire signed [31:0] dinDly2_68;  // sfix32_En30
  wire signed [68:0] tapout_67;  // sfix69_En66
  wire signed [31:0] dinDly2_69;  // sfix32_En30
  wire signed [68:0] tapout_68;  // sfix69_En66
  wire signed [31:0] dinDly2_70;  // sfix32_En30
  wire signed [68:0] tapout_69;  // sfix69_En66
  wire signed [31:0] dinDly2_71;  // sfix32_En30
  wire signed [68:0] tapout_70;  // sfix69_En66
  wire signed [31:0] dinDly2_72;  // sfix32_En30
  wire signed [68:0] tapout_71;  // sfix69_En66
  wire signed [31:0] dinDly2_73;  // sfix32_En30
  wire signed [68:0] tapout_72;  // sfix69_En66
  wire signed [31:0] dinDly2_74;  // sfix32_En30
  wire signed [68:0] tapout_73;  // sfix69_En66
  wire signed [31:0] dinDly2_75;  // sfix32_En30
  wire signed [68:0] tapout_74;  // sfix69_En66
  wire signed [31:0] dinDly2_76;  // sfix32_En30
  wire signed [68:0] tapout_75;  // sfix69_En66
  wire signed [31:0] dinDly2_77;  // sfix32_En30
  wire signed [68:0] tapout_76;  // sfix69_En66
  wire signed [31:0] dinDly2_78;  // sfix32_En30
  wire signed [68:0] tapout_77;  // sfix69_En66
  wire signed [31:0] dinDly2_79;  // sfix32_En30
  wire signed [68:0] tapout_78;  // sfix69_En66
  wire signed [31:0] dinDly2_80;  // sfix32_En30
  wire signed [68:0] tapout_79;  // sfix69_En66
  wire signed [31:0] dinDly2_81;  // sfix32_En30
  wire signed [68:0] tapout_80;  // sfix69_En66
  wire signed [31:0] dinDly2_82;  // sfix32_En30
  wire signed [68:0] tapout_81;  // sfix69_En66
  wire signed [68:0] tapout_82;  // sfix69_En66
  wire signed [68:0] muxOut;  // sfix69_En66
  reg signed [68:0] dout_1_re_1;  // sfix69_En66
  reg  doutVld_1;


  always @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        intdelay_reg <= {87{1'b0}};
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            intdelay_reg <= {87{1'b0}};
          end
          else begin
            if (dinRegVld) begin
              intdelay_reg[0] <= dinRegVld;
              intdelay_reg[32'sd86:32'sd1] <= intdelay_reg[32'sd85:32'sd0];
            end
          end
        end
      end
    end

  assign vldShift = intdelay_reg[86];

  assign vldOutTmp = dinRegVld & vldShift;

  assign ZERO_OUT = 69'sh000000000000000000;

  assign addin = 69'sh000000000000000000;

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_1 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinReg2_0_re),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_0),  // sfix32_En36
                                              .addin(addin),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_1),  // sfix32_En30
                                              .tapout(tapout)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_2 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_1),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_1),  // sfix32_En36
                                              .addin(tapout),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_2),  // sfix32_En30
                                              .tapout(tapout_1)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_3 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_2),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_2),  // sfix32_En36
                                              .addin(tapout_1),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_3),  // sfix32_En30
                                              .tapout(tapout_2)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_4 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_3),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_3),  // sfix32_En36
                                              .addin(tapout_2),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_4),  // sfix32_En30
                                              .tapout(tapout_3)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_5 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_4),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_4),  // sfix32_En36
                                              .addin(tapout_3),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_5),  // sfix32_En30
                                              .tapout(tapout_4)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_6 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_5),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_5),  // sfix32_En36
                                              .addin(tapout_4),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_6),  // sfix32_En30
                                              .tapout(tapout_5)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_7 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_6),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_6),  // sfix32_En36
                                              .addin(tapout_5),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_7),  // sfix32_En30
                                              .tapout(tapout_6)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_8 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_7),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_7),  // sfix32_En36
                                              .addin(tapout_6),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_8),  // sfix32_En30
                                              .tapout(tapout_7)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_9 (.clk(clk),
                                              .enb(enb),
                                              .dinReg2_0_re(dinDly2_8),  // sfix32_En30
                                              .dinPreAdd(dinDly2),  // sfix32_En30
                                              .coefIn_0(coefIn_8),  // sfix32_En36
                                              .addin(tapout_7),  // sfix69_En66
                                              .dinRegVld(dinRegVld),
                                              .syncReset(syncReset),
                                              .dinDly2(dinDly2_9),  // sfix32_En30
                                              .tapout(tapout_8)  // sfix69_En66
                                              );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_10 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_9),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_9),  // sfix32_En36
                                               .addin(tapout_8),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_10),  // sfix32_En30
                                               .tapout(tapout_9)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_11 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_10),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_10),  // sfix32_En36
                                               .addin(tapout_9),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_11),  // sfix32_En30
                                               .tapout(tapout_10)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_12 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_11),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_11),  // sfix32_En36
                                               .addin(tapout_10),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_12),  // sfix32_En30
                                               .tapout(tapout_11)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_13 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_12),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_12),  // sfix32_En36
                                               .addin(tapout_11),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_13),  // sfix32_En30
                                               .tapout(tapout_12)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_14 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_13),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_13),  // sfix32_En36
                                               .addin(tapout_12),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_14),  // sfix32_En30
                                               .tapout(tapout_13)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_15 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_14),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_14),  // sfix32_En36
                                               .addin(tapout_13),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_15),  // sfix32_En30
                                               .tapout(tapout_14)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_16 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_15),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_15),  // sfix32_En36
                                               .addin(tapout_14),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_16),  // sfix32_En30
                                               .tapout(tapout_15)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_17 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_16),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_16),  // sfix32_En36
                                               .addin(tapout_15),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_17),  // sfix32_En30
                                               .tapout(tapout_16)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_18 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_17),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_17),  // sfix32_En36
                                               .addin(tapout_16),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_18),  // sfix32_En30
                                               .tapout(tapout_17)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_19 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_18),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_18),  // sfix32_En36
                                               .addin(tapout_17),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_19),  // sfix32_En30
                                               .tapout(tapout_18)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_20 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_19),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_19),  // sfix32_En36
                                               .addin(tapout_18),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_20),  // sfix32_En30
                                               .tapout(tapout_19)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_21 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_20),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_20),  // sfix32_En36
                                               .addin(tapout_19),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_21),  // sfix32_En30
                                               .tapout(tapout_20)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_22 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_21),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_21),  // sfix32_En36
                                               .addin(tapout_20),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_22),  // sfix32_En30
                                               .tapout(tapout_21)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_23 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_22),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_22),  // sfix32_En36
                                               .addin(tapout_21),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_23),  // sfix32_En30
                                               .tapout(tapout_22)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_24 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_23),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_23),  // sfix32_En36
                                               .addin(tapout_22),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_24),  // sfix32_En30
                                               .tapout(tapout_23)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_25 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_24),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_24),  // sfix32_En36
                                               .addin(tapout_23),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_25),  // sfix32_En30
                                               .tapout(tapout_24)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_26 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_25),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_25),  // sfix32_En36
                                               .addin(tapout_24),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_26),  // sfix32_En30
                                               .tapout(tapout_25)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_27 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_26),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_26),  // sfix32_En36
                                               .addin(tapout_25),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_27),  // sfix32_En30
                                               .tapout(tapout_26)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_28 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_27),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_27),  // sfix32_En36
                                               .addin(tapout_26),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_28),  // sfix32_En30
                                               .tapout(tapout_27)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_29 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_28),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_28),  // sfix32_En36
                                               .addin(tapout_27),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_29),  // sfix32_En30
                                               .tapout(tapout_28)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_30 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_29),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_29),  // sfix32_En36
                                               .addin(tapout_28),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_30),  // sfix32_En30
                                               .tapout(tapout_29)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_31 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_30),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_30),  // sfix32_En36
                                               .addin(tapout_29),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_31),  // sfix32_En30
                                               .tapout(tapout_30)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_32 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_31),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_31),  // sfix32_En36
                                               .addin(tapout_30),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_32),  // sfix32_En30
                                               .tapout(tapout_31)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_33 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_32),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_32),  // sfix32_En36
                                               .addin(tapout_31),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_33),  // sfix32_En30
                                               .tapout(tapout_32)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_34 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_33),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_33),  // sfix32_En36
                                               .addin(tapout_32),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_34),  // sfix32_En30
                                               .tapout(tapout_33)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_35 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_34),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_34),  // sfix32_En36
                                               .addin(tapout_33),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_35),  // sfix32_En30
                                               .tapout(tapout_34)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_36 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_35),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_35),  // sfix32_En36
                                               .addin(tapout_34),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_36),  // sfix32_En30
                                               .tapout(tapout_35)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_37 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_36),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_36),  // sfix32_En36
                                               .addin(tapout_35),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_37),  // sfix32_En30
                                               .tapout(tapout_36)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_38 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_37),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_37),  // sfix32_En36
                                               .addin(tapout_36),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_38),  // sfix32_En30
                                               .tapout(tapout_37)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_39 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_38),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_38),  // sfix32_En36
                                               .addin(tapout_37),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_39),  // sfix32_En30
                                               .tapout(tapout_38)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_40 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_39),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_39),  // sfix32_En36
                                               .addin(tapout_38),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_40),  // sfix32_En30
                                               .tapout(tapout_39)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_41 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_40),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_40),  // sfix32_En36
                                               .addin(tapout_39),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_41),  // sfix32_En30
                                               .tapout(tapout_40)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_42 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_41),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_41),  // sfix32_En36
                                               .addin(tapout_40),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_42),  // sfix32_En30
                                               .tapout(tapout_41)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_43 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_42),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_42),  // sfix32_En36
                                               .addin(tapout_41),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_43),  // sfix32_En30
                                               .tapout(tapout_42)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_44 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_43),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_43),  // sfix32_En36
                                               .addin(tapout_42),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_44),  // sfix32_En30
                                               .tapout(tapout_43)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_45 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_44),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_44),  // sfix32_En36
                                               .addin(tapout_43),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_45),  // sfix32_En30
                                               .tapout(tapout_44)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_46 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_45),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_45),  // sfix32_En36
                                               .addin(tapout_44),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_46),  // sfix32_En30
                                               .tapout(tapout_45)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_47 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_46),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_46),  // sfix32_En36
                                               .addin(tapout_45),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_47),  // sfix32_En30
                                               .tapout(tapout_46)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_48 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_47),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_47),  // sfix32_En36
                                               .addin(tapout_46),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_48),  // sfix32_En30
                                               .tapout(tapout_47)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_49 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_48),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_48),  // sfix32_En36
                                               .addin(tapout_47),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_49),  // sfix32_En30
                                               .tapout(tapout_48)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_50 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_49),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_49),  // sfix32_En36
                                               .addin(tapout_48),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_50),  // sfix32_En30
                                               .tapout(tapout_49)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_51 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_50),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_50),  // sfix32_En36
                                               .addin(tapout_49),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_51),  // sfix32_En30
                                               .tapout(tapout_50)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_52 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_51),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_51),  // sfix32_En36
                                               .addin(tapout_50),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_52),  // sfix32_En30
                                               .tapout(tapout_51)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_53 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_52),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_52),  // sfix32_En36
                                               .addin(tapout_51),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_53),  // sfix32_En30
                                               .tapout(tapout_52)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_54 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_53),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_53),  // sfix32_En36
                                               .addin(tapout_52),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_54),  // sfix32_En30
                                               .tapout(tapout_53)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_55 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_54),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_54),  // sfix32_En36
                                               .addin(tapout_53),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_55),  // sfix32_En30
                                               .tapout(tapout_54)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_56 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_55),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_55),  // sfix32_En36
                                               .addin(tapout_54),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_56),  // sfix32_En30
                                               .tapout(tapout_55)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_57 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_56),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_56),  // sfix32_En36
                                               .addin(tapout_55),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_57),  // sfix32_En30
                                               .tapout(tapout_56)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_58 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_57),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_57),  // sfix32_En36
                                               .addin(tapout_56),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_58),  // sfix32_En30
                                               .tapout(tapout_57)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_59 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_58),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_58),  // sfix32_En36
                                               .addin(tapout_57),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_59),  // sfix32_En30
                                               .tapout(tapout_58)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_60 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_59),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_59),  // sfix32_En36
                                               .addin(tapout_58),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_60),  // sfix32_En30
                                               .tapout(tapout_59)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_61 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_60),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_60),  // sfix32_En36
                                               .addin(tapout_59),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_61),  // sfix32_En30
                                               .tapout(tapout_60)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_62 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_61),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_61),  // sfix32_En36
                                               .addin(tapout_60),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_62),  // sfix32_En30
                                               .tapout(tapout_61)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_63 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_62),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_62),  // sfix32_En36
                                               .addin(tapout_61),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_63),  // sfix32_En30
                                               .tapout(tapout_62)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_64 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_63),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_63),  // sfix32_En36
                                               .addin(tapout_62),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_64),  // sfix32_En30
                                               .tapout(tapout_63)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_65 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_64),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_64),  // sfix32_En36
                                               .addin(tapout_63),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_65),  // sfix32_En30
                                               .tapout(tapout_64)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_66 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_65),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_65),  // sfix32_En36
                                               .addin(tapout_64),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_66),  // sfix32_En30
                                               .tapout(tapout_65)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_67 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_66),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_66),  // sfix32_En36
                                               .addin(tapout_65),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_67),  // sfix32_En30
                                               .tapout(tapout_66)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_68 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_67),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_67),  // sfix32_En36
                                               .addin(tapout_66),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_68),  // sfix32_En30
                                               .tapout(tapout_67)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_69 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_68),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_68),  // sfix32_En36
                                               .addin(tapout_67),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_69),  // sfix32_En30
                                               .tapout(tapout_68)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_70 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_69),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_69),  // sfix32_En36
                                               .addin(tapout_68),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_70),  // sfix32_En30
                                               .tapout(tapout_69)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_71 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_70),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_70),  // sfix32_En36
                                               .addin(tapout_69),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_71),  // sfix32_En30
                                               .tapout(tapout_70)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_72 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_71),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_71),  // sfix32_En36
                                               .addin(tapout_70),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_72),  // sfix32_En30
                                               .tapout(tapout_71)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_73 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_72),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_72),  // sfix32_En36
                                               .addin(tapout_71),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_73),  // sfix32_En30
                                               .tapout(tapout_72)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_74 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_73),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_73),  // sfix32_En36
                                               .addin(tapout_72),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_74),  // sfix32_En30
                                               .tapout(tapout_73)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_75 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_74),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_74),  // sfix32_En36
                                               .addin(tapout_73),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_75),  // sfix32_En30
                                               .tapout(tapout_74)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_76 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_75),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_75),  // sfix32_En36
                                               .addin(tapout_74),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_76),  // sfix32_En30
                                               .tapout(tapout_75)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_77 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_76),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_76),  // sfix32_En36
                                               .addin(tapout_75),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_77),  // sfix32_En30
                                               .tapout(tapout_76)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_78 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_77),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_77),  // sfix32_En36
                                               .addin(tapout_76),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_78),  // sfix32_En30
                                               .tapout(tapout_77)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_79 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_78),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_78),  // sfix32_En36
                                               .addin(tapout_77),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_79),  // sfix32_En30
                                               .tapout(tapout_78)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_80 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_79),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_79),  // sfix32_En36
                                               .addin(tapout_78),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_80),  // sfix32_En30
                                               .tapout(tapout_79)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_81 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_80),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_80),  // sfix32_En36
                                               .addin(tapout_79),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_81),  // sfix32_En30
                                               .tapout(tapout_80)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_82 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_81),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_81),  // sfix32_En36
                                               .addin(tapout_80),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2_82),  // sfix32_En30
                                               .tapout(tapout_81)  // sfix69_En66
                                               );

  FilterTapSystolicPreAddWvlIn19 u_FilterTap_83 (.clk(clk),
                                               .enb(enb),
                                               .dinReg2_0_re(dinDly2_82),  // sfix32_En30
                                               .dinPreAdd(dinDly2),  // sfix32_En30
                                               .coefIn_0(coefIn_82),  // sfix32_En36
                                               .addin(tapout_81),  // sfix69_En66
                                               .dinRegVld(dinRegVld),
                                               .syncReset(syncReset),
                                               .dinDly2(dinDly2),  // sfix32_En30
                                               .tapout(tapout_82)  // sfix69_En66
                                               );

  assign muxOut = (vldOutTmp == 1'b0 ? ZERO_OUT :
              tapout_82);

  always @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        dout_1_re_1 <= 69'sh000000000000000000;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            dout_1_re_1 <= 69'sh000000000000000000;
          end
          else begin
            dout_1_re_1 <= muxOut;
          end
        end
      end
    end

  always @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        doutVld_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (syncReset == 1'b1) begin
            doutVld_1 <= 1'b0;
          end
          else begin
            doutVld_1 <= vldOutTmp;
          end
        end
      end
    end

  assign dout_1_re = dout_1_re_1;

  assign doutVld = doutVld_1;

endmodule  // subFilter

